### ISSUE TITLE
overlapping client-streaming rpc calls (even on distinct connections) causes premature io.EOF on the first started stream

### ISSUE THREAD

**Issue by glycerine** [grpc/grpc-go#1151]
go 1.8 on darwin/ osx 10.11.6 El Capitan.

protoc version 3.0.0

github.com/gogo/protobuf/protoc-gen-gogo version 100ba4e885062801d56799d78530b73b178a78f3 from Tue Mar 7 19:04:53 2017 +0100

google.golang.org/grpc version 14a6be430b5164b888c95ac962129546c85831e7 from Fri Mar 24 11:29:02 2017 -0700

I'm trying to overlap two streaming rpc calls. Full code is here:
https://github.com/glycerine/grpc-demo

In particular the critical code that overlaps the two transfers is here
https://github.com/glycerine/grpc-demo/blob/master/client/client.go#L192

The grpc-demo repo is just a super simple example of client-streaming, producing a `client` and a `server` binary.

I'm hoping this is just a simple mistake on my part, because I haven't used gRPC before yesterday. 

I expected to be able to overlap the calls for bigfile3 and bigfile4 transfer (the sendFile() calls) without issue, not in the least because they are on completely distinct connections (aside: should that really be needed? Shouldn't  I be able to multiplex the calls on the same http2 connection; there are like 1G of streams available in either direction, right?). However, I always see a premature io.EOF on the 1st-to-start rpc (the bigfile4 call) when the 2nd overlapping file transfer (streaming rpc invocation of bigfile3) starts.

Repro:

on the server terminal (same box, different terminals)
~~~
$ cd ~/go/src/github.com/glycerine/grpc-demo
$ make
$ ./server/server
~~~

on the client terminal:
~~~
$ cd ~/go/src/github.com/glycerine/grpc-demo
$ ./client/client
... serial calls to sendFile() to chunk and send data and data2 succeed witout issue.
... then we generate a 512MB payload, and try sending it twice, in overlapping connections to the same server:

 generating test data of size 536870912 bytes

 client runSendFile(path='bigfile4') starting

 'bigfile4' client sees 512 chunks of size ~ 1048576 bytes

 client, on chunk 0 of 'bigfile4', checksum='3a2ccae977bdf4fa96702d9148e0e6df749c4f09440f54e54338baf30f24dfd46050f465136ad4c9451fe0c15ebcb142f266d5814be2237853eea06e9b92dab9', and cumul='3a2ccae977bdf4fa96702d9148e0e6df749c4f09440f54e54338baf30f24dfd46050f465136ad4c9451fe0c15ebcb142f266d5814be2237853eea06e9b92dab9'

 client runSendFile(path='bigfile3') starting

 'bigfile3' client sees 512 chunks of size ~ 1048576 bytes

 client, on chunk 0 of 'bigfile3', checksum='3a2ccae977bdf4fa96702d9148e0e6df749c4f09440f54e54338baf30f24dfd46050f465136ad4c9451fe0c15ebcb142f266d5814be2237853eea06e9b92dab9', and cumul='3a2ccae977bdf4fa96702d9148e0e6df749c4f09440f54e54338baf30f24dfd46050f465136ad4c9451fe0c15ebcb142f266d5814be2237853eea06e9b92dab9'

panic: 'bigfile4' we got io.EOF before the last chunk! At: 20 of 512

goroutine 1 [running]:
main.(*client).runSendFile(0xc42019f940, 0x1880980, 0xc42000e188, 0x1609521, 0x8, 0xc4202b6000, 0x20000000, 0x20000000, 0x100000, 0x100000, ...)
	/Users/jasonaten/go/src/github.com/glycerine/grpc-demo/client/client.go:85 +0xd72
main.main()
	/Users/jasonaten/go/src/github.com/glycerine/grpc-demo/client/client.go:214 +0x8cd
jasonaten@Jasons-MacBook-Pro-3:~/go/src/github.com/glycerine/grpc-demo (master) $
~~~

**Comment by glycerine** [comment]
The EOF happens even when the clients are in two distinct processes, so its got to be something on the server side.

**Comment by glycerine** [comment]
Nevermind. This was due to how I wrote the server. I was mistaken in thinking that a new instance of my structure would be instantiated for each of Serve's callbacks. Fixed now. Closing issue.
