### ISSUE TITLE
codec benchmark panic

### ISSUE THREAD

**Issue by minaevmike** [grpc/grpc-go#1639]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master
### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64
### What operating system (Linux, Windows, …) and version?
linux 4.13
### What did you do?
If possible, provide a recipe for reproducing the error.
`go test -v -run=^$ -bench=BenchmarkProtoCodec -benchmem`
### What did you expect to see?
no panic
### What did you see instead?
```
$ go test -v -run=^$ -bench=BenchmarkProtoCodec -benchmem 
goos: linux
goarch: amd64
pkg: google.golang.org/grpc
BenchmarkProtoCodec/MinPayloadSize:1/SetParallelism(1)-8         	20000000	       110 ns/op	       0 B/op	       0 allocs/op
BenchmarkProtoCodec/MinPayloadSize:1/SetParallelism(16)-8        	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkProtoCodec/MinPayloadSize:1/SetParallelism(256)-8       	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkProtoCodec/MinPayloadSize:1/SetParallelism(4096)-8      	10000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkProtoCodec/MinPayloadSize:1/SetParallelism(65536)-8     	10000000	       118 ns/op	       1 B/op	       0 allocs/op
BenchmarkProtoCodec/MinPayloadSize:16/SetParallelism(1)-8        	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkProtoCodec/MinPayloadSize:16/SetParallelism(16)-8       	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkProtoCodec/MinPayloadSize:16/SetParallelism(256)-8      	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45e3f7]

goroutine 4373940 [running]:
github.com/golang/protobuf/proto.(*Buffer).EncodeRawBytes(0xc42008a278, 0x0, 0x13, 0x13, 0x1, 0xc420018228)
	/root/work/prog/GO/src/github.com/golang/protobuf/proto/encode.go:201 +0x8f
github.com/golang/protobuf/proto.(*Buffer).enc_proto3_slice_byte(0xc42008a278, 0xc4200e2000, 0xc420b20140, 0xb76a00, 0x897680)
	/root/work/prog/GO/src/github.com/golang/protobuf/proto/encode.go:692 +0x124
github.com/golang/protobuf/proto.(*Buffer).enc_struct(0xc42008a278, 0xc4200a40a0, 0xc420b20140, 0x8ae620, 0xc420b20140)
	/root/work/prog/GO/src/github.com/golang/protobuf/proto/encode.go:1236 +0xce
github.com/golang/protobuf/proto.(*Buffer).Marshal(0xc42008a278, 0xb70080, 0xc420b20140, 0xbd5ce8, 0x0)
	/root/work/prog/GO/src/github.com/golang/protobuf/proto/encode.go:274 +0x2ad
google.golang.org/grpc.protoCodec.marshal(0x8ae620, 0xc420b20140, 0xc42008a270, 0x7c9d1d, 0xba5f70, 0x0, 0x0, 0x0)
	/root/work/prog/GO/src/google.golang.org/grpc/codec.go:62 +0xda
google.golang.org/grpc.protoCodec.Marshal(0x8ae620, 0xc420b20140, 0x0, 0x8ae620, 0xc420b20120, 0x0, 0x0)
	/root/work/prog/GO/src/google.golang.org/grpc/codec.go:72 +0x6e
google.golang.org/grpc.(*protoCodec).Marshal(0xbd5ce8, 0x8ae620, 0xc420b20140, 0x0, 0x8ae620, 0xc420b20120, 0x0, 0x0)
	<autogenerated>:1 +0x48
google.golang.org/grpc.fastMarshalAndUnmarshal(0xb6fdc0, 0xbd5ce8, 0xb70080, 0xc420b20140, 0xc46977a900)
	/root/work/prog/GO/src/google.golang.org/grpc/codec_benchmark_test.go:93 +0x59
google.golang.org/grpc.benchmarkProtoCodec(0xbd5ce8, 0xc46c618080, 0x5, 0x8, 0xc42000c020, 0xc46977a900)
	/root/work/prog/GO/src/google.golang.org/grpc/codec_benchmark_test.go:88 +0x6a
google.golang.org/grpc.BenchmarkProtoCodec.func1.1.1(0xc42000c020)
	/root/work/prog/GO/src/google.golang.org/grpc/codec_benchmark_test.go:74 +0x58
testing.(*B).RunParallel.func1(0xc42018a030, 0xc42018a018, 0xc42018a010, 0xc46977a900, 0xc42007e540)
	/usr/local/go/src/testing/benchmark.go:625 +0x9c
created by testing.(*B).RunParallel
	/usr/local/go/src/testing/benchmark.go:618 +0x199
exit status 2
FAIL	google.golang.org/grpc	16.744s
```
it seems there are some problems with proto message lifetime of parallell access.
If i copy protobuf message for each bench like this
```
--- a/codec_benchmark_test.go
+++ b/codec_benchmark_test.go
 
@@ -85,6 +84,7 @@ func benchmarkProtoCodec(codec *protoCodec, protoStructs []proto.Message, pb *te
        for pb.Next() {
                counter++
                ps := protoStructs[counter%len(protoStructs)]
+              ps = proto.Clone(ps)
                fastMarshalAndUnmarshal(codec, ps, b)
        }
 }

```
it works fine(ofcourse there are a lot allocations in benchmem)

**Comment by dfawley** [comment]
Thanks for filing the bug.  I believe the issue is that, while `Marshal` works fine with the same message being used in parallel many times, we're `Unmarshal`ing into the same destination in parallel, which doesn't even make sense to do:

https://github.com/grpc/grpc-go/blob/08a45354194cd00490a5d926825670fb928b5f76/codec_benchmark_test.go#L97

(protoStruct is a shared reference to the proto message in the slice.)

I will send out a fix in a moment that `Unmarshal`s into a local.
