### ISSUE TITLE
Fix the behavior of addrConn with empty address list

### ISSUE THREAD

**Issue by predmond** [grpc/grpc-go#1683]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

git head

### What version of Go are you using (`go version`)?

1.9

### What operating system (Linux, Windows, …) and version?

linux

### What did you do?

I've written my own resolver that resolves addresses using serf. When shutting down I eventually call resolver.ClientConn.NewAddress() with an empty array. This is causing a divide by zero in clientconn.go.

### What did you see instead?

```
I1122 12:28:00.752952    5823 resolver_conn_wrapper.go:106] [GPRC] ccResolverWrapper: sending new addresses to cc: []
I1122 12:28:00.752967    5823 clientconn.go:750] [GPRC] addrConn: tryUpdateAddrs curAddr: {192.168.1.7:33570 0  <nil>}, addrs: []
I1122 12:28:00.752974    5823 clientconn.go:763] [GPRC] addrConn: tryUpdateAddrs curAddrFound: false
I1122 12:28:00.752996    5823 pickfirst.go:68] [GPRC] pickfirstBalancer: HandleSubConnStateChange: 0xc4204ccb60, CONNECTING
panic: runtime error: integer divide by zero

goroutine 3479 [running]:
swarm/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc44bb8d400, 0x2540be400, 0x0)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:920 +0xfa0
swarm/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc44bb8d400)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:728 +0x2f
created by swarm/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:727 +0xeb
exit status 2
```

**Comment by menghanl** [comment]
Do you have some special need for `resolver.ClientConn.NewAddress()` with an empty array?
This should not be necessary because upon shutting down, all the connections will be closed.

I will make a fix for the divide by zero panic.

**Comment by predmond** [comment]
I don't explicitly call NewAddress with an empty array it just happens that way during shutdown. The resolver doesn't know anything other than the list of address is now empty (which could happen normally if all services went away for some reason)

**Comment by predmond** [comment]
I'm getting another crash when I call cc.NewServiceConfig() before any calls to NewAddress()

```
I1122 13:39:00.510892   23302 swarm.go:55] Starting swarm version <unknown> (<unknown>) go1.9
I1122 13:39:00.512396   23302 node.go:162] [NEST] serf agent binding to address 0.0.0.0:37017
I1122 13:39:00.512425   23302 node.go:178] [NEST] serf agent joining cluster at localhost:7946
I1122 13:39:00.514699   23302 resolver_conn_wrapper.go:65] [GPRC] dialing to target with scheme: "serf"
I1122 13:39:00.514920   23302 resolver.go:38] [NEST|resolver] building resolver for {serf  nest}
I1122 13:39:00.515056   23302 resolver_conn_wrapper.go:114] [GPRC] ccResolverWrapper: got new service config: {
		"loadBalancingPolicy": "round_robin"
	}
I1122 13:39:00.515137   23302 clientconn.go:649] [GPRC] ClientConn switching balancer to "round_robin"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xdae039]

goroutine 98 [running]:
swarm/vendor/google.golang.org/grpc.(*ccBalancerWrapper).close(...)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:154
swarm/vendor/google.golang.org/grpc.(*ClientConn).switchBalancer(0xc42015e780, 0xc4202ca0e0, 0xb)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:662 +0x139
swarm/vendor/google.golang.org/grpc.(*ClientConn).handleServiceConfig(0xc42015e780, 0x192bacc, 0x2b, 0x1, 0x1)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:820 +0x11f
swarm/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc4202a67b0)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:115 +0x2d6
created by swarm/vendor/google.golang.org/grpc.newCCResolverWrapper
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:84 +0x2e1
exit status 2
```

**Comment by menghanl** [comment]
I created a PR for the two problems you mentioned: https://github.com/grpc/grpc-go/pull/1684
Can you give it a try?

**Comment by predmond** [comment]
both issues are fixed by the PR. thanks!

**Comment by menghanl** [comment]
The fix was merged. But we want to make the behavior more consistent.

The change makes `NewSubConn()` with empty list return an error, and makes `UpdateAddress()` with empty list tear the addrConn down. The SubConn won't be usable after this.

Eventually we want to make the SubConn with empty address list stay in TransientFailure but still usable, and balancer still can update this SubConn's address.

This will be done in a follow-up PR. And let's keep this issue open to track this.

**Comment by menghanl** [comment]
Closing this issue as part of clean-up.
It's covered by #1742
