### ISSUE TITLE
Hanging forever on RecvCompress

### ISSUE THREAD

**Issue by mediocregopher** [grpc/grpc-go#1727]
(was asked to submit this as a sibling issue of https://github.com/GoogleCloudPlatform/google-cloud-go/issues/797)

### What version of gRPC are you using?

be07790 make load balancing policy name string case-insensitive

### What version of Go are you using (`go version`)?

go version go1.9.2 linux/amd64

### What operating system (Linux, Windows, …) and version?

```
Linux (CentOS 7) 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### What did you do?

Used the [ApplyBulk](https://godoc.org/cloud.google.com/go/bigtable#Table.ApplyBulk) bigtable method frequently.

### What did you expect to see?

It successfully submits the bulk modifications and returns nil, or some error occurs and it returns that error. 

### What did you see instead?

It often works correctly, but now and then (once every few days) ApplyBulk will hang forever, with the following stack-trace:

```
goroutine 2838 [chan receive, 681 minutes]:
google.golang.org/grpc/transport.(*Stream).RecvCompress(...)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/google.golang.org/grpc/transport/transport.go:255
google.golang.org/grpc.(*clientStream).RecvMsg(0xc42cb36240, 0xbfe2e0, 0xc46f8e65e0, 0x0, 0x0)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/google.golang.org/grpc/stream.go:428 +0xa4f
google.golang.org/genproto/googleapis/bigtable/v2.(*bigtableMutateRowsClient).Recv(0xc44ffd0c80, 0x1173e00, 0xc4421e2ae0, 0xc46f8e5830)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/google.golang.org/genproto/googleapis/bigtable/v2/bigtable.pb.go:878 +0x62
cloud.google.com/go/bigtable.(*Table).doApplyBulk(0xc46d0a46c0, 0x1173e00, 0xc4421e2ae0, 0xc457cb7000, 0x2ec, 0x2ec, 0x0, 0x0, 0x0, 0x4d9a1c, ...)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/cloud.google.com/go/bigtable/bigtable.go:681 +0x43a
cloud.google.com/go/bigtable.(*Table).ApplyBulk.func1(0x1173e00, 0xc4421e2ae0, 0x0, 0x1)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/cloud.google.com/go/bigtable/bigtable.go:613 +0x88
cloud.google.com/go/bigtable/internal/gax.invokeWithRetry(0x1173e00, 0xc4421e2ae0, 0xc46f8e57d0, 0x0, 0xc46f8e5800, 0x5f5e100, 0x77359400, 0x3ff3333333333333, 0x0, 0x0, ...)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/cloud.google.com/go/bigtable/internal/gax/invoke.go:53 +0x100
cloud.google.com/go/bigtable/internal/gax.Invoke(0x1173e00, 0xc4421e2ae0, 0xc46f8e57d0, 0x11d5300, 0x2, 0x2, 0x2ec, 0x2ec)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/cloud.google.com/go/bigtable/internal/gax/invoke.go:81 +0xc8
cloud.google.com/go/bigtable.(*Table).ApplyBulk(0xc46d0a46c0, 0x1173e00, 0xc4421e2ae0, 0xc422bf7000, 0x2ec, 0x2ec, 0xc457cb4000, 0x2ec, 0x2ec, 0x0, ...)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/cloud.google.com/go/bigtable/bigtable.go:612 +0x511
bitbucket.org/levenlabs/analytics-api/analyticsapi/aasub.(*BigTableDB).upsertByTableDirect.func2()
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/bitbucket.org/levenlabs/analytics-api/analyticsapi/aasub/db_bt.go:298 +0x11e
bitbucket.org/levenlabs/llib/workgroup.(*WorkGroup).spin(0xc4230d2f10)
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/bitbucket.org/levenlabs/llib/workgroup/workgroup.go:111 +0x45
created by bitbucket.org/levenlabs/llib/workgroup.New
        /opt/TeamCityBuild/work/rachel-3/8232227c0afde646/.deps/src/bitbucket.org/levenlabs/llib/workgroup/workgroup.go:102 +0xd7
```

It's not clear if the problem is with the bigtable driver or with grpc yet, but any help in debugging this would be greatly appreciated. The only theory we have right now is that it's _possible_ that the context might be getting cancelled prior to some event internal to grpc, but there's not a ton of proof of that.

**Comment by MakMukhi** [comment]
On a quick first look it seems like this might be a problem in gRPC code. I'll take a deeper look later today and keep you posted. Thanks for reporting this issue.

**Comment by MakMukhi** [comment]
This indeed is a gRPC issue. I'll create a fix for it today.
