### ISSUE TITLE
examples/route_guide/server/server.go fatal error: concurrent map writes and data race

### ISSUE THREAD

**Issue by sgon00** [grpc/grpc-go#1751]
### What version of gRPC are you using?

```
~/go/src/google.golang.org/grpc]$ git rev-parse HEAD
ec61302c8eeed1f9705bc51e6606220ce21f4a60
```

### What version of Go are you using (`go version`)?

```
$ go version
go version go1.9.2 linux/amd64
```

### What operating system (Linux, Windows, …) and version?

Linux, Manjaro (based on Arch Linux)

### What did you do?

I think the route_guide server.go example has a data race issue. I tried to run concurrent clients and then met the following errors:

```
$ go run server/server.go 
fatal error: concurrent map writes

goroutine 53 [running]:
runtime.throw(0x8689fa, 0x15)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc4201e3a70 sp=0xc4201e3a50 pc=0x42bb75
runtime.mapassign_faststr(0x7dfd40, 0xc420077fb0, 0xc4201ee88c, 0x3, 0xc4200b5688)
	/usr/local/go/src/runtime/hashmap_fast.go:685 +0x4da fp=0xc4201e3af0 sp=0xc4201e3a70 pc=0x40e40a
main.(*routeGuideServer).RouteChat(0xc420146460, 0xa76780, 0xc4201d4240, 0xa74560, 0xc420146460)
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x201 fp=0xc4201e3b98 sp=0xc4201e3af0 pc=0x773a81
google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler(0x807040, 0xc420146460, 0xa75dc0, 0xc4201d63c0, 0x0, 0x0)
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xb2 fp=0xc4201e3be8 sp=0xc4201e3b98 pc=0x771a32
google.golang.org/grpc.(*Server).processStreamingRPC(0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250a00, 0xc420166060, 0xaae5c0, 0x0, 0x0, 0x0)
	/home/user/go/src/google.golang.org/grpc/server.go:1032 +0xa3e fp=0xc4201e3d90 sp=0xc4201e3be8 pc=0x768eae
google.golang.org/grpc.(*Server).handleStream(0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250a00, 0x0)
	/home/user/go/src/google.golang.org/grpc/server.go:1126 +0x14c1 fp=0xc4201e3f80 sp=0xc4201e3d90 pc=0x76ab01
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4201ee270, 0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250a00)
	/home/user/go/src/google.golang.org/grpc/server.go:617 +0x9f fp=0xc4201e3fb8 sp=0xc4201e3f80 pc=0x76c5bf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4201e3fc0 sp=0xc4201e3fb8 pc=0x4595d1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/user/go/src/google.golang.org/grpc/server.go:615 +0xa1

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fbe2afaaf70, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42014e018, 0x72, 0xc42004fb00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42014e018, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc42014e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc42014e000, 0xc420200008, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e078, 0x7646a2, 0x456070, 0xc42004fdb0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000e078, 0x87dd98, 0xc420001980, 0xa76840, 0xc420200008)
	/usr/local/go/src/net/tcpsock.go:247 +0x49
google.golang.org/grpc.(*Server).Serve(0xc420001980, 0xa73820, 0xc42000e078, 0x0, 0x0)
	/home/user/go/src/google.golang.org/grpc/server.go:495 +0x196
main.main()
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:232 +0x2fd

goroutine 52 [runnable]:
main.(*routeGuideServer).RouteChat(0xc420146460, 0xa76780, 0xc4201840c0, 0xa74560, 0xc420146460)
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x201
google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler(0x807040, 0xc420146460, 0xa75dc0, 0xc42018a1e0, 0xc42002f460, 0x4118a6)
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xb2
google.golang.org/grpc.(*Server).processStreamingRPC(0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250780, 0xc420166060, 0xaae5c0, 0x0, 0x0, 0x0)
	/home/user/go/src/google.golang.org/grpc/server.go:1032 +0xa3e
google.golang.org/grpc.(*Server).handleStream(0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250780, 0x0)
	/home/user/go/src/google.golang.org/grpc/server.go:1126 +0x14c1
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4201ee270, 0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250780)
	/home/user/go/src/google.golang.org/grpc/server.go:617 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/user/go/src/google.golang.org/grpc/server.go:615 +0xa1

goroutine 34 [runnable]:
internal/poll.runtime_pollWait(0x7fbe2afaaeb0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420206018, 0x72, 0xffffffffffffff00, 0xa6faa0, 0xa6b5a8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420206018, 0xc42020a000, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420206000, 0xc42020a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420206000, 0xc42020a000, 0x8000, 0x8000, 0x140, 0x140, 0xc420251040)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420200008, 0xc42020a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc420208000, 0xc42021a038, 0x9, 0x9, 0xc420025900, 0xc420198ca8, 0x42ade6)
	/usr/local/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0xa6cc20, 0xc420208000, 0xc42021a038, 0x9, 0x9, 0x9, 0x7535d6, 0xc420249590, 0x0)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0xa6cc20, 0xc420208000, 0xc42021a038, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
golang.org/x/net/http2.readFrameHeader(0xc42021a038, 0x9, 0x9, 0xa6cc20, 0xc420208000, 0x0, 0x1000100000000, 0xf00000000, 0x0)
	/home/user/go/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc42021a000, 0xc4201f69c0, 0xc4201f69c0, 0x0, 0x0)
	/home/user/go/src/golang.org/x/net/http2/frame.go:492 +0xa4
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc42021e000, 0xc4201f6b40, 0x87ddd0)
	/home/user/go/src/google.golang.org/grpc/transport/http2_server.go:390 +0x3a
google.golang.org/grpc.(*Server).serveStreams(0xc420001980, 0xa765a0, 0xc42021e000)
	/home/user/go/src/google.golang.org/grpc/server.go:613 +0x140
google.golang.org/grpc.(*Server).handleRawConn(0xc420001980, 0xa76840, 0xc420200008)
	/home/user/go/src/google.golang.org/grpc/server.go:574 +0x5e0
created by google.golang.org/grpc.(*Server).Serve
	/home/user/go/src/google.golang.org/grpc/server.go:535 +0x632

goroutine 35 [runnable]:
google.golang.org/grpc/transport.loopyWriter(0xa74260, 0xc4201d2100, 0xc4201f6ab0, 0xc420041fb8)
	/home/user/go/src/google.golang.org/grpc/transport/transport.go:718 +0x3c6
google.golang.org/grpc/transport.newHTTP2Server.func1(0xc42021e000)
	/home/user/go/src/google.golang.org/grpc/transport/http2_server.go:256 +0x5e
created by google.golang.org/grpc/transport.newHTTP2Server
	/home/user/go/src/google.golang.org/grpc/transport/http2_server.go:255 +0xe3f

goroutine 36 [select]:
google.golang.org/grpc/transport.(*http2Server).keepalive(0xc42021e000)
	/home/user/go/src/google.golang.org/grpc/transport/http2_server.go:951 +0x264
created by google.golang.org/grpc/transport.newHTTP2Server
	/home/user/go/src/google.golang.org/grpc/transport/http2_server.go:259 +0xe64

goroutine 54 [runnable]:
sync.(*Mutex).Unlock(0xc4201f6ab8)
	/usr/local/go/src/sync/mutex.go:175 +0xc8
google.golang.org/grpc/transport.(*controlBuffer).put(0xc4201f6ab0, 0xa6d5e0, 0xc4202496b0)
	/home/user/go/src/google.golang.org/grpc/transport/transport.go:172 +0x1b7
google.golang.org/grpc/transport.(*http2Server).WriteHeader(0xc42021e000, 0xc420250f00, 0x0, 0x0, 0x3)
	/home/user/go/src/google.golang.org/grpc/transport/http2_server.go:741 +0xc26
google.golang.org/grpc/transport.(*http2Server).Write(0xc42021e000, 0xc420250f00, 0xc4201fc740, 0x5, 0x5, 0xc4201fbbe0, 0x16, 0x16, 0xc4201fc746, 0xc4201fc740, ...)
	/home/user/go/src/google.golang.org/grpc/transport/http2_server.go:849 +0x878
google.golang.org/grpc.(*serverStream).SendMsg(0xc42024e640, 0x80d100, 0xc420147700, 0x0, 0x0)
	/home/user/go/src/google.golang.org/grpc/stream.go:665 +0x22d
google.golang.org/grpc/examples/route_guide/routeguide.(*routeGuideRouteChatServer).Send(0xc420204220, 0xc420147700, 0xc4201fc72c, 0x3)
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:472 +0x49
main.(*routeGuideServer).RouteChat(0xc420146460, 0xa76780, 0xc420204220, 0xa74560, 0xc420146460)
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:139 +0x7f
google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler(0x807040, 0xc420146460, 0xa75dc0, 0xc42024e640, 0x0, 0x0)
	/home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xb2
google.golang.org/grpc.(*Server).processStreamingRPC(0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250f00, 0xc420166060, 0xaae5c0, 0x0, 0x0, 0x0)
	/home/user/go/src/google.golang.org/grpc/server.go:1032 +0xa3e
google.golang.org/grpc.(*Server).handleStream(0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250f00, 0x0)
	/home/user/go/src/google.golang.org/grpc/server.go:1126 +0x14c1
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4201ee270, 0xc420001980, 0xa765a0, 0xc42021e000, 0xc420250f00)
	/home/user/go/src/google.golang.org/grpc/server.go:617 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/user/go/src/google.golang.org/grpc/server.go:615 +0xa1
exit status 2
```

And if I run with `-race` argument, the output: 

```
$ go run -race server/server.go 
==================
WARNING: DATA RACE
Read at 0x00c42007ffb0 by goroutine 17:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:315 +0x0
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:133 +0x1ef
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Previous write at 0x00c42007ffb0 by goroutine 16:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:598 +0x0
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x32a
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Goroutine 17 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777

Goroutine 16 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777
==================
==================
WARNING: DATA RACE
Read at 0x00c420238088 by goroutine 17:
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x25e
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Previous write at 0x00c420238088 by goroutine 16:
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x343
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Goroutine 17 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777

Goroutine 16 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777
==================
==================
WARNING: DATA RACE
Read at 0x00c420238088 by goroutine 18:
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x25e
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Previous write at 0x00c420238088 by goroutine 16:
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x343
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Goroutine 18 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777

Goroutine 16 (finished) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777
==================
==================
WARNING: DATA RACE
Read at 0x00c4201eaf98 by goroutine 17:
  runtime.growslice()
      /usr/local/go/src/runtime/slice.go:82 +0x0
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x453
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Previous write at 0x00c4201eaf98 by goroutine 16:
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x2bd
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Goroutine 17 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777

Goroutine 16 (finished) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777
==================
==================
WARNING: DATA RACE
Read at 0x00c4201eaf98 by goroutine 18:
  runtime.growslice()
      /usr/local/go/src/runtime/slice.go:82 +0x0
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x453
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Previous write at 0x00c4201eaf98 by goroutine 16:
  main.(*routeGuideServer).RouteChat()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/server/server.go:136 +0x2bd
  google.golang.org/grpc/examples/route_guide/routeguide._RouteGuide_RouteChat_Handler()
      /home/user/go/src/google.golang.org/grpc/examples/route_guide/routeguide/route_guide.pb.go:458 +0xd5
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/user/go/src/google.golang.org/grpc/server.go:1032 +0x1334
  google.golang.org/grpc.(*Server).handleStream()
      /home/user/go/src/google.golang.org/grpc/server.go:1126 +0x143a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/user/go/src/google.golang.org/grpc/server.go:617 +0xac

Goroutine 18 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777

Goroutine 16 (finished) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/user/go/src/google.golang.org/grpc/server.go:615 +0xb8
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:381 +0x14ca
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/user/go/src/google.golang.org/grpc/transport/http2_server.go:413 +0x676
  google.golang.org/grpc.(*Server).serveStreams()
      /home/user/go/src/google.golang.org/grpc/server.go:613 +0x1d1
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/user/go/src/google.golang.org/grpc/server.go:574 +0x777
==================
```

**Comment by dfawley** [comment]
Indeed, there is no lock on the map or the slices it contains.  :disappointed:

It should be a trivial fix.  I'll take care of it.
