### ISSUE TITLE
Flaky goroutine leak in TestPickFirstOrderOneServerDown

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1806]
```
E0114 22:34:58.565032    4418 pickfirst.go:59] pickfirstBalancer: failed to NewSubConn: grpc: cannot create SubConn with empty address list
--- FAIL: TestPickFirstOrderOneServerDown (11.93s)
	<autogenerated>:10: Leaked goroutine: goroutine 3007 [semacquire]:
		sync.runtime_Semacquire(0xd853fc)
			/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/sema.go:47 +0x30
		sync.(*Mutex).Lock(0xd853f8)
			/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/sync/mutex.go:85 +0xde
		github.com/golang/glog.(*loggingT).output(0xd853e0, 0xc400000001, 0xc42007fbc0, 0xd49417, 0xb, 0xa1, 0x0)
			/home/travis/gopath/src/github.com/golang/glog/glog.go:672 +0x5f
		github.com/golang/glog.(*loggingT).printDepth(0xd853e0, 0x1, 0x2, 0xc4207f4cf8, 0x1, 0x1)
			/home/travis/gopath/src/github.com/golang/glog/glog.go:646 +0x203
		github.com/golang/glog.WarningDepth(0x2, 0xc4207f4cf8, 0x1, 0x1)
			/home/travis/gopath/src/github.com/golang/glog/glog.go:1085 +0x6b
		google.golang.org/grpc/grpclog/glogger.(*glogger).Warningf(0xda19f0, 0xad319e, 0x31, 0xc420263e80, 0x1, 0x1)
			/home/travis/gopath/src/google.golang.org/grpc/grpclog/glogger/glogger.go:57 +0x11f
		google.golang.org/grpc/grpclog.Warningf(0xad319e, 0x31, 0xc420263e80, 0x1, 0x1)
			/home/travis/gopath/src/google.golang.org/grpc/grpclog/grpclog.go:60 +0x89
		google.golang.org/grpc.(*roundRobin).watchAddrUpdates(0xc42027a540, 0x0, 0x0)
			/home/travis/gopath/src/google.golang.org/grpc/balancer.go:161 +0x11c0
		google.golang.org/grpc.(*roundRobin).Start.func1(0xc42027a540)
			/home/travis/gopath/src/google.golang.org/grpc/balancer.go:234 +0x39
		created by google.golang.org/grpc.(*roundRobin).Start
			/home/travis/gopath/src/google.golang.org/grpc/balancer.go:238 +0x27d
E0114 22:35:35.022067    4418 pickfirst.go:59] pickfirstBalancer: failed to NewSubConn: grpc: cannot create SubConn with empty address list
FAIL
FAIL	google.golang.org/grpc	61.599s
```

**Comment by menghanl** [comment]
This is caused by a mutex deadlock in the `glog` logging package. But I could not find why the deadlock happened.

A solution is to not use glog in our tests.
Related: we could try to use `testing.T.Logf` as the logger for each individual test.
