### ISSUE TITLE
flaky test: TestConfigurableWindowSizeWithLargeWindow

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#1864]
`go1.9.0`, 64 bit

Test timeout:
```
panic: test timed out after 5m0s

goroutine 67251 [running]:
testing.startAlarm.func1()
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4201760f0, 0x97274d, 0x29, 0x9826f8, 0x47da01)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4201760f0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4201760f0, 0xc42005bde0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4201660e0, 0xc2c600, 0x5e, 0x5e, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42005bf18, 0xc42005bf70)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:921 +0x111
main.main()
	google.golang.org/grpc/test/_test/_testmain.go:230 +0xdb

goroutine 5 [syscall]:
syscall.Syscall(0x4a, 0xa, 0x0, 0x0, 0x486e82, 0xc420037e78, 0xc420037e80)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Fsync(0xa, 0x982c60, 0xc4204b05a0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/syscall/zsyscall_linux_amd64.go:473 +0x4a
internal/poll.(*FD).Fsync(0xc4204b05a0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_posix.go:56 +0x88
os.(*File).Sync(0xc42000e0b8, 0xc4206e1c20, 0xc4200682e0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/os/file_posix.go:127 +0x4a
github.com/golang/glog.(*syncBuffer).Sync(0xc42015b6b0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/golang/glog/glog.go:811 +0x2f
github.com/golang/glog.(*loggingT).flushAll(0xc308a0)
	/home/travis/gopath/src/github.com/golang/glog/glog.go:902 +0x7d
github.com/golang/glog.(*loggingT).lockAndFlushAll(0xc308a0)
	/home/travis/gopath/src/github.com/golang/glog/glog.go:890 +0x44
github.com/golang/glog.(*loggingT).flushDaemon(0xc308a0)
	/home/travis/gopath/src/github.com/golang/glog/glog.go:883 +0x87
created by github.com/golang/glog.init.0
	/home/travis/gopath/src/github.com/golang/glog/glog.go:410 +0x203

goroutine 67250 [select]:
google.golang.org/grpc.newClientStream.func4(0xc42052a500, 0xc4200d2900, 0xbea2e0, 0xc42042ec30, 0xc420170640)
	/home/travis/gopath/src/google.golang.org/grpc/stream.go:291 +0x112
created by google.golang.org/grpc.newClientStream
	/home/travis/gopath/src/google.golang.org/grpc/stream.go:290 +0xae0

goroutine 67148 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc4201722c0)
	/home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x156
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x197

goroutine 67224 [runnable]:
google.golang.org/grpc/transport.(*quotaPool).get(0xc42042c0a0, 0x4000, 0xbea2e0, 0xc4206062d0, 0xbea220, 0xc420066a80, 0x0, 0x0, 0x4000, 0xc400000000, ...)
	/home/travis/gopath/src/google.golang.org/grpc/transport/control.go:191 +0x27a
google.golang.org/grpc/transport.(*http2Server).Write(0xc4204bf800, 0xc4201a2280, 0xc420284000, 0x5, 0x4000, 0xc420bca000, 0x13333b, 0x134000, 0xc420156086, 0xc420156080, ...)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:889 +0x48d
google.golang.org/grpc.(*serverStream).SendMsg(0xc4201e41e0, 0x8f53c0, 0xc42000e008, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/stream.go:627 +0x22d
google.golang.org/grpc/test/grpc_testing.(*testServiceFullDuplexCallServer).Send(0xc420162130, 0xc42000e008, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/test/grpc_testing/test.pb.go:648 +0x49
google.golang.org/grpc/test.(*testServer).FullDuplexCall(0xc4201660c0, 0xbed060, 0xc420162130, 0xbec340, 0xc4201660c0)
	/home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:326 +0x4b7
google.golang.org/grpc/test/grpc_testing._TestService_FullDuplexCall_Handler(0x8fd600, 0xc4201660c0, 0xbec1c0, 0xc4201e41e0, 0xc4ff28, 0xc420033440)
	/home/travis/gopath/src/google.golang.org/grpc/test/grpc_testing/test.pb.go:634 +0xb2
google.golang.org/grpc.(*Server).processStreamingRPC(0xc420164840, 0xbecca0, 0xc4204bf800, 0xc4201a2280, 0xc42042e480, 0xc269c0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:1052 +0xa45
google.golang.org/grpc.(*Server).handleStream(0xc420164840, 0xbecca0, 0xc4204bf800, 0xc4201a2280, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:1146 +0x14c1
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420018780, 0xc420164840, 0xbecca0, 0xc4204bf800, 0xc4201a2280)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:637 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/src/google.golang.org/grpc/server.go:635 +0xa1

goroutine 67192 [select]:
google.golang.org/grpc/transport.(*recvBufferReader).read(0xc420076870, 0xc420d01ffb, 0x12f340, 0x12f340, 0xc420170738, 0xc4200578c0, 0x7b21ac)
	/home/travis/gopath/src/google.golang.org/grpc/transport/transport.go:132 +0x28b
google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc420076870, 0xc420d01ffb, 0x12f340, 0x12f340, 0x3ffb, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/transport/transport.go:121 +0x67
google.golang.org/grpc/transport.(*transportReader).Read(0xc42042ed20, 0xc420d01ffb, 0x12f340, 0x12f340, 0x3ffb, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/transport/transport.go:408 +0x55
io.ReadAtLeast(0xbe2c20, 0xc42042ed20, 0xc420cfe000, 0x13333b, 0x13333b, 0x13333b, 0xc420432000, 0xc420170640, 0x13333b)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0xbe2c20, 0xc42042ed20, 0xc420cfe000, 0x13333b, 0x13333b, 0x89ee80, 0x1, 0xc420cfe000)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/io/io.go:327 +0x58
google.golang.org/grpc/transport.(*Stream).Read(0xc420170640, 0xc420cfe000, 0x13333b, 0x13333b, 0x13333b, 0x13333b, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/transport/transport.go:392 +0xbf
google.golang.org/grpc.(*parser).recvMsg(0xc4201665a0, 0x400000, 0x0, 0xc420020b40, 0x79c761, 0x3, 0x0, 0xc42002d370)
	/home/travis/gopath/src/google.golang.org/grpc/rpc_util.go:355 +0x11d
google.golang.org/grpc.recv(0xc4201665a0, 0x1531f0e16520, 0xc4ff28, 0xc420170640, 0x0, 0x0, 0x8f53c0, 0xc42000e028, 0x400000, 0x0, ...)
	/home/travis/gopath/src/google.golang.org/grpc/rpc_util.go:445 +0x4d
google.golang.org/grpc.(*clientStream).RecvMsg(0xc4200d2900, 0x8f53c0, 0xc42000e028, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/stream.go:437 +0x135
google.golang.org/grpc/test/grpc_testing.(*testServiceFullDuplexCallClient).Recv(0xc42004d450, 0xc42042ed80, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/test/grpc_testing/test.pb.go:484 +0x62
google.golang.org/grpc/test.testConfigurableWindowSize(0xc4206a81e0, 0x9613c2, 0x9, 0x95cecc, 0x3, 0x0, 0x0, 0x0, 0x9622ce, 0xb, ...)
	/home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:5184 +0x575
google.golang.org/grpc/test.TestConfigurableWindowSizeWithLargeWindow(0xc4206a81e0)
	/home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:5129 +0x12a
testing.tRunner(0xc4206a81e0, 0x9826f8)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:789 +0x2de

goroutine 67237 [select]:
google.golang.org/grpc/transport.(*http2Server).keepalive(0xc4204bf800)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:955 +0x264
created by google.golang.org/grpc/transport.newHTTP2Server
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:264 +0xf0e

goroutine 67146 [IO wait]:
internal/poll.runtime_pollWait(0x1531f0e15d30, 0x72, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42045e298, 0x72, 0xc42060dc00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42045e298, 0xffffffffffffff00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc42045e280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc42045e280, 0xc42019c000, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e068, 0x7d3201, 0x45aaf0, 0xc42060de80)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000e068, 0x9824b0, 0xc420164840, 0xbed300, 0xc42019c000)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/tcpsock.go:247 +0x49
google.golang.org/grpc.(*Server).Serve(0xc420164840, 0xbe96e0, 0xc42000e068, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:503 +0x1ec
created by google.golang.org/grpc/test.(*test).startServer
	/home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:600 +0x439

goroutine 67147 [select]:
google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc42042e510)
	/home/travis/gopath/src/google.golang.org/grpc/resolver_conn_wrapper.go:108 +0x1ac
created by google.golang.org/grpc.(*ccResolverWrapper).start
	/home/travis/gopath/src/google.golang.org/grpc/resolver_conn_wrapper.go:94 +0x3f

goroutine 67236 [runnable]:
golang.org/x/net/http2.(*Framer).endWrite(0xc420576460, 0x0, 0x0)
	/home/travis/gopath/src/golang.org/x/net/http2/frame.go:351 +0x175
golang.org/x/net/http2.(*Framer).WriteDataPadded(0xc420576460, 0x1, 0xc420be5ffb, 0x4000, 0x118005, 0x0, 0x0, 0x0, 0xc42042c0a0, 0x4000)
	/home/travis/gopath/src/golang.org/x/net/http2/frame.go:685 +0x296
golang.org/x/net/http2.(*Framer).WriteData(0xc420576460, 0x1, 0xc420be5ffb, 0x4000, 0x118005, 0x0, 0xc420044c70)
	/home/travis/gopath/src/golang.org/x/net/http2/frame.go:643 +0x7c
google.golang.org/grpc/transport.(*http2Server).itemHandler(0xc4204bf800, 0xbe29e0, 0xc420606270, 0xbe29e0, 0xc420606330)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:1016 +0xd3a
google.golang.org/grpc/transport.(*http2Server).(google.golang.org/grpc/transport.itemHandler)-fm(0xbe29e0, 0xc420606270, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:261 +0x3e
google.golang.org/grpc/transport.loopyWriter(0xbea220, 0xc420066a80, 0xc4206f8510, 0xc420044fb8)
	/home/travis/gopath/src/google.golang.org/grpc/transport/transport.go:763 +0x1b8
google.golang.org/grpc/transport.newHTTP2Server.func2(0xc4204bf800)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:261 +0x5e
created by google.golang.org/grpc/transport.newHTTP2Server
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:260 +0xee9

goroutine 67149 [select]:
google.golang.org/grpc.(*addrConn).transportMonitor(0xc4206d6240)
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:1215 +0x25f
google.golang.org/grpc.(*addrConn).connect.func1(0xc4206d6240)
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:827 +0x1ce
created by google.golang.org/grpc.(*addrConn).connect
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:818 +0xeb

goroutine 67152 [runnable]:
internal/poll.runtime_pollWait(0x1531f0e15f70, 0x72, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42045e498, 0x72, 0xffffffffffffff00, 0xbe5060, 0xbe0650)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42045e498, 0xc420506000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42045e480, 0xc420506000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc42045e480, 0xc420506000, 0x8000, 0x8000, 0xc420504f00, 0xc420045ce0, 0x406bd2)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e0d8, 0xc420506000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc420504a80, 0xc4203dbfee, 0x12, 0x12, 0x3fee, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0xbe1e60, 0xc420504a80, 0xc4203d8000, 0x4000, 0x4000, 0x4000, 0x0, 0x100004000, 0x100004000)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0xbe1e60, 0xc420504a80, 0xc4203d8000, 0x4000, 0x4000, 0x400000000001, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/io/io.go:327 +0x58
golang.org/x/net/http2.(*Framer).ReadFrame(0xc42038e000, 0xc42042eab0, 0xc42042eab0, 0x0, 0x0)
	/home/travis/gopath/src/golang.org/x/net/http2/frame.go:500 +0x15b
google.golang.org/grpc/transport.(*http2Client).reader(0xc420432000)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_client.go:1180 +0xe1
created by google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_client.go:258 +0xc73

goroutine 67153 [select]:
google.golang.org/grpc/transport.loopyWriter(0xbea220, 0xc4201725c0, 0xc42042eb40, 0xc42041afb8)
	/home/travis/gopath/src/google.golang.org/grpc/transport/transport.go:748 +0x3c6
google.golang.org/grpc/transport.newHTTP2Client.func3(0xc420432000)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_client.go:290 +0x5e
created by google.golang.org/grpc/transport.newHTTP2Client
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_client.go:289 +0xdc4

goroutine 67238 [IO wait]:
internal/poll.runtime_pollWait(0x1531f0e15eb0, 0x72, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4206a0018, 0x72, 0xffffffffffffff00, 0xbe5060, 0xbe0650)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4206a0018, 0xc42026c000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4206a0000, 0xc42026c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc4206a0000, 0xc42026c000, 0x8000, 0x8000, 0x405a40, 0xc42045a118, 0xc4206060f0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42019c000, 0xc42026c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc4203ec360, 0xc420576498, 0x9, 0x9, 0xc420066b01, 0x10171012048c900, 0x0)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0xbe1e60, 0xc4203ec360, 0xc420576498, 0x9, 0x9, 0x9, 0x7afaa6, 0xc420606120, 0xc42029d500)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0xbe1e60, 0xc4203ec360, 0xc420576498, 0x9, 0x9, 0xc42029d500, 0x3346, 0x3346)
	/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/io/io.go:327 +0x58
golang.org/x/net/http2.readFrameHeader(0xc420576498, 0x9, 0x9, 0xbe1e60, 0xc4203ec360, 0x0, 0x100000000, 0x100003346, 0x334600000001)
	/home/travis/gopath/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc420576460, 0xc4206f8240, 0xc4206f8240, 0x0, 0x0)
	/home/travis/gopath/src/golang.org/x/net/http2/frame.go:492 +0xa4
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc4204bf800, 0xc4206f8600, 0x982508)
	/home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:396 +0x3a
google.golang.org/grpc.(*Server).serveStreams(0xc420164840, 0xbecca0, 0xc4204bf800)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:633 +0xf2
google.golang.org/grpc.(*Server).handleRawConn.func2()
	/home/travis/gopath/src/google.golang.org/grpc/server.go:590 +0x3c
google.golang.org/grpc.(*Server).handleRawConn.func3(0xc42042c0c0, 0xc420164840, 0x1531f0e165a0, 0xc4204bf800)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:598 +0x27
created by google.golang.org/grpc.(*Server).handleRawConn
	/home/travis/gopath/src/google.golang.org/grpc/server.go:597 +0x656
FAIL	google.golang.org/grpc/test	300.176s
ok  	google.golang.org/grpc/test/bufconn	0.068s
?   	google.golang.org/grpc/test/codec_perf	[no test files]
?   	google.golang.org/grpc/test/grpc_testing	[no test files]
ok  	google.golang.org/grpc/test/leakcheck	8.280s
ok  	google.golang.org/grpc/transport	206.136s
make: *** [test] Error 1
```

**Comment by menghanl** [comment]
This happened on my fork, no in the main repo.

**Comment by menghanl** [comment]
Cannot reproduce with over 10000 runs. Closing.
