### ISSUE TITLE
possible leak on grpc client WithTransportCredentials

### ISSUE THREAD

**Issue by chemidy** [grpc/grpc-go#2072]
### What version of gRPC are you using?
```
  [[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.12.0"
```
### What version of Go are you using (`go version`)?
```
go version go1.10.2 darwin/amd64
```

### What operating system (Linux, Windows, …) and version?

System Version: macOS 10.13.4 (17E202)

### What did you do?

I'm trying to use [uber goleak](https://github.com/uber-go/goleak) to detect leak in my integration tests.

```go
func TestListAddresses(t *testing.T) {
	defer goleak.VerifyNoLeaks(t)

	tlsCreds := credentials.NewTLS(&tls.Config{InsecureSkipVerify: true})
	conn, err := grpc.Dial("MY_URL",
		grpc.WithTransportCredentials(tlsCreds),
	)
	defer conn.Close()

	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	client := pb.ApiClient(conn)

	_, err := client.ListAddresses(ctx, &pb.ListAddresses{})
	if err != nil {
		t.Fatalf("error getting addresses : %v", err)
	}
} 


```

### What did you expect to see?

No errors

### What did you see instead?

```go
goleak: Errors on successful test run: found unexpected goroutines:

 Goroutine 29 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 29 [IO wait]:
internal/poll.runtime_pollWait(0x284cf20, 0x72, 0xc420487858)
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201c6798, 0x72, 0xffffffffffffff00, 0x187a400, 0x1c56638)
	/usr/local/Cellar/go/1.10.2/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201c6798, 0xc420228000, 0x1000, 0x1000)
	/usr/local/Cellar/go/1.10.2/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201c6780, 0xc420228000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.2/libexec/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc4201c6780, 0xc420228000, 0x1000, 0x1000, 0x10358f9, 0xc42046a600, 0x200000003)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e010, 0xc420228000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc4202100c0, 0x28c0000, 0xc42000e010, 0x5, 0xc42000e010, 0xc420487a10)
	/usr/local/Cellar/go/1.10.2/libexec/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc420212000, 0x1828217, 0xc420212120, 0xc42046a600)
	/usr/local/Cellar/go/1.10.2/libexec/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc420212000, 0xc420324000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.2/libexec/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc42009ae40, 0xc4204a4818, 0x9, 0x9, 0xc420212330, 0x1228ec0, 0xc420212330)
	/usr/local/Cellar/go/1.10.2/libexec/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1877780, 0xc42009ae40, 0xc4204a4818, 0x9, 0x9, 0x9, 0x12aca61, 0xc420212000, 0xc420229000)
	/usr/local/Cellar/go/1.10.2/libexec/src/io/io.go:309 +0x86
io.ReadFull(0x1877780, 0xc42009ae40, 0xc4204a4818, 0x9, 0x9, 0x12f32a4, 0x284d2b8, 0xc420212000)
	/usr/local/Cellar/go/1.10.2/libexec/src/io/io.go:327 +0x58
net/http.http2readFrameHeader(0xc4204a4818, 0x9, 0x9, 0x1877780, 0xc42009ae40, 0x0, 0xc400000000, 0x102bf34, 0x1828260)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/http/h2_bundle.go:1517 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4204a47e0, 0xc420441760, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/http/h2_bundle.go:1775 +0xa4
net/http.(*http2clientConnReadLoop).run(0xc420487fb8, 0x18268f0, 0xc42005bfb8)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/http/h2_bundle.go:8028 +0x90
net/http.(*http2ClientConn).readLoop(0xc4204e1880)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/http/h2_bundle.go:7956 +0x68
created by net/http.(*http2Transport).newClientConn
	/usr/local/Cellar/go/1.10.2/libexec/src/net/http/h2_bundle.go:7143 +0x65c
]
```

**Comment by menghanl** [comment]
Do you have another http2 client running in the same process? The leak goroutine stack trace seems to be generated by `net/http.(*http2Transport).newClientConn`, and doesn't include any gRPC functions.

I couldn't run your test locally, there's no clear indication on how server is started. I tried with my local helloworld, where the server is started in another process, and a similar test finished with no error.

One other possible cause is, `conn.Close()` doesn't wait until all goroutines exit, so there might be some goroutine running after it's called. Those goroutines will eventually exit.
I'm not familiar with `goleak` package, but it seems `goleak.VerifyNoLeaks` does [retry](https://github.com/uber-go/goleak/blob/d13b03e061d1517cc2bf84902c76fc134dafc1d9/leaks.go#L60) a few times before returning an error.
