### ISSUE TITLE
Crash in benchmark_test.go

### ISSUE THREAD

**Issue by dsymonds** [grpc/grpc-go#213]
After #212, I get a crash due to what appears to be a malformed test message:

```
$ go test -bench=. > orig.txt
testing: warning: no tests to run
F0606 09:06:51.811831 35263 logger.go:104] %v.StreamingCall(_) = _, %v&{0xc208082320} rpc error: code = 2 desc = "rpc error: code = 13 desc = \"grpc: proto: grpc_testing.SimpleResponse: illegal tag 0 (wire type 0)\""
goroutine 2356 [running]:
github.com/golang/glog.stacks(0xc208878200, 0x0, 0x0, 0x0)
	/Users/dsymonds/go/src/github.com/golang/glog/glog.go:690 +0xbb
github.com/golang/glog.(*loggingT).output(0x66c220, 0xc200000003, 0xc2081a0300)
	/Users/dsymonds/go/src/github.com/golang/glog/glog.go:641 +0x225
github.com/golang/glog.(*loggingT).print(0x66c220, 0x3, 0xc208878090, 0x3, 0x3)
	/Users/dsymonds/go/src/github.com/golang/glog/glog.go:590 +0x164
github.com/golang/glog.Fatal(0xc208878090, 0x3, 0x3)
	/Users/dsymonds/go/src/github.com/golang/glog/glog.go:983 +0x50
google.golang.org/grpc/grpclog.(*glogger).Fatal(0x691aa0, 0xc208878090, 0x3, 0x3)
	/Users/dsymonds/go/src/google.golang.org/grpc/grpclog/logger.go:104 +0x3c
google.golang.org/grpc/grpclog.Fatal(0xc208878090, 0x3, 0x3)
	/Users/dsymonds/go/src/google.golang.org/grpc/grpclog/logger.go:73 +0x50
google.golang.org/grpc/benchmark.DoStreamingRoundTrip(0x798958, 0xc20802a120, 0x798c08, 0xc20828e350, 0x1, 0x1)
	/Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark.go:135 +0x36f
google.golang.org/grpc/benchmark.streamCaller(0x798958, 0xc20802a120, 0x798c08, 0xc20828e350)
	/Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:109 +0x58
google.golang.org/grpc/benchmark.runStream.func1(0xc20859c000, 0x798958, 0xc20802a120, 0x798c08, 0xc20828e350, 0xc20828f3b0, 0xc208280000, 0xc20859aae0)
	/Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:86 +0xc1
created by google.golang.org/grpc/benchmark.runStream
	/Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:93 +0x4be
```

**Comment by dsymonds** [comment]
Woo. I managed to get this to identify a data race:

```
==================
WARNING: DATA RACE
Write by goroutine 80:
  google.golang.org/grpc/transport.(*recvBufferReader).Read()
      /Users/dsymonds/go/src/google.golang.org/grpc/transport/transport.go:149 +0x89f
  google.golang.org/grpc/transport.(*Stream).Read()
      /Users/dsymonds/go/src/google.golang.org/grpc/transport/transport.go:281 +0x94
  io.ReadAtLeast()
      /Users/dsymonds/src/go/src/io/io.go:298 +0x11b
  io.ReadFull()
      /Users/dsymonds/src/go/src/io/io.go:316 +0x79
  encoding/binary.Read()
      /Users/dsymonds/src/go/src/encoding/binary/binary.go:216 +0x1758
  google.golang.org/grpc.(*parser).recvMsg()
      /Users/dsymonds/go/src/google.golang.org/grpc/rpc_util.go:143 +0x136
  google.golang.org/grpc.recv()
      /Users/dsymonds/go/src/google.golang.org/grpc/rpc_util.go:184 +0x55
  google.golang.org/grpc.(*clientStream).RecvMsg()
      /Users/dsymonds/go/src/google.golang.org/grpc/stream.go:163 +0xb8
  google.golang.org/grpc/benchmark/grpc_testing.(*testServiceStreamingCallClient).Recv()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/grpc_testing/test.pb.go:401 +0xb0
  google.golang.org/grpc/benchmark.DoStreamingRoundTrip()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark.go:134 +0x213
  google.golang.org/grpc/benchmark.streamCaller()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:109 +0x65
  google.golang.org/grpc/benchmark.runStream.func1()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:86 +0xce

Previous read by goroutine 79:
  google.golang.org/grpc/transport.(*recvBufferReader).Read()
      /Users/dsymonds/go/src/google.golang.org/grpc/transport/transport.go:136 +0x149
  google.golang.org/grpc/transport.(*Stream).Read()
      /Users/dsymonds/go/src/google.golang.org/grpc/transport/transport.go:281 +0x94
  io.ReadAtLeast()
      /Users/dsymonds/src/go/src/io/io.go:298 +0x11b
  io.ReadFull()
      /Users/dsymonds/src/go/src/io/io.go:316 +0x79
  encoding/binary.Read()
      /Users/dsymonds/src/go/src/encoding/binary/binary.go:216 +0x1758
  google.golang.org/grpc.(*parser).recvMsg()
      /Users/dsymonds/go/src/google.golang.org/grpc/rpc_util.go:143 +0x136
  google.golang.org/grpc.recv()
      /Users/dsymonds/go/src/google.golang.org/grpc/rpc_util.go:184 +0x55
  google.golang.org/grpc.(*clientStream).RecvMsg()
      /Users/dsymonds/go/src/google.golang.org/grpc/stream.go:163 +0xb8
  google.golang.org/grpc/benchmark/grpc_testing.(*testServiceStreamingCallClient).Recv()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/grpc_testing/test.pb.go:401 +0xb0
  google.golang.org/grpc/benchmark.DoStreamingRoundTrip()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark.go:134 +0x213
  google.golang.org/grpc/benchmark.streamCaller()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:109 +0x65
  google.golang.org/grpc/benchmark.runStream.func1()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:86 +0xce

Goroutine 80 (running) created at:
  google.golang.org/grpc/benchmark.runStream()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:93 +0x579
  google.golang.org/grpc/benchmark.BenchmarkClientStreamc8()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:117 +0x3e
  testing.(*B).runN()
      /Users/dsymonds/src/go/src/testing/benchmark.go:124 +0xf2
  testing.(*B).launch()
      /Users/dsymonds/src/go/src/testing/benchmark.go:216 +0x1ba

Goroutine 79 (running) created at:
  google.golang.org/grpc/benchmark.runStream()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:93 +0x579
  google.golang.org/grpc/benchmark.BenchmarkClientStreamc8()
      /Users/dsymonds/go/src/google.golang.org/grpc/benchmark/benchmark_test.go:117 +0x3e
  testing.(*B).runN()
      /Users/dsymonds/src/go/src/testing/benchmark.go:124 +0xf2
  testing.(*B).launch()
      /Users/dsymonds/src/go/src/testing/benchmark.go:216 +0x1ba
==================
```

**Comment by dsymonds** [comment]
It looks like `benchmark_test.go` is calling `Recv` concurrently on a single stream. I thought streams were not safe to be used in that way.

**Comment by dsymonds** [comment]
Yep, making a new stream (over the same client connection) for each goroutine seems to fix the data race.

I'll send a pull request.
