### ISSUE TITLE
accidental panic when ClientStream.CloseAndRecv

### ISSUE THREAD

**Issue by evolsnow** [grpc/grpc-go#2841]
An accidental panic in runtime.errorString, hard to reproduce.

### What version of gRPC are you using?

Version = "1.21.0-dev"

### What version of Go are you using (`go version`)?

go1.9

### What operating system (Linux, Windows, …) and version?

Linux 4.4.0-33.bm.1-amd64  x86_64 GNU/Linux

### What did you do?

benchmark grpc client-streaming

### What did you expect to see?

- 

### What did you see instead?
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x465625]

goroutine 3064555 [running]:
errors.(*errorString).Error(0x0, 0x18ffec0, 0x0)
        /usr/local/go/src/errors/errors.go:19 +0x5
app/vendor/google.golang.org/grpc/status.FromError(0x18ffec0, 0x0, 0xc4200a0060, 0xc434ad2b00)
        app/vendor/google.golang.org/grpc/status/status.go:135 +0x79
app/vendor/google.golang.org/grpc.toRPCErr(0x18ffec0, 0x0, 0xc4200a0050, 0xc45f8df300)
        app/vendor/google.golang.org/grpc/rpc_util.go:764 +0x76
app/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc450228500, 0x10fee00, 0xc461e84e60, 0x0, 0x1072f00, 0xc460cfe660)
        app/vendor/google.golang.org/grpc/stream.go:876 +0x134
app/vendor/google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc450228500, 0x2, 0x2)
        app/vendor/google.golang.org/grpc/stream.go:719 +0x46
app/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc465f8d8c0, 0xc434ad2ed8, 0xc434ad2ec8, 0x8, 0x20)
        app/vendor/google.golang.org/grpc/stream.go:577 +0x7e
app/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc465f8d8c0, 0x10fee00, 0xc461e84e60, 0x10ae140, 0xc46a07de40)
        app/vendor/google.golang.org/grpc/stream.go:718 +0x135
(*appClient).CloseAndRecv(0xc46b048bc0, 0xc43ed75200, 0x2f, 0x10ae140)`
```

According to the stack, it panics in `grpc/status/status.go`
```go
func FromError(err error) (s *Status, ok bool) {
	if err == nil {
		return &Status{s: &spb.Status{Code: int32(codes.OK)}}, true
	}
	if se, ok := err.(interface {
		GRPCStatus() *Status
	}); ok {
		return se.GRPCStatus(), true
	}
	return New(codes.Unknown, err.Error()), false // panic in err.Error()
}
```
The only reason I could imagine is that we do like this (but how was it possible):
```go
var err error
var e *errString  // errors.(*errorString) from standard library
err = e

fmt.Println(err==nil) // false
fmt.Prinln(err.Error()) // panic
```

**Comment by dfawley** [comment]
Sounds like memory corruption or a problem with your installation.  This is essentially impossible, since one cannot create a nil *errorString (the type is unexported and the errors package provides no way to do so).  Closing since there doesn't appear to be anything we can do.
