### ISSUE TITLE
FullDuplexCall panic invalid memory

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#3040]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xadeb4d]
goroutine 49865 [running]:
google.golang.org/grpc/test.(*funcServer).FullDuplexCall(0xc420d78240, 0xd3eba0, 0xc420978270, 0xd3db80, 0xc420d78240)
	/home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:4623 +0x5d
google.golang.org/grpc/test/grpc_testing._TestService_FullDuplexCall_Handler(0xc25460, 0xc420d78240, 0xd3dac0, 0xc4201469c0, 0x107cf80, 0xc420d788a0)
	/home/travis/gopath/src/google.golang.org/grpc/test/grpc_testing/test.pb.go:895 +0xd3
google.golang.org/grpc.(*Server).processStreamingRPC(0xc4204d0000, 0xd3f6e0, 0xc421652000, 0xc4202a0000, 0xc420d782d0, 0x1054a80, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:1199 +0x143d
google.golang.org/grpc.(*Server).handleStream(0xc4204d0000, 0xd3f6e0, 0xc421652000, 0xc4202a0000, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:1279 +0x13f3
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42045e1e0, 0xc4204d0000, 0xd3f6e0, 0xc421652000, 0xc4202a0000)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:710 +0xad
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/src/google.golang.org/grpc/server.go:708 +0xb9
FAIL	google.golang.org/grpc/test	259.998s
```

**Comment by dfawley** [comment]
This is the same as #2981.  (I meant to *search issues* for the subject line here, and not file this yet -- whoops!)
