### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Name resolution failure)

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc-go#3468]
I start to use Grpc framework to achieve some communication between Client/Server but i got this Exception :

Description : I am using .Net Framework 4.7 in my Environment, which it contains client (as Library), Server (as exe) and a caller(as Library) which is used to call the client.

Client Packages : Grpc (1.19.0) / Grpc.Core (1.19.0) / Grpc.Tools (1.19.0) / Goolge.Protobuf (3.7.0) Server Packages : Grpc (1.19.0) / Grpc.Core (1.19.0) / Grpc.Tools (1.19.0) / Goolge.Protobuf (3.7.0) / Goolge.Protobuf.Tools (3.7.0)

As i understand the client is not able to connect to the server for some reason.

thanks for any help.

**Can anybody give me any Idea what is going wrong? why i am not able to connect to Server?**

The Stack :

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Grpc.Core.Internal.AsyncCall2.UnaryCall(TRequest msg) at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method2 method, String host, CallOptions options, TRequest request) at Grpc.Core.Interceptors.InterceptingCallInvoker.b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext2 context, BlockingUnaryCallContinuation2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method2 method, String host, CallOptions options, TRequest request) at GrpcStreaming.GrpcStreamingClient.Init(GrpcStreamingContext request, CallOptions options) at GrpcStreaming.GrpcStreamingClient.Init(GrpcStreamingContext request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) at NameSpaceExample.Init(String str1, String str2)

**Comment by menghanl** [comment]
This is grpc-go repo.
Please try https://github.com/grpc/grpc-dotnet or https://github.com/grpc/grpc instead. Thanks!

**Comment by MhdAna** [comment]
Hi menghanl,
Thank you very much for your Contribution.
But I want to understand why you suggest those two links for me, do you mean that i am using wrong Grpc version. Or you mean that both links can give me a good orientation how to achieve a Grpc communication channel between Client/Server?

**Comment by menghanl** [comment]
This repo is for gRPC in golang. But it seems you are using gRPC C#. Please file you issue in the grpc-dotnet repo instead.

**Comment by MhdAna** [comment]
Thanks very much
