### ISSUE TITLE
Stream setup is hung at pickerWrapper.pick

### ISSUE THREAD

**Issue by arjunsingri** [grpc/grpc-go#3642]
### What did you do?

We have a GRPC client connecting to a GRPC server using a stream in a k8s cluster. Nothing fancy.

### What did you expect to see?
The stream should have been setup and the GRPC server should start streaming data to the client.

### What did you see instead?

It looks like the stream setup is hung at the below function. I was able to get this using pprof.

```
goroutine 135 [select]:
google.golang.org/grpc.(*pickerWrapper).pick(0xc0004fe0c0, 0x130b4c0, 0xc0006000f0, 0x1c9a300, 0x109127a, 0x1f, 0x130b4c0, 0xc0006000f0, 0xc00059cfd0, 0x4933fc, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.27.1/picker_wrapper.go:152 +0x788
google.golang.org/grpc.(*ClientConn).getTransport(0xc000588000, 0x130b4c0, 0xc0006000f0, 0x7fa8a6923400, 0x109127a, 0x1f, 0x110, 0xc000468000, 0xf72160, 0x0, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.27.1/clientconn.go:897 +0x80
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc000468000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:351 +0x18a
google.golang.org/grpc.newClientStream(0x130b4c0, 0xc0006000f0, 0x1c774c0, 0xc000588000, 0x109127a, 0x1f, 0xc000666010, 0x1, 0x1, 0x0, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:284 +0x87c
google.golang.org/grpc.(*ClientConn).NewStream(0xc000588000, 0x130b440, 0xc000126000, 0x1c774c0, 0x109127a, 0x1f, 0xc000666010, 0x1, 0x1, 0xc00059d448, ...)
```

**Comment by menghanl** [comment]
My guess is there's connection problem.

Can you turn on logging and try again?
https://github.com/grpc/grpc-go#how-to-turn-on-logging
