### ISSUE TITLE
When using load test on a server getting [circuit breaker open] panic

### ISSUE THREAD

**Issue by arthurvaverko** [grpc/grpc-go#3660]
I have implemented a simple service to get some info from sql.
When i fire a request to a REST endpoint that in turn should send the gRPC after after few seconds i get the following error log 

```c
ERRO[0251] gRPC [/legacy.Legacy/GetPartnerConfiguration] is in panic, recovering. original panic [circuit breaker open], stack:

goroutine 65053 [running]:
runtime/debug.Stack(0xc0013776f8, 0x1833a00, 0xc0003f1280)
 /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/kaltura/ott-lib-core/grpc/server.tracingServerInterceptor.func1(0xc001377a80, 0xc000d9b320, 0xc001377b80)
 /Users/elibendavid/go/pkg/mod/github.com/kaltura/ott-lib-core@v0.0.0-20200604130940-9e23b637e777/grpc/server/server.go:43 +0x6e
panic(0x1833a00, 0xc0003f1280)
 /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kaltura/ott-service-legacy/api-gen/grpc.legacyService.GetPartnerConfiguration(0x1ab2ec0, 0xc0009067e0, 0xc000906690, 0x1868060, 0x0, 0x1aaefc0)
 /Users/elibendavid/kaltura/ott-go/ott-service-legacy/api-gen/grpc/grpc.go:36 +0xff
github.com/kaltura/ott-service-legacy/api-gen/grpc/proto._Legacy_GetPartnerConfiguration_Handler.func1(0x1ab2ec0, 0xc0009067e0, 0x18ec7e0, 0xc000906690, 0x1927cc0, 0xc00019cfd8, 0x1ab2ec0, 0xc0009067e0)
 /Users/elibendavid/kaltura/ott-go/ott-service-legacy/api-gen/grpc/proto/api.pb.go:791 +0x86
github.com/kaltura/ott-lib-core/grpc/server.tracingServerInterceptor(0x1ab2ec0, 0xc000906660, 0x18ec7e0, 0xc000906690, 0xc000d9b320, 0xc000d9b340, 0x0, 0x0, 0x0, 0x0)
 /Users/elibendavid/go/pkg/mod/github.com/kaltura/ott-lib-core@v0.0.0-20200604130940-9e23b637e777/grpc/server/server.go:71 +0x3a1
github.com/kaltura/ott-service-legacy/api-gen/grpc/proto._Legacy_GetPartnerConfiguration_Handler(0x1868060, 0x2143480, 0x1ab2ec0, 0xc000906660, 0xc0027a1740, 0x1997078, 0x1ab2ec0, 0xc000906660, 0xc000d046f0, 0x3)
 /Users/elibendavid/kaltura/ott-go/ott-service-legacy/api-gen/grpc/proto/api.pb.go:793 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00018e000, 0x1abc100, 0xc000682300, 0xc000f2f100, 0xc000212b70, 0x2104f00, 0x0, 0x0, 0x0)
 /Users/elibendavid/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc00018e000, 0x1abc100, 0xc000682300, 0xc000f2f100, 0x0)
 /Users/elibendavid/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccd
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002f4020, 0xc00018e000, 0x1abc100, 0xc000682300, 0xc000f2f100)
 /Users/elibendavid/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
```

this log is comming from my tracing interceptor that will recover form every panic and wont crash the service instead it willl return an err struct back in the response

thats the code throwing the error

```go
func tracingServerInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {
	logger := log.NewLogger()
	defer func() {
		if r := recover(); r != nil {
			stackTrace := string(debug.Stack())
			logger.Errorf("gRPC [%s] is in panic, recovering. original panic [%v], stack:\n%s", info.FullMethod, r, stackTrace)
			err = errors.New("unexpected error")
		}
	}()

	md, headersExtracted := metadata.FromIncomingContext(ctx)
	requestId := "Could not extract request"
...
...
...
```

**Comment by arthurvaverko** [comment]
sorry seems like the stack trace was incomplete .. 
this panic came from the couchbase driver I was using ...
