### ISSUE TITLE
credentials/tls/certprovider/pemfile:Test/Provider_UpdateFailure_ThenSuccess fails with Go 1.16

### ISSUE THREAD

**Issue by ianlancetaylor** [grpc/grpc-go#4162]
### What version of gRPC are you using?

tip (git revision 504caa93c53934ac0367ba2636aa1c8147372a43)

### What version of Go are you using (`go version`)?

go version devel +fa90aaca7d Thu Jan 7 19:31:03 2021 +0000 linux/amd64

### What operating system (Linux, Windows, …) and version?

GNU/Linux Debian GNU/Linux rodete 20201231.01.08RL

### What did you do?
If possible, provide a recipe for reproducing the error.

```
cd credentials/tls/certprovider/pemfile
go test .
```

### What did you expect to see?

```
ok  	google.golang.org/grpc/credentials/tls/certprovider/pemfile	0.NNNs
```

### What did you see instead?

```
anic: cannot handle unexported field at {*certprovider.KeyMaterial}.Roots.lazyCerts[0].rawSubject:
	"crypto/x509".lazyCert
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported [recovered]
	panic: cannot handle unexported field at {*certprovider.KeyMaterial}.Roots.lazyCerts[0].rawSubject:
	"crypto/x509".lazyCert
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported

goroutine 32 [running]:
testing.tRunner.func1.2(0x778c60, 0xc00068e110)
	/home/iant/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000082780)
	/home/iant/go/src/testing/testing.go:1147 +0x4b6
panic(0x778c60, 0xc00068e110)
	/home/iant/go/src/runtime/panic.go:965 +0x1b9
github.com/google/go-cmp/cmp.validator.apply(0xc00068c0a0, 0x773660, 0xc00005c440, 0x1b7, 0x773660, 0xc00005c440, 0x1b7)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/options.go:241 +0x5a5
github.com/google/go-cmp/cmp.(*state).tryOptions(0xc00068c0a0, 0x866b20, 0x773660, 0x773660, 0xc00005c440, 0x1b7, 0x773660, 0xc00005c440, 0x1b7, 0x40f79b)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:303 +0x132
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00068c0a0, 0x8618c0, 0xc0000a4300)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:258 +0x2f2
github.com/google/go-cmp/cmp.(*state).compareStruct(0xc00068c0a0, 0x866b20, 0x7a5840, 0x7a5840, 0xc00005c440, 0x199, 0x7a5840, 0xc00005c440, 0x199)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:427 +0x685
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00068c0a0, 0x861890, 0xc00070e240)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:286 +0xe38
github.com/google/go-cmp/cmp.(*state).statelessCompare(0xc00068c0a0, 0x861890, 0xc00070e240, 0x7fca1520ef01, 0x7fca1520ef18)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:229 +0x97
github.com/google/go-cmp/cmp.(*state).compareSlice.func2(0x0, 0x0, 0xc00069cac8, 0x45230c)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:493 +0x85
github.com/google/go-cmp/cmp/internal/diff.(*path).connect(0xc00069cbe0, 0x1, 0x1, 0xc00069cd90)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/internal/diff/diff.go:328 +0x79
github.com/google/go-cmp/cmp/internal/diff.Difference(0x1, 0x1, 0xc00069cd90, 0x1, 0x1, 0xc000016310)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/internal/diff/diff.go:306 +0x905
github.com/google/go-cmp/cmp.(*state).compareSlice(0xc00068c0a0, 0x866b20, 0x7711a0, 0x7711a0, 0xc0004183f8, 0x197, 0x7711a0, 0xc0004183f8, 0x197)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:492 +0x734
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00068c0a0, 0x8618c0, 0xc0000a4200)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:288 +0x945
github.com/google/go-cmp/cmp.(*state).compareStruct(0xc00068c0a0, 0x866b20, 0x7b2e60, 0x7b2e60, 0xc0004183f0, 0x199, 0x7b2e60, 0xc0004183f0, 0x199)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:427 +0x685
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00068c0a0, 0x861830, 0xc0006920c0)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:286 +0xe38
github.com/google/go-cmp/cmp.(*state).comparePtr(0xc00068c0a0, 0x866b20, 0x7c69c0, 0x7c69c0, 0xc00005c518, 0x196, 0x7c69c0, 0xc00068a018, 0x196)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:579 +0x333
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00068c0a0, 0x8618c0, 0xc0000a4100)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:292 +0xcbe
github.com/google/go-cmp/cmp.(*state).compareStruct(0xc00068c0a0, 0x866b20, 0x7a6240, 0x7a6240, 0xc00005c500, 0x199, 0x7a6240, 0xc00068a000, 0x199)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:427 +0x685
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00068c0a0, 0x861830, 0xc000692040)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:286 +0xe38
github.com/google/go-cmp/cmp.(*state).comparePtr(0xc00068c0a0, 0x866b20, 0x768960, 0x768960, 0xc00005c500, 0x16, 0x768960, 0xc00068a000, 0x16)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:579 +0x333
github.com/google/go-cmp/cmp.(*state).compareAny(0xc00068c0a0, 0x861500, 0xc000692000)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:292 +0xcbe
github.com/google/go-cmp/cmp.Equal(0x768960, 0xc00005c500, 0x768960, 0xc00068a000, 0xc00068e010, 0x1, 0x1, 0xc000094088)
	/home/iant/gopath/pkg/mod/github.com/google/go-cmp@v0.5.0/cmp/compare.go:94 +0x9d
google.golang.org/grpc/credentials/tls/certprovider/pemfile.s.TestProvider_UpdateFailure_ThenSuccess(0xc000082780)
	/home/iant/gopath/src/github.com/grpc/grpc-go/credentials/tls/certprovider/pemfile/watcher_test.go:406 +0x51b
google.golang.org/grpc/internal/grpctest.RunSubTests.func1(0xc000082780)
	/home/iant/gopath/src/github.com/grpc/grpc-go/internal/grpctest/grpctest.go:103 +0x7c
testing.tRunner(0xc000082780, 0xc000430560)
	/home/iant/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/home/iant/go/src/testing/testing.go:1239 +0x2b3
FAIL	google.golang.org/grpc/credentials/tls/certprovider/pemfile	0.490s
FAIL
```

Go 1.16 has added a new field `lazyCerts []lazyCert` to `crypto/x509.CertPool` (see https://golang.org/cl/229917).  The test uses `cmp.AllowUnexported(x509.CertPool{})`, but that doesn't seem to be enough to skip the unexported field type.  In general the standard library doesn't guarantee that comparing `x509/CertPool` values will return anything reasonable.  I'm not sure what this test is trying to test; would it work to just compare the `Certs` field of `KeyMaterial`?  Is there any reason to compare the `Roots` field?

**Comment by ianlancetaylor** [comment]
Thanks.
