### ISSUE TITLE
Unable to get cpp route_guide to comminucate with go route_guide

### ISSUE THREAD

**Issue by wari** [grpc/grpc-go#417]
Using Arch linux, I've just downloaded grpc (cpp, and go) using git today, and downloaded all the submodules. Compiled everything and installed.

When I ran the go greeter server, the cpp client can connect to the go server, and replied nicely with

    Greeter received: Hello world

I tried to do something more complex, the route_guide example. Go client, cpp server:

```
[wari@nucky client]$ ./client --server_addr 127.0.0.1:50051
2015/10/29 17:05:28 Getting feature for point (409146138, -746188906)
2015/10/29 17:05:28 &{0xc82010a380}.GetFeatures(_) = _, rpc error: code = 12 desc = "": 
```

And vice versa (cpp client, go server):

```
[wari@nucky route_guide]$ ./route_guide_client 
DB parsed, loaded 100 features.
-------------- GetFeature --------------
GetFeature rpc failed.
GetFeature rpc failed.
-------------- ListFeatures --------------
Looking for features between 40, -75 and 42, -73
ListFeatures rpc failed.
-------------- RecordRoute --------------
Visiting point 40.1809, -74.4158
Visiting point 41.6561, -74.6722
Visiting point 40.7101, -74.7743
Visiting point 41.2856, -74.5149
Visiting point 41.0322, -74.7872
Visiting point 40.4701, -74.4782
Visiting point 40.0066, -74.6793
Visiting point 40.0066, -74.6793
Visiting point 40.4701, -74.4782
Visiting point 40.932, -74.6201
RecordRoute rpc failed.
-------------- RouteChat --------------
Sending message First message at 0, 0
Sending message Second message at 0, 1
Sending message Third message at 1, 0
Sending message Fourth message at 0, 0
RouteChat rpc failed.
```
As far as I can see, there's not much difference with the proto file, and for the route_guide, there's no diff in the json db. Although the route_guide in the CPP example behaved a bit differently than go's route_guide, I don't see why it should fail.

Any ideas or is this normal? I doubt so. It could be something horribly wrong with my setup. But this is a fresh install.

**Comment by wari** [comment]
I'm not sure if this is relavant, net/trace reports that this is still connected:

Active Requests

| When	| Elapsed (s) | function |
|------------|----------------|------------|
| 2015/10/29 17:54:06.673896 |	462.982815 |	/routeguide.RouteGuide/RouteChat |
| 2015/10/29 17:53:56.994103 |	472.662693 |	/routeguide.RouteGuide/RecordRoute |
| 2015/10/29 17:53:56.993537 |	472.663315 |	/routeguide.RouteGuide/ListFeatures |
| 2015/10/29 17:53:56.993120 |	472.663784 |	/routeguide.RouteGuide/GetFeature |
| 2015/10/29 17:53:56.992671 |	472.664285 |	/routeguide.RouteGuide/GetFeature |

**Comment by wari** [comment]
When using Java to connect to the grpc-go route_guide server, I got the following error:

```
[wari@nucky examples]$ ./build/install/grpc-examples/bin/route-guide-client
Oct 29, 2015 6:35:04 PM io.grpc.examples.routeguide.RouteGuideClient info
INFO: *** GetFeature: lat=409,146,138 lon=-746,188,906
Oct 29, 2015 6:35:05 PM io.grpc.internal.TransportSet$1 run
INFO: Created transport io.grpc.netty.NettyClientTransport@7085bdee for localhost/127.0.0.1:8980
Oct 29, 2015 6:35:05 PM io.grpc.internal.TransportSet$TransportListener transportReady
INFO: Transport io.grpc.netty.NettyClientTransport@7085bdee for localhost/127.0.0.1:8980 is ready
Oct 29, 2015 6:35:05 PM io.grpc.examples.routeguide.RouteGuideClient getFeature
WARNING: RPC failed
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service routeguide.RouteGuide
        at io.grpc.Status.asRuntimeException(Status.java:430)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:156)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:106)
        at io.grpc.examples.routeguide.RouteGuideGrpc$RouteGuideBlockingStub.getFeature(RouteGuideGrpc.java:169)
        at io.grpc.examples.routeguide.RouteGuideClient.getFeature(RouteGuideClient.java:80)
        at io.grpc.examples.routeguide.RouteGuideClient.main(RouteGuideClient.java:232)

Oct 29, 2015 6:35:05 PM io.grpc.internal.TransportSet$TransportListener transportShutdown
INFO: Transport io.grpc.netty.NettyClientTransport@7085bdee for localhost/127.0.0.1:8980 is being shutdown
Oct 29, 2015 6:35:05 PM io.grpc.internal.TransportSet$TransportListener transportTerminated
INFO: Transport io.grpc.netty.NettyClientTransport@7085bdee for localhost/127.0.0.1:8980 is terminated
Exception in thread "main" io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service routeguide.RouteGuide
        at io.grpc.Status.asRuntimeException(Status.java:430)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:156)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:106)
        at io.grpc.examples.routeguide.RouteGuideGrpc$RouteGuideBlockingStub.getFeature(RouteGuideGrpc.java:169)
        at io.grpc.examples.routeguide.RouteGuideClient.getFeature(RouteGuideClient.java:80)
        at io.grpc.examples.routeguide.RouteGuideClient.main(RouteGuideClient.java:232)
```

But the same program worked when connected to the CPP route_guide server:

```
[wari@nucky examples]$ ./build/install/grpc-examples/bin/route-guide-client
Oct 29, 2015 6:36:42 PM io.grpc.examples.routeguide.RouteGuideClient info
INFO: *** GetFeature: lat=409,146,138 lon=-746,188,906
Oct 29, 2015 6:36:42 PM io.grpc.internal.TransportSet$1 run
INFO: Created transport io.grpc.netty.NettyClientTransport@7085bdee for localhost/127.0.0.1:8980
Oct 29, 2015 6:36:42 PM io.grpc.internal.TransportSet$TransportListener transportReady
INFO: Transport io.grpc.netty.NettyClientTransport@7085bdee for localhost/127.0.0.1:8980 is ready
Oct 29, 2015 6:36:42 PM io.grpc.examples.routeguide.RouteGuideClient info
INFO: Found feature called "BerkshireValleyManagementAreaTrail,Jefferson,NJ,USA" at 40.915, -74.619
Oct 29, 2015 6:36:42 PM io.grpc.examples.routeguide.RouteGuideClient info
INFO: *** GetFeature: lat=0 lon=0
Oct 29, 2015 6:36:42 PM io.grpc.examples.routeguide.RouteGuideClient info
INFO: Found no feature at 0, 0
Oct 29, 2015 6:36:42 PM io.grpc.examples.routeguide.RouteGuideClient info
INFO: *** ListFeatures: lowLat=400,000,000 lowLon=-750,000,000 hiLat=420,000,000 hiLon=-730,000,000
Oct 29, 2015 6:36:42 PM io.grpc.examples.routeguide.RouteGuideClient info
INFO: Result: name: "PatriotsPath,Mendham,NJ07945,USA"
location {
  latitude: 407838351
  longitude: -746143763
}
.......
```

Of course, java server + cpp client works as well. Can't say the same for go and java.

**Comment by iamqizhao** [comment]
This is because the proto used by gRPC-Go has a different package name.
Fixing ....
