### ISSUE TITLE
xds resolver nil pointer panic

### ISSUE THREAD

**Issue by sky91** [grpc/grpc-go#4345]
grpc-go version: v1.37.0

With the code below:
```go
ctx, cancel := context.WithCancel(context.Background())
go func() {
	<-ctx.Done()
	_, _ = grpc.Dial("xds:///foo.com", grpc.WithInsecure())
}()
go func() {
	<-ctx.Done()
	_, _ = grpc.Dial("xds:///bar.com", grpc.WithInsecure())
}()
time.Sleep(time.Second)
cancel()
```
Error output:
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x1bc11a9]

goroutine 50 [running]:
google.golang.org/grpc/xds/internal/resolver.(*xdsResolver).newConfigSelector(0xc0003bc100, 0x0, 0x0, 0xc00011c6c0, 0x1, 0x1, 0x0, 0x1, 0x0)
	C:/Users/sky91/.go/pkg/mod/google.golang.org/grpc@v1.37.0/xds/internal/resolver/serviceconfig.go:259 +0x49
google.golang.org/grpc/xds/internal/resolver.(*xdsResolver).run(0xc0003bc100)
	C:/Users/sky91/.go/pkg/mod/google.golang.org/grpc@v1.37.0/xds/internal/resolver/xds_resolver.go:219 +0x188
created by google.golang.org/grpc/xds/internal/resolver.(*xdsResolverBuilder).Build
	C:/Users/sky91/.go/pkg/mod/google.golang.org/grpc@v1.37.0/xds/internal/resolver/xds_resolver.go:94 +0x5c9
```

Is it a bug?

**Comment by menghanl** [comment]
Can you paste the client logs when the panic happens?
And can you try from master branch? This might be fixed by #4327
