### ISSUE TITLE
flaky test: TestRateLimitedResolve

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#4362]
```
--- FAIL: TestRateLimitedResolve (10.10s)
    dns_resolver_test.go:1531: Timed out waiting for 3 calls after 40ms; got 2
    leakcheck.go:110: Leaked goroutine: goroutine 152 [sleep]:
        time.Sleep(0xf4240)
        	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/time.go:193 +0xcc
        google.golang.org/grpc/internal/resolver/dns.TestRateLimitedResolve.func3(0x40000922a0, 0x385f18, 0x40000da070)
        	/home/runner/work/grpc-go/grpc-go/internal/resolver/dns/dns_resolver_test.go:1517 +0x44
        created by google.golang.org/grpc/internal/resolver/dns.TestRateLimitedResolve
        	/home/runner/work/grpc-go/grpc-go/internal/resolver/dns/dns_resolver_test.go:1510 +0x2dc
FAIL
```

https://github.com/grpc/grpc-go/pull/4356/checks?check_run_id=2422242299

Have only seen this once on the newly added `arm64` tests

**Comment by easwars** [comment]
Another failure:
https://github.com/grpc/grpc-go/runs/2461922311?check_suite_focus=true

**Comment by easwars** [comment]
And another one where the test exceeds the 7m timeout:
https://github.com/grpc/grpc-go/runs/2450829872?check_suite_focus=true

**Comment by easwars** [comment]
One more:
https://github.com/grpc/grpc-go/pull/4364/checks?check_run_id=2461922311
