### ISSUE TITLE
Flaky Test: TestResolve

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-go#4384]
```
=== RUN   TestResolve
panic: test timed out after 10m0s

goroutine 74901 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1701 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001c0900, 0x1373f63, 0xb, 0x1389ee0, 0x1090766)
	/usr/local/go/src/testing/testing.go:1240 +0x2da
testing.runTests.func1(0xc0001c0300)
	/usr/local/go/src/testing/testing.go:1512 +0x78
testing.tRunner(0xc0001c0300, 0xc0003d1d70)
	/usr/local/go/src/testing/testing.go:1194 +0xef
testing.runTests(0xc0000b42a0, 0x15a7c60, 0x9, 0x9, 0xc01c7e2e508a44a8, 0x8bb2dac217, 0x15ae3e0, 0x18)
	/usr/local/go/src/testing/testing.go:1510 +0x2fe
testing.(*M).Run(0xc00011a180, 0x0)
	/usr/local/go/src/testing/testing.go:1418 +0x1eb
google.golang.org/grpc/internal/resolver/dns.TestMain(0xc00011a180)
	/Users/zasweq/workplace/grpc-respository/grpc-go/internal/resolver/dns/dns_resolver_test.go:47 +0x45
main.main()
	_testmain.go:61 +0x165

goroutine 74859 [sleep]:
time.Sleep(0xf4240)
	/usr/local/go/src/runtime/time.go:193 +0xd2
google.golang.org/grpc/internal/resolver/dns.testIPResolver(0xc0001c0900)
	/Users/zasweq/workplace/grpc-respository/grpc-go/internal/resolver/dns/dns_resolver_test.go:1137 +0x4f3
google.golang.org/grpc/internal/resolver/dns.TestResolve(0xc0001c0900)
	/Users/zasweq/workplace/grpc-respository/grpc-go/internal/resolver/dns/dns_resolver_test.go:674 +0x55
testing.tRunner(0xc0001c0900, 0x1389ee0)
	/usr/local/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x2b3
FAIL	google.golang.org/grpc/internal/resolver/dns	600.419s
```

**Comment by zasweq** [comment]
Ran into this again locally.
