### ISSUE TITLE
Flaky test: Test/WithBackoffConfig

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4430]
Seems to be new:

```
--- FAIL: Test (26.55s)
    --- FAIL: Test/WithBackoffConfig (10.05s)
        tlogger.go:99: clientconn.go:252 [core] parsed scheme: "passthrough"  (t=+37.603µs)
        tlogger.go:99: resolver_conn_wrapper.go:96 [core] ccResolverWrapper: sending update to cc: {[{foo:80  <nil> 0 <nil>}] <nil> <nil>}  (t=+78.305µs)
        tlogger.go:99: clientconn.go:708 [core] ClientConn switching balancer to "pick_first"  (t=+113.208µs)
        tlogger.go:99: clientconn.go:723 [core] Channel switches to new LB policy "pick_first"  (t=+131.609µs)
        tlogger.go:99: clientconn.go:1114 [core] Subchannel Connectivity change to CONNECTING  (t=+159.711µs)
        tlogger.go:99: clientconn.go:1251 [core] Subchannel picks a new address "foo:80" to connect  (t=+214.914µs)
        tlogger.go:99: clientconn.go:435 [core] Channel Connectivity change to SHUTDOWN  (t=+225.715µs)
        tlogger.go:99: clientconn.go:1114 [core] Subchannel Connectivity change to SHUTDOWN  (t=+296.52µs)
        tlogger.go:99: clientconn.go:1326 [core] grpc: addrConn.createTransport failed to connect to {foo:80 foo:80 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled". Reconnecting...  (t=+339.522µs)
        grpctest.go:39: Leaked goroutine: goroutine 1973 [syscall]:
            net._C2func_getaddrinfo(0xc0002d6200, 0x0, 0xc0001a4570, 0xc000144008, 0x0, 0x0, 0x0)
            	_cgo_gotypes.go:94 +0x55
            net.cgoLookupIPCNAME.func1(0xc0002d6200, 0x4, 0x4, 0xc0001a4570, 0xc000144008, 0x0, 0xc00033e6a0, 0x5ca872)
            	/opt/hostedtoolcache/go/1.15.11/x64/src/net/cgo_unix.go:161 +0xc5
            net.cgoLookupIPCNAME(0x9e8b14, 0x3, 0x9f3f75, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
            	/opt/hostedtoolcache/go/1.15.11/x64/src/net/cgo_unix.go:161 +0x16b
            net.cgoIPLookup(0xc0001dd020, 0x9e8b14, 0x3, 0x9f3f75, 0x3)
            	/opt/hostedtoolcache/go/1.15.11/x64/src/net/cgo_unix.go:218 +0x67
            created by net.cgoLookupIP
            	/opt/hostedtoolcache/go/1.15.11/x64/src/net/cgo_unix.go:228 +0xc7
        grpctest.go:60: Leak check disabled for future tests
FAIL
FAIL	google.golang.org/grpc	44.333s
```

Run: https://github.com/grpc/grpc-go/pull/4428/checks?check_run_id=2571028486

**Comment by easwars** [comment]
@menghanl : Have you seen this before?

**Comment by menghanl** [comment]
No. I have never seen this.

**Comment by easwars** [comment]
The leaked goroutine here looks very similar to the one in golang/go#22724, which was supposedly fixed in Go1.11, and we hit this issue only in Go1.11. I've tried running this test a million times with the latest Go version and it passes all the time.

**Comment by easwars** [comment]
We have removed Go1.11 tests. So, we should not see this anymore.

**Comment by dfawley** [comment]
Happened with `Test/WithBackoffConfigDefault` on Go 1.17; probably related.

https://github.com/grpc/grpc-go/runs/3957171132
```
--- FAIL: Test (32.52s)
    --- FAIL: Test/WithBackoffConfigDefault (10.01s)
        tlogger.go:116: INFO clientconn.go:1616 [core] original dial target is: "passthrough:///foo:80"  (t=+92.605µs)
        tlogger.go:116: INFO clientconn.go:1623 [core] parsed dial target is: {Scheme:passthrough Authority: Endpoint:foo:80 URL:{Scheme:passthrough Opaque: User: Host: Path:/foo:80 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+221.312µs)
        tlogger.go:116: INFO clientconn.go:259 [core] Channel authority set to "foo:80"  (t=+295.216µs)
        tlogger.go:116: INFO resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{foo:80  <nil> <nil> 0 <nil>}] <nil> <nil>}  (t=+391.621µs)
        tlogger.go:116: INFO clientconn.go:705 [core] ClientConn switching balancer to "pick_first"  (t=+461.925µs)
        tlogger.go:116: INFO clientconn.go:725 [core] Channel switches to new LB policy "pick_first"  (t=+518.028µs)
        tlogger.go:116: INFO clientconn.go:413 [core] Channel Connectivity change to SHUTDOWN  (t=+725.639µs)
        tlogger.go:116: INFO clientconn.go:1136 [core] Subchannel Connectivity change to CONNECTING  (t=+802.343µs)
        tlogger.go:116: INFO clientconn.go:1247 [core] Subchannel picks a new address "foo:80" to connect  (t=+905.048µs)
        tlogger.go:116: INFO clientconn.go:1136 [core] Subchannel Connectivity change to SHUTDOWN  (t=+1.062757ms)
        tlogger.go:116: WARNING clientconn.go:1315 [core] grpc: addrConn.createTransport failed to connect to {foo:80 foo:80 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"  (t=+2.120113ms)
        grpctest.go:39: Leaked goroutine: goroutine 2564 [syscall]:
            net._C2func_getaddrinfo(0xc00028200c, 0x0, 0xc0001dc150, 0xc000198000)
            	_cgo_gotypes.go:91 +0x8b
            net.cgoLookupIPCNAME.func1({0xc00028200c, 0x4, 0xbc1711}, 0x4776f5, 0x1046ac0)
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:163 +0xb2
            net.cgoLookupIPCNAME({0xbb5dbb, 0x3}, {0xbc1711, 0x1})
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:163 +0x26e
            net.cgoIPLookup(0x1046ad0, {0xbb5dbb, 0x3}, {0xbc1711, 0x3})
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:220 +0x67
            created by net.cgoLookupIP
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:230 +0x1ba
        grpctest.go:60: Leak check disabled for future tests
    tlogger.go:116: WARNING clientconn.go:1315 [core] grpc: addrConn.createTransport failed to connect to {foo:80 foo:80 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"  (t=+2.521733ms)
    tlogger.go:116: WARNING clientconn.go:1315 [core] grpc: addrConn.createTransport failed to connect to {Non-Existent.Server:80 Non-Existent.Server:80 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"  (t=+9.365294ms)
    tlogger.go:116: WARNING clientconn.go:1315 [core] grpc: addrConn.createTransport failed to connect to {Non-Existent.Server:80 x.test.example.com <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"  (t=+2.707043ms)
FAIL
FAIL	google.golang.org/grpc	51.205s
```

**Comment by menghanl** [comment]
Happened again, in another test case

```
    --- FAIL: Test/ConnectParamsWithMinConnectTimeout (10.06s)
        tlogger.go:116: INFO clientconn.go:1616 [core] original dial target is: "passthrough:///foo:80"  (t=+11.9µs)
        tlogger.go:116: INFO clientconn.go:1623 [core] parsed dial target is: {Scheme:passthrough Authority: Endpoint:foo:80 URL:{Scheme:passthrough Opaque: User: Host: Path:/foo:80 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+44.5µs)
        tlogger.go:116: INFO clientconn.go:259 [core] Channel authority set to "foo:80"  (t=+71.8µs)
        tlogger.go:116: INFO resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{foo:80  <nil> <nil> 0 <nil>}] <nil> <nil>}  (t=+89.1µs)
        tlogger.go:116: INFO clientconn.go:705 [core] ClientConn switching balancer to "pick_first"  (t=+101.901µs)
        tlogger.go:116: INFO clientconn.go:725 [core] Channel switches to new LB policy "pick_first"  (t=+111.501µs)
        tlogger.go:116: INFO clientconn.go:413 [core] Channel Connectivity change to SHUTDOWN  (t=+134.101µs)
        tlogger.go:116: INFO clientconn.go:1136 [core] Subchannel Connectivity change to CONNECTING  (t=+147.001µs)
        tlogger.go:116: INFO clientconn.go:1247 [core] Subchannel picks a new address "foo:80" to connect  (t=+190.701µs)
        tlogger.go:116: INFO clientconn.go:1136 [core] Subchannel Connectivity change to SHUTDOWN  (t=+13.584181ms)
        tlogger.go:116: WARNING clientconn.go:1315 [core] grpc: addrConn.createTransport failed to connect to {foo:80 foo:80 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"  (t=+14.292485ms)
        grpctest.go:39: Leaked goroutine: goroutine 435 [syscall]:
            net._C2func_getaddrinfo(0xc0002da368, 0x0, 0xc0001e4930, 0xc0000100b0)
            	_cgo_gotypes.go:91 +0x56
            net.cgoLookupIPCNAME.func1({0xc0002da368, 0xc000043e28, 0x180}, 0x937176, 0xc000043e50)
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:163 +0x9f
            net.cgoLookupIPCNAME({0x92b960, 0x3}, {0x937176, 0x0})
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:163 +0x16d
            net.cgoIPLookup(0xd3d690, {0x92b960, 0xc0002da361}, {0x937176, 0xc0001c6000})
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:220 +0x3b
            created by net.cgoLookupIP
            	/opt/hostedtoolcache/go/1.17.2/x64/src/net/cgo_unix.go:230 +0x125
        grpctest.go:60: Leak check disabled for future tests
```

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/runs/4159123792?check_suite_focus=true

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/runs/4884740585?check_suite_focus=true

**Comment by easwars** [comment]
I can't make this fail on forge even once in 10k runs. Closing since we aren't seeing this frequently enough.

**Comment by dfawley** [comment]
https://github.com/grpc/grpc-go/runs/5744477899?check_suite_focus=true
