### ISSUE TITLE
Flaky test: Test/ConnectParamsWithMinConnectTimeout

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4527]
See: https://github.com/grpc/grpc-go/pull/4507/checks?check_run_id=2776598792

```
--- FAIL: Test (24.91s)
    --- FAIL: Test/ConnectParamsWithMinConnectTimeout (10.04s)
        tlogger.go:99: clientconn.go:252 [core] parsed scheme: "passthrough"  (t=+29.9µs)
        tlogger.go:99: resolver_conn_wrapper.go:96 [core] ccResolverWrapper: sending update to cc: {[{foo:80  <nil> 0 <nil>}] <nil> <nil>}  (t=+57µs)
        tlogger.go:99: clientconn.go:708 [core] ClientConn switching balancer to "pick_first"  (t=+75.1µs)
        tlogger.go:99: clientconn.go:723 [core] Channel switches to new LB policy "pick_first"  (t=+87.2µs)
        tlogger.go:99: clientconn.go:1114 [core] Subchannel Connectivity change to CONNECTING  (t=+105.8µs)
        tlogger.go:99: clientconn.go:435 [core] Channel Connectivity change to SHUTDOWN  (t=+118.601µs)
        tlogger.go:99: clientconn.go:1251 [core] Subchannel picks a new address "foo:80" to connect  (t=+130.301µs)
        tlogger.go:99: clientconn.go:1114 [core] Subchannel Connectivity change to SHUTDOWN  (t=+1.398511ms)
        tlogger.go:99: clientconn.go:1326 [core] grpc: addrConn.createTransport failed to connect to {foo:80 foo:80 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled". Reconnecting...  (t=+1.971616ms)
        grpctest.go:39: Leaked goroutine: goroutine 388 [syscall]:
            net._C2func_getaddrinfo(0xc0002f423c, 0x0, 0xc000278480, 0xc00000e088, 0x0, 0x0, 0x0)
            	_cgo_gotypes.go:91 +0x55
            net.cgoLookupIPCNAME.func1(0xc0002f423c, 0x0, 0xc000278480, 0xc00000e088, 0x4, 0x4, 0xc000046f30)
            	/opt/hostedtoolcache/go/1.11.13/x64/src/net/cgo_unix.go:149 +0x131
            net.cgoLookupIPCNAME(0x9df50f, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
            	/opt/hostedtoolcache/go/1.11.13/x64/src/net/cgo_unix.go:149 +0x153
            net.cgoIPLookup(0xc0001f64e0, 0x9df50f, 0x3)
            	/opt/hostedtoolcache/go/1.11.13/x64/src/net/cgo_unix.go:201 +0x4d
            created by net.cgoLookupIP
            	/opt/hostedtoolcache/go/1.11.13/x64/src/net/cgo_unix.go:211 +0xad
        grpctest.go:60: Leak check disabled for future tests
FAIL
FAIL	google.golang.org/grpc	39.556s
```

**Comment by easwars** [comment]
The leaked goroutine here looks very similar to the one in https://github.com/golang/go/issues/22724, which was supposedly fixed in Go1.11, and we hit this issue only in Go1.11. I've tried running this test a million times with the latest Go version and it passes all the time.

**Comment by easwars** [comment]
We have removed support for Go1.11 tests, so we should not see this anymore.
