### ISSUE TITLE
Flaky test: TestDropRequest

### ISSUE THREAD

**Issue by charlesxsh** [grpc/grpc-go#4660]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
commit 9280052d36656451dd7568a18a836c2a74edaf6c

### What version of Go are you using (`go version`)?
go 1.16

### What operating system (Linux, Windows, …) and version?
linux

### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
No panic

### What did you see instead?
panic at test `TestDropRequest` of file `balancer/grpclb/grpclb_test.go`
```
panic: interface conversion: net.Addr is nil, not *net.TCPAddr [recovered]
	panic: interface conversion: net.Addr is nil, not *net.TCPAddr

goroutine 6 [running]:
testing.tRunner.func1.2(0x8f98a0, 0xc0005142a0)
	/usr/local/go/src/testing/testing.go:1143 +0x335
testing.tRunner.func1(0xc0002bcc80)
	/usr/local/go/src/testing/testing.go:1146 +0x4c2
panic(0x8f98a0, 0xc0005142a0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
google.golang.org/grpc/balancer/grpclb.TestDropRequest(0xc0002bcc80)
	/fuzz/target/balancer/grpclb/grpclb_test.go:831 +0x23dc
testing.tRunner(0xc0002bcc80, 0x9ad220)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b5
FAIL	google.golang.org/grpc/balancer/grpclb	11.014s
FAIL
```

Reason

```
...
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
...
		var p peer.Peer
		if _, err := testC.EmptyCall(ctx, &testpb.Empty{}, grpc.WaitForReady(true), grpc.Peer(&p)); err != nil {   
			t.Errorf("%v.EmptyCall(_, _) = _, %v, want _, <nil>", testC, err)  <----- line 829
		}
		if want := tss.bePorts[1]; p.Addr.(*net.TCPAddr).Port != want {
			t.Errorf("got peer: %v, want peer port: %v", p.Addr, want)
		}
 ...
// if ctx timeout, rest of calls with  this context will have error DeadlineExceeded
 grpclb_test.go:829: &{0xc0002c0a00}.EmptyCall(_, _) = _, rpc error: code = DeadlineExceeded desc = context deadline exceeded, want _, <nil>
```

**Comment by dfawley** [comment]
#5022
