### ISSUE TITLE
Stream.RecvMsg blocked indefinitely after Stream.SendMsg returned io.EOF

### ISSUE THREAD

**Issue by jgraettinger** [grpc/grpc-go#4691]
### What version of gRPC are you using?

1.38

### What version of Go are you using (`go version`)?

1.14.2 (yes, this is old, but I don't believe it's causal here).

### What operating system (Linux, Windows, …) and version?

Ubuntu 18.04

### What did you do?

We have a chunk of code as follows:

```Go
func (a *Appender) sendMsg(r *pb.AppendRequest) (err error) {
	if err = a.stream.SendMsg(r); err == io.EOF {
		// EOF indicates that a server-side error has occurred, but it must
		// still be read via RecvMsg. See SendMsg docs.
		err = a.stream.RecvMsg(&a.Response)
	}
	return
}
```

In a recent CI run, we observed that the tests hung in the call into RecvMsg within this block, which is only reached immediately after SendMsg() returns an io.EOF.

Per the SendMsg docs, on reading io.EOF the caller may immediately call RecvMsg to receive a descriptive error of the stream break. This call should not block. In our case, it did:

```
goroutine 1689 [select, 9 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc0002607e0)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/transport.go:322 +0x15d
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/transport.go:337
google.golang.org/grpc.(*csAttempt).recvMsg(0xc000144e00, 0x1a436a0, 0xc000563318, 0x0, 0x4b751f, 0xc000ff5bbc)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/stream.go:943 +0xe6d
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc000144e00, 0x1e84420, 0xc0000bd590)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/stream.go:808 +0x62
google.golang.org/grpc.(*clientStream).withRetry(0xc000ff5b00, 0xc000fe95a8, 0xc000fe9578, 0xc000ff5bb0, 0xc000173df0)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/stream.go:666 +0xe2
google.golang.org/grpc.(*clientStream).RecvMsg(0xc000ff5b00, 0x1a436a0, 0xc000563318, 0x1e82c40, 0xc00009a050)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/stream.go:807 +0x168
go.gazette.dev/core/broker/client.(*Appender).sendMsg(0xc0005632c0, 0xc000141bc0, 0x0, 0xc00017c280)
	/gazette/broker/client/appender.go:148 +0x169
```

I'm noting from this stack trace that `recvMsg` is calling into `waitOnHeader` because the server didn't (and will never) send opening stream headers. `waitOnHeader` in turn does a blocking select on `headerChan` and the stream's context.

_It smells like there's a bug here_, but I don't know this code well and can't say for sure.
 * If the transport breaks prior to headers being read, is `headerChan` ever closed ?
 * Is this stream context wrapped from the user's passed-in Context, such that its cancelled on a transport break ? If so, when does that cancellation happen (should it be prior to `waitOnHeader` returning?)

### What did you expect to see?

RecvMsg returns immediately with a descriptive error of the stream break, after SendMsg returns an io.EOF.

### What did you see instead?

RecvMsg blocks indefinitely.

**Comment by dfawley** [comment]
> I'm noting from this stack trace that recvMsg is calling into waitOnHeader because the server didn't (and will never) send opening stream headers

This is fine.  If the stream dies before that happens, `waitOnHeader` should still unblock, as `headerChan` is closed in that case, too:

https://github.com/grpc/grpc-go/blob/8ab16ef276a33df4cdb106446eeff40ff56a6928/internal/transport/http2_client.go#L828

This seems like it might be happening due to a race somewhere.  Do you have a way to reproduce this that we can run so we can narrow it down?

**Comment by jgraettinger** [comment]
Thanks! I'm having a devil of a time getting a repro but will keep trying.

Picking through the stack trace I do have, one thing of note is that the remote server side of the RPC -- which is the same process, this being a test -- believes the connection is fine, and is sitting in a read call:

<details><summary>stack trace</summary>
<p>

```
goroutine 1753 [select, 9 minutes]:
google.golang.org/grpc/internal/transport.(*recvBufferReader).read(0xc000825900, 0xc00046b2b0, 0x5, 0x5, 0xc0007048a0, 0x484b3c, 0x4b751f)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/transport.go:177 +0x167
google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0xc000825900, 0xc00046b2b0, 0x5, 0x5, 0xc00075ae18, 0xcc01b0, 0xc0007048a0)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/transport.go:171 +0x52e
google.golang.org/grpc/internal/transport.(*transportReader).Read(0xc00070e870, 0xc00046b2b0, 0x5, 0x5, 0xc00075ae48, 0xcd72a9, 0xc0005fb980)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/transport.go:483 +0x73
io.ReadAtLeast(0x1e84680, 0xc00070e870, 0xc00046b2b0, 0x5, 0x5, 0x5, 0xc00075af38, 0x42616c, 0x17e3060)
	/usr/local/go/src/io/io.go:310 +0x99
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
google.golang.org/grpc/internal/transport.(*Stream).Read(0xc000ff5c20, 0xc00046b2b0, 0x5, 0x5, 0x1abb274, 0x6, 0xc000290a01)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/internal/transport/transport.go:467 +0x186
google.golang.org/grpc.(*parser).recvMsg(0xc00046b2a0, 0x400000, 0x0, 0xc0003d6a20, 0xc0003d6960, 0x3, 0x3, 0x1e92080)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/rpc_util.go:558 +0x87
google.golang.org/grpc.recvAndDecompress(0xc00046b2a0, 0xc000ff5c20, 0x0, 0x0, 0x400000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/rpc_util.go:689 +0x5e
google.golang.org/grpc.recv(0xc00046b2a0, 0x7f76d86ef2c0, 0x3493228, 0xc000ff5c20, 0x0, 0x0, 0x1a43540, 0xc0000bea80, 0x400000, 0x0, ...)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/rpc_util.go:757 +0xac
google.golang.org/grpc.(*serverStream).RecvMsg(0xc0004fe6c0, 0x1a43540, 0xc0000bea80, 0x0, 0x0)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/stream.go:1545 +0x2b1
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).RecvMsg(0xc00046b2e0, 0x1a43540, 0xc0000bea80, 0x0, 0x0)
	/gazette/.build/go-path/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:164 +0x69
go.gazette.dev/core/broker.proxyAppend(0x7f76d88aba68, 0xc000290660, 0xc0007d2778, 0xc0006f8339, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gazette/broker/append_api.go:96 +0x3b1
go.gazette.dev/core/broker.(*Service).Append(0xc0006dc420, 0x1eb5a80, 0xc000290660, 0x1eaf8a0, 0xc0006dc420)
	/gazette/broker/append_api.go:50 +0xb56
go.gazette.dev/core/broker/protocol._Journal_Append_Handler(0x19fcbe0, 0xc0006dc420, 0x1eaf600, 0xc00046b2e0, 0x18, 0xc000173f90)
	/gazette/broker/protocol/protocol.pb.go:3113 +0xce
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0x19fcbe0, 0xc0006dc420, 0x1eafa80, 0xc0004fe6c0, 0xc00046b2c0, 0x1af8180, 0x1ea6980, 0xc000332930)
	/gazette/.build/go-path/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0x1a8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00039c8c0, 0x1eb70a0, 0xc0005fb980, 0xc000ff5c20, 0xc000700db0, 0x2a7bd80, 0x0, 0x0, 0x0)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1540 +0xb78
google.golang.org/grpc.(*Server).handleStream(0xc00039c8c0, 0x1eb70a0, 0xc0005fb980, 0xc000ff5c20, 0x0)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1613 +0x1302
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002af880, 0xc00039c8c0, 0x1eb70a0, 0xc0005fb980, 0xc000ff5c20)
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0xd9
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/gazette/.build/go-path/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x342
```
</p>
</details>

I should also note that tests were already running with `-race`, so if there _was_ a data race the detector didn't catch it.

It's as if SendMsg somehow returned io.EOF when the underlying transport actually _hasn't_ failed 😕

**Comment by dfawley** [comment]
> I should also note that tests were already running with -race, so if there was a data race the detector didn't catch it.

There are plenty of races that will lead to problems the Go race detector can't catch.

> It's as if SendMsg somehow returned io.EOF when the underlying transport actually hasn't failed confused

Why do you believe the transport failed in your test?  That would be unexpected in a same-process test, unless you are intentionally triggering it.

> because the server didn't (and will never) send opening stream headers

I'm curious: why did you say this?  Is it part of your test case to have the server not respond to the RPC?

**Comment by jgraettinger** [comment]
> There are plenty of races that will lead to problems the Go race detector can't catch.

Totally. I'm just noting that it was running.

> Why do you believe the transport failed in your test? That would be unexpected in a same-process test, unless you are intentionally triggering it.

I don't know of another reason why SendMsg would return io.EOF. My understanding is that client-side errors are returned directly from SendMsg, and peer errors become io.EOF.

> I'm curious: why did you say this? Is it part of your test case to have the server not respond to the RPC?

The server is awaiting a message from the client. The client had attempted to send one via SendMsg, but that call returned `io.EOF` and no message was sent. The client next called `RecvMsg` to read the peer error, which blocks indefinitely, so the underlying connection isn't torn down.

_I continue to be unable to reproduce this. Unless my description of the scenario is tickling an idea for investigation, probably this should be closed. Thanks!_

**Comment by dfawley** [comment]
> I don't know of another reason why SendMsg would return io.EOF. My understanding is that client-side errors are returned directly from SendMsg, and peer errors become io.EOF.

`io.EOF` is returned whenever the stream is closed, which could also happen if the server ends the stream, but it looks like you were in the middle of an interceptor (from the second stack trace) so that seems unlikely.  If you have INFO level logging on, you can see the state of the connections in the `ClientConn` as they change.

> I continue to be unable to reproduce this. Unless my description of the scenario is tickling an idea for investigation, probably this should be closed. Thanks!

Was this just a single occurrence or did you see it multiple times before creating this issue?  I assume you don't have the INFO logs from gRPC when this happened?

**Comment by jgraettinger** [comment]
> Was this just a single occurrence or did you see it multiple times before creating this issue? I assume you don't have the INFO logs from gRPC when this happened?

It was a single occurrence of that specific trace, though we'd seen flakes we were unable to pin down before then. I've not seen a recent re-occurrence, on upgraded versions of Go and go-grpc. Closing; I'll report if it happens again and I have more details.

**Comment by jhhurwitz** [comment]
I am also seeing Stream.RecvMsg blocked regularly for v1.29.1, happy to help debug here.

The stuck goroutine looks like this:

```1 @ 0x43a3c5 0x44a34f 0x87ca15 0x8f5045 0x8f5030 0x8fa0c6 0x8f2d9c 0x8f3d25 0x97d842 0x9908ad 0x997264 0x976fe2 0x9916fd 0x9916d4 0x9916d3 0x991618 0x46fb81
#	0x87ca14	google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader+0xd4	external/org_golang_google_grpc/internal/transport/transport.go:318
#	0x8f5044	google.golang.org/grpc/internal/transport.(*Stream).RecvCompress+0x724	external/org_golang_google_grpc/internal/transport/transport.go:333
#	0x8f502f	google.golang.org/grpc.(*csAttempt).recvMsg+0x70f			external/org_golang_google_grpc/stream.go:870
#	0x8fa0c5	google.golang.org/grpc.(*clientStream).RecvMsg.func1+0x45		external/org_golang_google_grpc/stream.go:735
#	0x8f2d9b	google.golang.org/grpc.(*clientStream).withRetry+0x9b			external/org_golang_google_grpc/stream.go:593
#	0x8f3d24	google.golang.org/grpc.(*clientStream).RecvMsg+0x104			external/org_golang_google_grpc/stream.go:734
...
```

**Comment by dfawley** [comment]
v1.29 is sufficiently old at this point.  Can you reproduce on master@HEAD or the latest release (1.43)?

**Comment by jhhurwitz** [comment]
Sorry for the delay, I was able to reproduce the issue on 1.43

```
2 @ 0x43a705 0x44a68f 0x892735 0x91617e 0x91616a 0x91dae6 0x913c1c 0x914d65 0x9a3382 0x9b63ad 0x9bcd64 0x99cb22 0x9b71fd 0x9b71d4 0x9b71d3 0x9b7118 0x46fec1
#	0x892734	google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader+0xd4	external/org_golang_google_grpc/internal/transport/transport.go:323
#	0x91617d	google.golang.org/grpc/internal/transport.(*Stream).RecvCompress+0x7fd	external/org_golang_google_grpc/internal/transport/transport.go:338
#	0x916169	google.golang.org/grpc.(*csAttempt).recvMsg+0x7e9			external/org_golang_google_grpc/stream.go:961
#	0x91dae5	google.golang.org/grpc.(*clientStream).RecvMsg.func1+0x45		external/org_golang_google_grpc/stream.go:826
#	0x913c1b	google.golang.org/grpc.(*clientStream).withRetry+0x9b			external/org_golang_google_grpc/stream.go:684
#	0x914d64	google.golang.org/grpc.(*clientStream).RecvMsg+0x104			external/org_golang_google_grpc/stream.go:825
```

**Comment by kraney** [comment]
From my observations on this, what I believe is happening is the following
* gRPC opens a TCP connection - but actually the connection is to a proxy (Envoy.) So the TCP 3-way handshake completes successfully
* The envoy proxy then attempts to open a connection to the other end, but that fails
* The proxy then sends a TCP RST on the connection from gRPC

So effectively from gRPC's point of view, it successfully sets up a connection and probably can write to that just fine. But then it tries to read headers from a response that never comes. Instead it gets a TCP reset before every receiving a single byte of data.

This seems to leave it in a state where it's waiting for data forever, and never notices that the TCP socket is actually already dead.

If so, it should be possible to reproduce by connecting the gRPC client, not to a real gRPC server, but to just a simple server using netcat, and then once it connects, kill netcat. That should be the same sequence where it is able to connect, but never read any data.

**Comment by menghanl** [comment]
Wouldn't a TCP RST cause `net.Conn` to return connection errors (like "connection reset by peer")?
And even if the client didn't notice the broken connection, `keepalive` would break later, unless the other end responded with ping acks?

Can you turn on logs: https://github.com/grpc/grpc-go#how-to-turn-on-logging
And also set `GODEBUG=http2debug=2` to see http level logs (this should show pings and acks)

**Comment by jhhurwitz** [comment]
I will try and repro with the debug logs in the near future. Thanks for the feedback
