### ISSUE TITLE
Flaky test: Test/ConfigurableWindowSizeWithLargeWindow

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4721]
https://github.com/grpc/grpc-go/pull/4718/checks?check_run_id=3467784224

```
--- FAIL: Test (261.36s)
    --- FAIL: Test/ConfigurableWindowSizeWithLargeWindow (15.10s)
        end2end_test.go:5707: Running test in tcp-clear-v1-balancer environment...
        tlogger.go:101: clientconn.go:172 [core] Channel Created  (t=+2.772531ms)
        tlogger.go:101: clientconn.go:251 [core] parsed scheme: "passthrough"  (t=+2.944733ms)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:41361  <nil> 0 <nil>}] <nil> <nil>}  (t=+3.213336ms)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:41361 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+3.456939ms)
        tlogger.go:101: clientconn.go:727 [core] ClientConn switching balancer to "pick_first"  (t=+4.042046ms)
        tlogger.go:101: clientconn.go:747 [core] Channel switches to new LB policy "pick_first"  (t=+4.228448ms)
        tlogger.go:101: clientconn.go:788 [core] Subchannel Created  (t=+4.489751ms)
        tlogger.go:101: clientconn.go:788 [core] Subchannel(id:649) created  (t=+4.689753ms)
        tlogger.go:101: picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+5.104057ms)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to CONNECTING  (t=+5.698664ms)
        tlogger.go:101: clientconn.go:1252 [core] Subchannel picks a new address "localhost:41361" to connect  (t=+6.023768ms)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to CONNECTING  (t=+8.256693ms)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to READY  (t=+9.993012ms)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to READY  (t=+10.128314ms)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to SHUTDOWN  (t=+307.016234ms)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to SHUTDOWN  (t=+307.59244ms)
        tlogger.go:101: clientconn.go:1478 [core] Subchannel Deleted  (t=+307.837243ms)
        tlogger.go:101: clientconn.go:1478 [core] Subchanel(id:649) deleted  (t=+307.933744ms)
        tlogger.go:101: clientconn.go:1097 [core] Channel Deleted  (t=+308.075045ms)
        end2end_test.go:5707: Running test in tcp-tls-v1-balancer environment...
        tlogger.go:101: clientconn.go:172 [core] Channel Created  (t=+314.77552ms)
        tlogger.go:101: clientconn.go:251 [core] parsed scheme: "passthrough"  (t=+315.113824ms)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:46737  <nil> 0 <nil>}] <nil> <nil>}  (t=+315.497428ms)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:46737 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+315.767331ms)
        tlogger.go:101: clientconn.go:727 [core] ClientConn switching balancer to "pick_first"  (t=+315.939333ms)
        tlogger.go:101: clientconn.go:747 [core] Channel switches to new LB policy "pick_first"  (t=+316.056335ms)
        tlogger.go:101: clientconn.go:788 [core] Subchannel Created  (t=+316.280237ms)
        tlogger.go:101: clientconn.go:788 [core] Subchannel(id:655) created  (t=+316.385338ms)
        tlogger.go:101: picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+316.698142ms)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to CONNECTING  (t=+316.889844ms)
        tlogger.go:101: clientconn.go:1252 [core] Subchannel picks a new address "localhost:46737" to connect  (t=+317.081846ms)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to CONNECTING  (t=+320.035879ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 649 from a parent (id=648) that doesn't currently exist  (t=+322.048302ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 649 from a parent (id=648) that doesn't currently exist  (t=+322.302404ms)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to READY  (t=+452.579161ms)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to READY  (t=+453.207868ms)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to SHUTDOWN  (t=+5.116691672s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to SHUTDOWN  (t=+5.116951275s)
        tlogger.go:101: clientconn.go:1478 [core] Subchannel Deleted  (t=+5.117073676s)
        tlogger.go:101: clientconn.go:1478 [core] Subchanel(id:655) deleted  (t=+5.117150877s)
        tlogger.go:101: clientconn.go:1097 [core] Channel Deleted  (t=+5.117251678s)
        end2end_test.go:5707: Running test in tcp-clear environment...
        tlogger.go:101: clientconn.go:172 [core] Channel Created  (t=+5.118573393s)
        tlogger.go:101: clientconn.go:251 [core] parsed scheme: "passthrough"  (t=+5.118756995s)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:45731  <nil> 0 <nil>}] <nil> <nil>}  (t=+5.118914297s)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:45731 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+5.1191585s)
        tlogger.go:101: clientconn.go:788 [core] Subchannel Created  (t=+5.119488203s)
        tlogger.go:101: clientconn.go:788 [core] Subchannel(id:661) created  (t=+5.119582005s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to CONNECTING  (t=+5.119891808s)
        tlogger.go:101: clientconn.go:1252 [core] Subchannel picks a new address "localhost:45731" to connect  (t=+5.120009609s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to CONNECTING  (t=+5.121229523s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 655 from a parent (id=654) that doesn't currently exist  (t=+5.12188903s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 655 from a parent (id=654) that doesn't currently exist  (t=+5.121994132s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to READY  (t=+5.124849064s)
        tlogger.go:101: roundrobin.go:50 [roundrobin] roundrobinPicker: newPicker called with info: {map[0x400024b100:{{localhost:45731  <nil> 0 <nil>}}]}  (t=+5.125264068s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to READY  (t=+5.125370569s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to SHUTDOWN  (t=+5.408457646s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to SHUTDOWN  (t=+5.410232466s)
        tlogger.go:101: clientconn.go:1478 [core] Subchannel Deleted  (t=+5.410370868s)
        tlogger.go:101: clientconn.go:1478 [core] Subchanel(id:661) deleted  (t=+5.41053307s)
        tlogger.go:101: clientconn.go:1097 [core] Channel Deleted  (t=+5.410640071s)
        end2end_test.go:5707: Running test in tcp-tls environment...
        tlogger.go:101: clientconn.go:172 [core] Channel Created  (t=+5.413949908s)
        tlogger.go:101: clientconn.go:251 [core] parsed scheme: "passthrough"  (t=+5.414081509s)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:38059  <nil> 0 <nil>}] <nil> <nil>}  (t=+5.414308712s)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:38059 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+5.414472514s)
        tlogger.go:101: clientconn.go:788 [core] Subchannel Created  (t=+5.414742917s)
        tlogger.go:101: clientconn.go:788 [core] Subchannel(id:667) created  (t=+5.414833618s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to CONNECTING  (t=+5.415162522s)
        tlogger.go:101: clientconn.go:1252 [core] Subchannel picks a new address "localhost:38059" to connect  (t=+5.415282923s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to CONNECTING  (t=+5.416305634s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 661 from a parent (id=660) that doesn't currently exist  (t=+5.417118344s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 661 from a parent (id=660) that doesn't currently exist  (t=+5.417287545s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to READY  (t=+5.54152294s)
        tlogger.go:101: roundrobin.go:50 [roundrobin] roundrobinPicker: newPicker called with info: {map[0x400024ac90:{{localhost:38059  <nil> 0 <nil>}}]}  (t=+5.541864243s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to READY  (t=+5.541975845s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to SHUTDOWN  (t=+10.032461037s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to SHUTDOWN  (t=+10.03268274s)
        tlogger.go:101: clientconn.go:1478 [core] Subchannel Deleted  (t=+10.032806541s)
        tlogger.go:101: clientconn.go:1478 [core] Subchanel(id:667) deleted  (t=+10.033067944s)
        tlogger.go:101: clientconn.go:1097 [core] Channel Deleted  (t=+10.033274346s)
        end2end_test.go:5707: Running test in handler-tls environment...
        tlogger.go:101: clientconn.go:172 [core] Channel Created  (t=+10.038153101s)
        tlogger.go:101: clientconn.go:251 [core] parsed scheme: "passthrough"  (t=+10.038343403s)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:33013  <nil> 0 <nil>}] <nil> <nil>}  (t=+10.038505105s)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:33013 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+10.038639107s)
        tlogger.go:101: clientconn.go:788 [core] Subchannel Created  (t=+10.038848409s)
        tlogger.go:101: clientconn.go:788 [core] Subchannel(id:673) created  (t=+10.03894761s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to CONNECTING  (t=+10.039285814s)
        tlogger.go:101: clientconn.go:1252 [core] Subchannel picks a new address "localhost:33013" to connect  (t=+10.039516516s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 667 from a parent (id=666) that doesn't currently exist  (t=+10.041298336s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 667 from a parent (id=666) that doesn't currently exist  (t=+10.041412038s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to CONNECTING  (t=+10.042049745s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to READY  (t=+10.166564042s)
        tlogger.go:101: roundrobin.go:50 [roundrobin] roundrobinPicker: newPicker called with info: {map[0x40006836e0:{{localhost:33013  <nil> 0 <nil>}}]}  (t=+10.166910046s)
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to READY  (t=+10.167025647s)
        end2end_test.go:5741: &{0x400000aa20}.Recv() = _, rpc error: code = DeadlineExceeded desc = context deadline exceeded, want _, <nil>
        tlogger.go:101: clientconn.go:435 [core] Channel Connectivity change to SHUTDOWN  (t=+15.043594509s)
        tlogger.go:101: clientconn.go:1141 [core] Subchannel Connectivity change to SHUTDOWN  (t=+15.043829912s)
        tlogger.go:101: clientconn.go:1478 [core] Subchannel Deleted  (t=+15.043965613s)
        tlogger.go:101: clientconn.go:1478 [core] Subchanel(id:673) deleted  (t=+15.044049914s)
        tlogger.go:101: clientconn.go:1097 [core] Channel Deleted  (t=+15.044149115s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 673 from a parent (id=672) that doesn't currently exist  (t=+15.051976303s)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 673 from a parent (id=672) that doesn't currently exist  (t=+15.052148505s)
2021/08/31 00:41:58 http: TLS handshake error from 127.0.0.1:44774: write tcp 127.0.0.1:45253->127.0.0.1:44774: use of closed network connection
2021/08/31 00:43:55 http: TLS handshake error from 127.0.0.1:38938: write tcp 127.0.0.1:43789->127.0.0.1:38938: use of closed network connection
2021/08/31 00:44:14 http: TLS handshake error from 127.0.0.1:54732: EOF
panic: test timed out after 7m0s

goroutine 102377 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1788 +0xc8
created by time.goFunc
	/opt/hostedtoolcache/go/1.17.0/x64/src/time/sleep.go:180 +0x40

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0x40001ec1a0, {0x636401, 0x4}, 0x668938)
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1307 +0x36c
testing.runTests.func1(0x40001ec1a0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1598 +0x80
testing.tRunner(0x40001ec1a0, 0x40000add18)
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1259 +0x100
testing.runTests(0x40000b6750, {0xad8030, 0x1, 0x1}, {0xc0437cba49bd40af, 0x61d417d57e, 0xaedfc0})
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1596 +0x3f8
testing.(*M).Run(0x400019c300)
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1504 +0x510
main.main()
	_testmain.go:43 +0x18c

goroutine 51674 [chan receive]:
testing.(*T).Run(0x40001ec340, {0x545fdb, 0xf}, 0x40000d05e0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1307 +0x36c
google.golang.org/grpc/internal/grpctest.RunSubTests(0x40001ec340, {0x634ee0, 0xb1dee8})
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:99 +0x37c
google.golang.org/grpc/test.Test(0x40001ec340)
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:90 +0x40
testing.tRunner(0x40001ec340, 0x668938)
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1259 +0x100
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1306 +0x350

goroutine 102355 [select]:
google.golang.org/grpc.(*pickerWrapper).pick(0x4000325a40, {0x70d560, 0x40003c42d0}, 0x1, {{0x65281a, 0x2d}, {0x70d560, 0x40003c42d0}})
	/home/runner/work/grpc-go/grpc-go/picker_wrapper.go:103 +0x18c
google.golang.org/grpc.(*ClientConn).getTransport(0x40001f8e00, {0x70d560, 0x40003c42d0}, 0x1, {0x65281a, 0x2d})
	/home/runner/work/grpc-go/grpc-go/clientconn.go:960 +0x5c
google.golang.org/grpc.(*clientStream).newAttemptLocked(0x4000326240, {0x0, 0x0}, 0x0)
	/home/runner/work/grpc-go/grpc-go/stream.go:406 +0x28c
google.golang.org/grpc.newClientStreamWithParams({0x70d528, 0x4000497e00}, 0xae12c0, 0x40001f8e00, {0x65281a, 0x2d}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/grpc-go/grpc-go/stream.go:330 +0xe74
google.golang.org/grpc.newClientStream.func2({0x70d528, 0x4000497e00}, 0x668700)
	/home/runner/work/grpc-go/grpc-go/stream.go:184 +0xa0
google.golang.org/grpc.newClientStream({0x70d528, 0x4000497e00}, 0xae12c0, 0x40001f8e00, {0x65281a, 0x2d}, {0x0, 0x0, 0x0})
	/home/runner/work/grpc-go/grpc-go/stream.go:212 +0x434
google.golang.org/grpc.(*ClientConn).NewStream(0x40001f8e00, {0x70d528, 0x4000497e00}, 0xae12c0, {0x65281a, 0x2d}, {0x0, 0x0, 0x0})
	/home/runner/work/grpc-go/grpc-go/stream.go:158 +0x18c
google.golang.org/grpc/test/grpc_testing.(*testServiceClient).StreamingOutputCall(0x4000399820, {0x70d528, 0x4000497e00}, 0x40004f8690, {0x0, 0x0, 0x0})
	/home/runner/work/grpc-go/grpc-go/test/grpc_testing/test_grpc.pb.go:74 +0x94
google.golang.org/grpc/test.testServerStreaming(0x4001429520, {{0x640e42, 0x13}, {0x63612c, 0x3}, {0x63612f, 0x3}, 0x0, {0x0, 0x0}, ...})
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:4058 +0x2c4
google.golang.org/grpc/test.s.TestServerStreaming({{}}, 0x4001429520)
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:4035 +0xa4
google.golang.org/grpc/internal/grpctest.RunSubTests.func1(0x4001429520)
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:103 +0x74
testing.tRunner(0x4001429520, 0x40000d05e0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1259 +0x100
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.0/x64/src/testing/testing.go:1306 +0x350

goroutine 102375 [select]:
google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake(0x40001c2200, {0x70d560, 0x40003c4390}, {0x6403f2, 0x12}, {0x71a280, 0x40001c2240})
	/home/runner/work/grpc-go/grpc-go/credentials/tls.go:90 +0x230
google.golang.org/grpc/internal/transport.newHTTP2Client({0x70d528, 0x40000743c0}, {0x70d4b8, 0x40009fac80}, {{0x40004cea8f, 0xf}, {0x6403f2, 0x12}, 0x0, 0x0, ...}, ...)
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:252 +0x6e0
google.golang.org/grpc/internal/transport.NewClientTransport(...)
	/home/runner/work/grpc-go/grpc-go/internal/transport/transport.go:576
google.golang.org/grpc.(*addrConn).createTransport(0x400022c580, {{0x40004cea8f, 0xf}, {0x6403f2, 0x12}, 0x0, 0x0, {0x0, 0x0}}, {{0x640014, ...}, ...}, ...)
	/home/runner/work/grpc-go/grpc-go/clientconn.go:1316 +0x414
google.golang.org/grpc.(*addrConn).tryAllAddrs(0x400022c580, {0x40009fad40, 0x1, 0x1}, {0xc0437cbf480cc740, 0x667a7f1f5f, 0xaedfc0})
	/home/runner/work/grpc-go/grpc-go/clientconn.go:1254 +0x3cc
google.golang.org/grpc.(*addrConn).resetTransport(0x400022c580)
	/home/runner/work/grpc-go/grpc-go/clientconn.go:1189 +0x260
google.golang.org/grpc.(*addrConn).connect(0x400022c580)
	/home/runner/work/grpc-go/grpc-go/clientconn.go:867 +0x1f8
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:285 +0xc8

goroutine 102373 [IO wait]:
internal/poll.runtime_pollWait(0x5527f8fbb8, 0x72)
	/opt/hostedtoolcache/go/1.17.0/x64/src/runtime/netpoll.go:229 +0xa4
internal/poll.(*pollDesc).wait(0x4000173418, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x38
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x4000173400)
	/opt/hostedtoolcache/go/1.17.0/x64/src/internal/poll/fd_unix.go:402 +0x1f4
net.(*netFD).accept(0x4000173400)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/fd_unix.go:173 +0x2c
net.(*TCPListener).accept(0x40003bc6c0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/tcpsock_posix.go:140 +0x2c
net.(*TCPListener).Accept(0x40003bc6c0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/tcpsock.go:262 +0x34
google.golang.org/grpc.(*Server).Serve(0x400046ba40, {0x70b8b8, 0x40003bc6c0})
	/home/runner/work/grpc-go/grpc-go/server.go:779 +0x3f4
created by google.golang.org/grpc/test.(*test).listenAndServe
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:678 +0x1df0

goroutine 102376 [IO wait]:
internal/poll.runtime_pollWait(0x5527f93150, 0x72)
	/opt/hostedtoolcache/go/1.17.0/x64/src/runtime/netpoll.go:229 +0xa4
internal/poll.(*pollDesc).wait(0x400070c398, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x38
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400070c380, {0x40001c6240, 0x205, 0x205})
	/opt/hostedtoolcache/go/1.17.0/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x400070c380, {0x40001c6240, 0x205, 0x205})
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/fd_posix.go:56 +0x44
net.(*conn).Read(0x40001c2240, {0x40001c6240, 0x205, 0x205})
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/net.go:183 +0x4c
crypto/tls.(*atLeastReader).Read(0x40003bc858, {0x40001c6240, 0x205, 0x205})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:777 +0x58
bytes.(*Buffer).ReadFrom(0x40001f93f8, {0x6fde20, 0x40003bc858})
	/opt/hostedtoolcache/go/1.17.0/x64/src/bytes/buffer.go:204 +0xa4
crypto/tls.(*Conn).readFromUntil(0x40001f9180, {0x6fef00, 0x40001c2240}, 0x5)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:799 +0xe0
crypto/tls.(*Conn).readRecordOrCCS(0x40001f9180, 0x0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:606 +0xf4
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).readHandshake(0x40001f9180)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1009 +0x48
crypto/tls.(*Conn).clientHandshake(0x40001f9180, {0x70d4b8, 0x40009faf00})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/handshake_client.go:179 +0x230
crypto/tls.(*Conn).handshakeContext(0x40001f9180, {0x70d4f0, 0x40000be000})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1445 +0x388
crypto/tls.(*Conn).HandshakeContext(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1395
crypto/tls.(*Conn).Handshake(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1379
google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func1(0x400114c060, 0x40001f9180)
	/home/runner/work/grpc-go/grpc-go/credentials/tls.go:87 +0x4c
created by google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
	/home/runner/work/grpc-go/grpc-go/credentials/tls.go:86 +0x1d0

goroutine 102374 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0x40004f8460)
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:77 +0x7c
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:67 +0x1f0

goroutine 102403 [runnable]:
math/big.nat.montgomery({0x40003346c0, 0x20, 0x46}, {0x4000334240, 0x20, 0x44}, {0x4000334240, 0x20, 0x44}, {0x40002d8dc0, ...}, ...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/math/big/nat.go:213 +0x3d0
math/big.nat.expNNMontgomery({0x4000334240, 0x40, 0x44}, {0x400037d900, 0x40, 0x184}, {0x400058d440, 0x20, 0x45}, {0x40002d8dc0, ...})
	/opt/hostedtoolcache/go/1.17.0/x64/src/math/big/nat.go:1124 +0xa58
math/big.nat.expNN({0x0, 0x0, 0x0}, {0x400037d900, 0x40, 0x184}, {0x400058d440, 0x20, 0x45}, {0x40002d8dc0, ...})
	/opt/hostedtoolcache/go/1.17.0/x64/src/math/big/nat.go:937 +0x3fc
math/big.(*Int).Exp(0x400021e540, 0x4000444f98, 0x40000d18c0, 0x40000d1820)
	/opt/hostedtoolcache/go/1.17.0/x64/src/math/big/int.go:509 +0x148
crypto/rsa.decrypt({0x6fdde0, 0x4000096660}, 0x40004977a0, 0x4000445128)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/rsa/rsa.go:535 +0x3e8
crypto/rsa.decryptAndCheck({0x6fdde0, 0x4000096660}, 0x40004977a0, 0x4000445128)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/rsa/rsa.go:570 +0x40
crypto/rsa.signPSSWithSalt({0x6fdde0, 0x4000096660}, 0x40004977a0, 0x5, {0x40000385e0, 0x20, 0x20}, {0x4000038620, 0x20, 0x20})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/rsa/pss.go:217 +0x130
crypto/rsa.SignPSS({0x6fdde0, 0x4000096660}, 0x40004977a0, 0x5, {0x40000385e0, 0x20, 0x20}, 0x4000298330)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/rsa/pss.go:281 +0x1d8
crypto/rsa.(*PrivateKey).Sign(0x40004977a0, {0x6fdde0, 0x4000096660}, {0x40000385e0, 0x20, 0x20}, {0x6fde00, 0x4000298330})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/rsa/rsa.go:146 +0x74
crypto/tls.(*serverHandshakeStateTLS13).sendServerCertificate(0x40004455d0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/handshake_server_tls13.go:622 +0x3e4
crypto/tls.(*serverHandshakeStateTLS13).handshake(0x40004455d0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/handshake_server_tls13.go:61 +0xac
crypto/tls.(*Conn).serverHandshake(0x40002fa000, {0x70d4b8, 0x40004882c0})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/handshake_server.go:54 +0xa4
crypto/tls.(*Conn).handshakeContext(0x40002fa000, {0x70d4f0, 0x40000be000})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1445 +0x388
crypto/tls.(*Conn).HandshakeContext(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1395
crypto/tls.(*Conn).Handshake(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1379
google.golang.org/grpc/credentials.(*tlsCreds).ServerHandshake(0x40001c21a0, {0x71a280, 0x400009c0c0})
	/home/runner/work/grpc-go/grpc-go/credentials/tls.go:115 +0x114
google.golang.org/grpc/internal/transport.NewServerTransport({0x71a280, 0x400009c0c0}, 0x4000445e68)
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_server.go:140 +0x88
google.golang.org/grpc.(*Server).newHTTP2Transport(0x400046ba40, {0x71a280, 0x400009c0c0})
	/home/runner/work/grpc-go/grpc-go/server.go:880 +0x100
google.golang.org/grpc.(*Server).handleRawConn(0x400046ba40, {0x4000286260, 0xf}, {0x71a280, 0x400009c0c0})
	/home/runner/work/grpc-go/grpc-go/server.go:837 +0x8c
google.golang.org/grpc.(*Server).Serve.func3(0x400046ba40, {0x70b8b8, 0x40003bc6c0}, {0x71a280, 0x400009c0c0})
	/home/runner/work/grpc-go/grpc-go/server.go:821 +0x60
created by google.golang.org/grpc.(*Server).Serve
	/home/runner/work/grpc-go/grpc-go/server.go:820 +0x46c
FAIL	google.golang.org/grpc/test	420.266s
```

**Comment by dfawley** [comment]
https://github.com/grpc/grpc-go/pull/4816/checks?check_run_id=3705204412
