### ISSUE TITLE
Large stream deadlocked in writeQuota

### ISSUE THREAD

**Issue by tonistiigi** [grpc/grpc-go#4722]
### What version of gRPC are you using?
v1.39.0

edit: master ef66d13abb84ad6c6d99c8cbf3697607b7891f32 reproduces as well

### What version of Go are you using (`go version`)?
1.16

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?

A large stream (~500MB of data with some records quite small) sometimes hangs and never recovers. The send call seems to be blocked in `/transport.(*writeQuota).get`. Found a similar report in https://github.com/grpc/grpc-go/issues/2427 and have confirmed the reader side is reading but is blocked as well.

```
client:

goroutine 179 [select, 6 minutes]:
google.golang.org/grpc/internal/transport.(*recvBufferReader).read(0xc0004905f0, 0xc0036e067d, 0x398c, 0x398c, 0x546, 0x0, 0x0)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/internal/transport/transport.go:177 +0xa5
google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0xc0004905f0, 0xc0036e067d, 0x398c, 0x398c, 0x546, 0x0, 0x0)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/internal/transport/transport.go:171 +0x211
google.golang.org/grpc/internal/transport.(*transportReader).Read(0xc000842330, 0xc0036e067d, 0x398c, 0x398c, 0x546, 0x0, 0x0)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/internal/transport/transport.go:483 +0x55
io.ReadAtLeast(0x2173980, 0xc000842330, 0xc0036dc000, 0x8009, 0x8009, 0x8009, 0x1bcdfa0, 0x1, 0xc0036dc000)
        /usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
google.golang.org/grpc/internal/transport.(*Stream).Read(0xc00061a000, 0xc0036dc000, 0x8009, 0x8009, 0x5, 0x0, 0x0)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/internal/transport/transport.go:467 +0xd2
google.golang.org/grpc.(*parser).recvMsg(0xc0006aa750, 0x400000, 0xc00010fb58, 0xbdf04e, 0xc0036c0000, 0x8009, 0x8009, 0x7f7624b491e8)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/rpc_util.go:577 +0x112
google.golang.org/grpc.recvAndDecompress(0xc0006aa750, 0xc00061a000, 0x0, 0x0, 0x400000, 0x0, 0x0, 0x0, 0xc00010fc50, 0x4c113b, ...)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/rpc_util.go:689 +0x4d
google.golang.org/grpc.recv(0xc0006aa750, 0x7f7624a87798, 0x2edc1a0, 0xc00061a000, 0x0, 0x0, 0x1e5da20, 0xc0008427e0, 0x400000, 0x0, ...)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/rpc_util.go:757 +0x9b
google.golang.org/grpc.(*serverStream).RecvMsg(0xc0004a69c0, 0x1e5da20, 0xc0008427e0, 0x0, 0x0)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/google.golang.org/grpc/stream.go:1545 +0x156
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.(*serverStream).RecvMsg(0xc0008425d0, 0x1e5da20, 0xc0008427e0, 0xc00010fe70, 0xd8deda)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go:368 +0x54
github.com/tonistiigi/fsutil.(*receiver).run.func2(0x0, 0x0)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/github.com/tonistiigi/fsutil/receive.go:169 +0x136
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0008426f0, 0xc0006aa888)
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /build/moby-buildx/.gopath/src/github.com/docker/buildx/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66



server:

goroutine 436 [select, 5 minutes]:
google.golang.org/grpc/internal/transport.(*writeQuota).get(0xc000045460, 0xc00000800e, 0xc000b938f0, 0x40e338)
        /src/vendor/google.golang.org/grpc/internal/transport/flowcontrol.go:59 +0x7a
google.golang.org/grpc/internal/transport.(*http2Client).Write(0xc000294000, 0xc0005199e0, 0xc00046f890, 0x5, 0x5, 0xc000dc0000, 0x8009, 0x8009, 0xc00046f895, 0x14ac6a0, ...)
        /src/vendor/google.golang.org/grpc/internal/transport/http2_client.go:936 +0x105
google.golang.org/grpc.(*csAttempt).sendMsg(0xc00086b280, 0x14ac6a0, 0xc000ad7830, 0xc00046f890, 0x5, 0x5, 0xc000dc0000, 0x8009, 0x8009, 0xc000dc0000, ...)
        /src/vendor/google.golang.org/grpc/stream.go:917 +0x129
google.golang.org/grpc.(*clientStream).SendMsg.func2(0xc00086b280, 0x7f6002957a68, 0x50)
        /src/vendor/google.golang.org/grpc/stream.go:782 +0xb3
google.golang.org/grpc.(*clientStream).withRetry(0xc0005197a0, 0xc00007f040, 0xc000b93bb8, 0x1ed8590, 0x0)
        /src/vendor/google.golang.org/grpc/stream.go:662 +0x3df
google.golang.org/grpc.(*clientStream).SendMsg(0xc0005197a0, 0x14ac6a0, 0xc000ad7830, 0x0, 0x0)
        /src/vendor/google.golang.org/grpc/stream.go:788 +0x3a5
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.(*clientStream).SendMsg(0xc00064c680, 0x14ac6a0, 0xc000ad7830, 0x0, 0x0)
        /src/vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go:163 +0x62
github.com/tonistiigi/fsutil.(*syncStream).SendMsg(0xc0005df9f8, 0x14ac6a0, 0xc000ad7830, 0x0, 0x0)
        /src/vendor/github.com/tonistiigi/fsutil/send.go:205 +0x6d
github.com/tonistiigi/fsutil.(*fileSender).Write(0xc000457b90, 0xc000a5c000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /src/vendor/github.com/tonistiigi/fsutil/send.go:191 +0xa7
io.copyBuffer(0x1685480, 0xc000457b90, 0x1686f40, 0xc00000e990, 0xc000a5c000, 0x8000, 0x8000, 0x14e0980, 0xc0007fe600, 0x1686f40)
        /usr/local/go/src/io/io.go:425 +0x21c
io.CopyBuffer(0x1685480, 0xc000457b90, 0x1686f40, 0xc00000e990, 0xc000a5c000, 0x8000, 0x8000, 0xf1394, 0xc00087f858, 0x0)
        /usr/local/go/src/io/io.go:396 +0x8c
github.com/tonistiigi/fsutil.(*sender).sendFile(0xc00087f860, 0xc0005f0750, 0x0, 0x0)
        /src/vendor/github.com/tonistiigi/fsutil/send.go:138 +0x2d4
github.com/tonistiigi/fsutil.(*sender).run.func2(0xc00038c0b8, 0x4425d6)
        /src/vendor/github.com/tonistiigi/fsutil/send.go:75 +0xc6
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000611740, 0xc0000454e0)
        /src/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /src/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

The traces are from different runs so times don't match exactly but from the same reproducer. 

Enabling logs changes timings enough to make my main repro not work anymore. With an even bigger stream, I got it to block with logs but nothing interesting there. The last line is just `Channel Connectivity change to READY`. I can also only repro this on specific machines, eg. in Github Codespaces.

Possibly something wrong on my side but would need help figuring out the next steps.

**Comment by zasweq** [comment]
Can you please add code that reproduces this problem so that the team can take a look?

**Comment by tonistiigi** [comment]
It is very much specific to timings. As I said, even a simple change like adding logs changes the behavior so I can't make an isolated reproducer. I can give a reproducer in our open source app that reproduces in github codespaces environment. I can also try to add debug logs on specific areas/conditions that you would wish to see and then try to tweak the reproducer to trigger the lock condition again.

**Comment by zasweq** [comment]
The team would love a finite example, so we can take a look ourselves. Thanks!

**Comment by easwars** [comment]
We can try looking at our github codespaces environment. Not sure if you would have to give us any specific permissions etc for that.

**Comment by ashinrot** [comment]
I have the same problem, with totally same server and client side stack trace. The grpc version is v1.31.0

**Comment by dfawley** [comment]
> I have the same problem, with totally same server and client side stack trace. The grpc version is v1.31.0

This is over a 1 year old release; please try to reproduce with 1.42 and provide a reliable way of reproducing so we can investigate.

**Comment by tonistiigi** [comment]
I reproduced this in ef66d13 (mentioned in original report)

**Comment by dfawley** [comment]
> I reproduced this in ef66d13 (mentioned in original report)

Does your environment happen to have anything between the client and server (e.g. a reverse proxy)?  Can you reproduce this on localhost?

**Comment by ashinrot** [comment]
> > I reproduced this in [ef66d13](https://github.com/grpc/grpc-go/commit/ef66d13abb84ad6c6d99c8cbf3697607b7891f32) (mentioned in original report)
> 
> Does your environment happen to have anything between the client and server (e.g. a reverse proxy)? Can you reproduce this on localhost?

My client and server run on localhost, and use unix domain socket.

**Comment by dfawley** [comment]
> My client and server run on localhost, and use unix domain socket.

That sounds promising.  Can you reproduce at HEAD?  Can you simplify the code into a minimal reproduction and share it, if so?
