### ISSUE TITLE
Encounter io.grpc.StatusRuntimeException frequently

### ISSUE THREAD

**Issue by rantianhua** [grpc/grpc-go#4856]
### What version of gRPC-Java are you using?

1.37.0

### What is your environment?

Client:
MacOS 10.15.7 
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)

Server:
Linux
Use groc-go v1.40.0 to build the grpc server.

### What did you expect to see?

The grpc connection is stable.

### What did you see instead?

I encountered StatusRuntimeException frequently during the client receives data from the server, And the stacktrace is the following:

```

onError
io.grpc.StatusRuntimeException: INTERNAL: Internal error
Rst Stream
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:500)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:65)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:592)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:508)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:632)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:98)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
``` 

If I tried again after this error occurred, then there was anthor error:

```
onError
io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:500)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:65)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:592)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:508)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:632)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:98)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Steps to reproduce the bug

I encountered the error frequently, with no special reproduction steps.

Server configuration:

```
	server := grpc.NewServer(
		grpc.StreamInterceptor(
			grpc_middleware.ChainStreamServer(
				grpc_recovery.StreamServerInterceptor(grpc_recovery.WithRecoveryHandler(recoveryHandlerFunc)),
				grpc_zap.StreamServerInterceptor(log.Logger(ctx).Logger),
			),
		),
		grpc.ReadBufferSize(1024*1024),
		grpc.KeepaliveParams(keepalive.ServerParameters{
			Time:    time.Hour,
			Timeout: time.Minute,
		}),
		grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
			MinTime:             time.Second * 10,
			PermitWithoutStream: true,
		}),
	)
```

Client configuration:

```
            channel = ManagedChannelBuilder.forAddress("xxx", 8082)
                .keepAliveWithoutCalls(true)
                .usePlaintext()
                .enableRetry()
                .executor(Dispatchers.Default.asExecutor())
                .keepAliveTime(20, TimeUnit.SECONDS)
                .keepAliveTimeout(1, TimeUnit.MINUTES)
                .keepAliveWithoutCalls(true)
                .build()
```

**Comment by rantianhua** [comment]
I also reported this problem on grpc-java project with the link https://github.com/grpc/grpc-java/issues/8470. I've talked with @ejona86 in 8470, and now we think we need to find the root cause from the server side.

**Comment by ejona86** [comment]
Wait... this is okhttp. Looks like the [default inbound metadata size for grpc-okhttp is MAX_INT (2^31-1)](https://github.com/grpc/grpc-java/blob/0d25d8f7d6aef41d47f3734704b2b868baea651f/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L178) (huh). If we think there's an overflow or the like, rantianhua did test with a lower (but we thought it was higher!) setting of 1 MB and saw the same results. Although I could believe there could be a bug in that flow.

Looking more at the Java code, it seems the okhttp transport doesn't send maxInboundMessageSize in the SETTINGS at all (even when the limit is in place), so it would be the default of infinite.
