### ISSUE TITLE
panic on grpclog.(*loggerT).Infoln()

### ISSUE THREAD

**Issue by vkatopod** [grpc/grpc-go#4921]
### What version of gRPC are you using?
v1.36.0

### What version of Go are you using (`go version`)?
go1.16.5 linux/amd64

### What operating system (Linux, Windows, …) and version?
centos-micro:7.9-22.0
CentOS Linux 7 (Core)

### What did you do?
Call grpc Dial method:

"google.golang.org/grpc"

conn, err := grpc.Dial(port, grpc.WithInsecure())
if err != nil {
  log.Fatal(err)
}

### What did you see instead?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46e0e8]

goroutine 1 [running]:
log.(*Logger).formatHeader(0xc000132140, 0xc000132170, 0xc04c9a9734a8c319, 0x600dae8, 0xc09120, 0x0, 0x0, 0x0)
/usr/local/go/src/log/log.go:105 +0x16e5
log.(*Logger).Output(0xc000132140, 0x2, 0xc000028560, 0x19, 0x0, 0x0)
/usr/local/go/src/log/log.go:179 +0x18d
log.(*Logger).Println(0xc000132140, 0xc0000205c0, 0x2, 0x2)
/usr/local/go/src/log/log.go:200 +0x6a
google.golang.org/grpc/grpclog.(*loggerT).Infoln(0xc0000200e0, 0xc0000205c0, 0x2, 0x2)
[HOME]/pkg/mod/google.golang.org/grpc@v1.36.0/grpclog/loggerv2.go:153 +0x58
google.golang.org/grpc/internal/grpclog.InfoDepth(0x2, 0xc0000205c0, 0x2, 0x2)
[HOME]/pkg/mod/google.golang.org/grpc@v1.36.0/internal/grpclog/grpclog.go:37 +0xa6
google.golang.org/grpc/grpclog.(*componentData).InfoDepth(0xc000112770, 0x1, 0xc000113c90, 0x1, 0x2)
[HOME]/pkg/mod/google.golang.org/grpc@v1.36.0/grpclog/component.go:36 +0x177
google.golang.org/grpc/internal/channelz.Infof(0x978298, 0xc000112770, 0x0, 0x8eba25, 0x11, 0xc000293950, 0x1, 0x1)
[HOME]/pkg/mod/google.golang.org/grpc@v1.36.0/internal/channelz/logging.go:50 +0x1a8
google.golang.org/grpc.DialContext(0x972a10, 0xc00002e058, 0x7ffc25c5a8f2, 0xe, 0xc000293f18, 0x1, 0x1, 0x0, 0x0, 0x0)
[HOME]/pkg/mod/google.golang.org/grpc@v1.36.0/clientconn.go:251 +0x996
google.golang.org/grpc.Dial(...)
[HOME]/pkg/mod/google.golang.org/grpc@v1.36.0/clientconn.go:105
main.main()
[HOME]/src/health/healthClient/main.go:21 +0xf8

**Comment by vkatopod** [comment]
Thanks for the answer. We will upgrade the grpc library to 1.42. The tests were performed by different team, I'll ask them if they can provide the test case that produced the error.
