### ISSUE TITLE
TestHandlerTransport_HandleStreams_MultiWriteStatus block issue

### ISSUE THREAD

**Issue by charlesxsh** [grpc/grpc-go#4945]
### What version of gRPC are you using?
commit 9280052d36656451dd7568a18a836c2a74edaf6c

### What version of Go are you using (`go version`)?
1.16

### What operating system (Linux, Windows, …) and version?
Linux/Debian

### What did you do?
If possible, provide a recipe for reproducing the error.
These potential blocking issues are found by our current WIP project. Some issues are hard to reproduce without our tool/instrumentation. We will release it as soon as it is ready.
This issue is part of #4672, I simply seperate them into individual issue so that we can track them one by one.

### What did you expect to see?
no blocking issue

### What did you see instead?

TestHandlerTransport_HandleStreams_MultiWriteStatus (internal/transport/handler_server_test.go)

https://github.com/grpc/grpc-go/blob/84d0920b59e5f138ffd4da11f7b2ab51e862b581/internal/transport/handler_server.go#L185

https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/handler_server.go#L73

we can see the `writes` channel has no buffer.
`ht.WriteStatus` => `err := ht.do(...)`

`ht.do` send func to writes, but writes has no receiver if
https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/handler_server.go#L428 is chosen.
So it blocks at sending. So later goroutine will be blocked before previous ht.writeStatusMu is still locked.

https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/handler_server_test.go#L403-L407

**Comment by charlesxsh** [comment]
@dfawley Hi there, here is more details:

```
goroutine 24 [semacquire]:
sync.runtime_Semacquire(0xc0000aaae8)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0000aaae0)
	/usr/local/go/src/sync/waitgroup.go:149 +0x119
google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1(0xc000143320, 0xc0000ef080)
	/fuzz/target/internal/transport/handler_server_test.go:470 +0x23e
created by google.golang.org/grpc/internal/transport.testHandlerTransportHandleStreams.func1
	/fuzz/target/internal/transport/handler_server_test.go:491 +0x45

goroutine 25 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000a6f3c, 0x932300, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000a6f38)
	/usr/local/go/src/sync/mutex.go:152 +0x105
sync.(*Mutex).Lock(0xc0000a6f38)
	/usr/local/go/src/sync/mutex.go:95 +0x10b
google.golang.org/grpc/internal/transport.(*serverHandlerTransport).WriteStatus(0xc0000a6ea0, 0xc0000ef080, 0xc000260020, 0x0, 0x0)
	/fuzz/target/internal/transport/handler_server.go:237 +0xd2
google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1.1(0xc0000aaae0, 0xc000143320, 0xc0000ef080)
	/fuzz/target/internal/transport/handler_server_test.go:462 +0xab
created by google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1
	/fuzz/target/internal/transport/handler_server_test.go:460 +0x1d6

goroutine 26 [select]:
google.golang.org/grpc/internal/transport.(*serverHandlerTransport).do(0xc0000a6ea0, 0xc000143aa0, 0xc0000a5f90, 0x1)
	/fuzz/target/internal/transport/handler_server.go:211 +0x3b6
google.golang.org/grpc/internal/transport.(*serverHandlerTransport).WriteStatus(0xc0000a6ea0, 0xc0000ef080, 0xc000260018, 0x0, 0x0)
	/fuzz/target/internal/transport/handler_server.go:241 +0x198
google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1.1(0xc0000aaae0, 0xc000143320, 0xc0000ef080)
	/fuzz/target/internal/transport/handler_server_test.go:462 +0xab
created by google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1
	/fuzz/target/internal/transport/handler_server_test.go:460 +0x1d6


goroutine 27 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000a6f3c, 0x932300, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000a6f38)
	/usr/local/go/src/sync/mutex.go:152 +0x105
sync.(*Mutex).Lock(0xc0000a6f38)
	/usr/local/go/src/sync/mutex.go:95 +0x10b
google.golang.org/grpc/internal/transport.(*serverHandlerTransport).WriteStatus(0xc0000a6ea0, 0xc0000ef080, 0xc000260028, 0x0, 0x0)
	/fuzz/target/internal/transport/handler_server.go:237 +0xd2
google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1.1(0xc0000aaae0, 0xc000143320, 0xc0000ef080)
	/fuzz/target/internal/transport/handler_server_test.go:462 +0xab
created by google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1
	/fuzz/target/internal/transport/handler_server_test.go:460 +0x1d6

goroutine 28 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000a6f3c, 0x932300, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000a6f38)
	/usr/local/go/src/sync/mutex.go:152 +0x105
sync.(*Mutex).Lock(0xc0000a6f38)
	/usr/local/go/src/sync/mutex.go:95 +0x10b
google.golang.org/grpc/internal/transport.(*serverHandlerTransport).WriteStatus(0xc0000a6ea0, 0xc0000ef080, 0xc000260030, 0x0, 0x0)
	/fuzz/target/internal/transport/handler_server.go:237 +0xd2
google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1.1(0xc0000aaae0, 0xc000143320, 0xc0000ef080)
	/fuzz/target/internal/transport/handler_server_test.go:462 +0xab
created by google.golang.org/grpc/internal/transport.TestHandlerTransport_HandleStreams_MultiWriteStatus.func1
	/fuzz/target/internal/transport/handler_server_test.go:460 +0x1d6
```

The test passed as usual, it just some goroutine might leak because of this blocking issue.

**Comment by dfawley** [comment]
Does this reproduce at HEAD?  Do you have a proposed fix?
