### ISSUE TITLE
TestEDSHandleResponseWithoutWatch block issue

### ISSUE THREAD

**Issue by charlesxsh** [grpc/grpc-go#4953]
### What version of gRPC are you using?
commit 9280052d36656451dd7568a18a836c2a74edaf6c

### What version of Go are you using (`go version`)?
1.16

### What operating system (Linux, Windows, …) and version?
Linux/Debian

### What did you do?
If possible, provide a recipe for reproducing the error.
These potential blocking issues are found by our current WIP project. Some issues are hard to reproduce without our tool/instrumentation. We will release it as soon as it is ready.
This issue is part of #4672, I simply seperate them into individual issue so that we can track them one by one.

### What did you expect to see?
no blocking issue

### What did you see instead?

TestEDSHandleResponseWithoutWatch (xds/internal/client/v2/eds_test.go)

https://github.com/grpc/grpc-go/blob/9c668aeab86903a70e291eb47a04f48d84e67006/xds/internal/testutils/fakeserver/server.go#L190

TestEDSHandleResponseWithoutWatch's one goroutine might be blocked at line 190.

**Comment by charlesxsh** [comment]
added more detail at

```
goroutine 15 [chan receive]:
google.golang.org/grpc/xds/internal/testutils/fakeserver.(*xdsServer).StreamAggregatedResources(0xc00075a7b0, 0xe81100, 0xc00051f9a0, 0xe75f80, 0xc00075a7b0)
	/fuzz/target/xds/internal/testutils/fakeserver/server.go:251 +0x149
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0xc247e0, 0xc00075a7b0, 0xe7edc8, 0xc0000de7e0, 0x1, 0x1)
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.9-0.20201210154907-fd9021fe5dad/envoy/service/discovery/v2/ads.pb.go:289 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000471340, 0xe81e58, 0xc0005823c0, 0xc0000f71e0, 0xc00086e8d0, 0x14bca80, 0x0, 0x0, 0x0)
	/fuzz/target/server.go:1587 +0xe84
google.golang.org/grpc.(*Server).handleStream(0xc000471340, 0xe81e58, 0xc0005823c0, 0xc0000f71e0, 0x0)
	/fuzz/target/server.go:1672 +0xd08
google.golang.org/grpc.(*Server).serveStreams.func1.3(0xc000a90000, 0xc000471340, 0xe81e58, 0xc0005823c0, 0xc0000f71e0)
	/fuzz/target/server.go:981 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/fuzz/target/server.go:979 +0x510

goroutine 16 [select]:
google.golang.org/grpc/internal/transport.(*recvBufferReader).read(0xc000880960, 0xc0006c21a8, 0x5, 0x5, 0x1, 0x1, 0x485b7d)
	/fuzz/target/internal/transport/transport.go:255 +0x50c
google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0xc000880960, 0xc0006c21a8, 0x5, 0x5, 0x1, 0x1, 0xc00056a5a0)
	/fuzz/target/internal/transport/transport.go:233 +0x231
google.golang.org/grpc/internal/transport.(*transportReader).Read(0xc000948f30, 0xc0006c21a8, 0x5, 0x5, 0xc0006c2198, 0xc000556b90, 0x7bd43c)
	/fuzz/target/internal/transport/transport.go:718 +0x7c
io.ReadAtLeast(0xe66ce0, 0xc000948f30, 0xc0006c21a8, 0x5, 0x5, 0x5, 0x0, 0x58b2cb, 0xdad688)
	/usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
google.golang.org/grpc/internal/transport.(*Stream).Read(0xc0000f71e0, 0xc0006c21a8, 0x5, 0x5, 0x1, 0x1, 0xc0000de7e0)
	/fuzz/target/internal/transport/transport.go:701 +0xf4
google.golang.org/grpc.(*parser).recvMsg(0xc0006c2198, 0x400000, 0x19, 0x45b005, 0xc00051f820, 0xc000509588, 0x0, 0xc00051f820)
	/fuzz/target/rpc_util.go:585 +0x8d
google.golang.org/grpc.recvAndDecompress(0xc0006c2198, 0xc0000f71e0, 0x0, 0x0, 0x400000, 0x0, 0x0, 0x0, 0xc0005095e0, 0x41be33, ...)
	/fuzz/target/rpc_util.go:716 +0x4d
google.golang.org/grpc.recv(0xc0006c2198, 0x7f6d7a646798, 0x1589818, 0xc0000f71e0, 0x0, 0x0, 0xd091e0, 0xc000630080, 0x400000, 0x0, ...)
	/fuzz/target/rpc_util.go:784 +0x9b
google.golang.org/grpc.(*serverStream).RecvMsg(0xc0000de7e0, 0xd091e0, 0xc000630080, 0x0, 0x0)
	/fuzz/target/stream.go:1705 +0x185
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2.(*aggregatedDiscoveryServiceStreamAggregatedResourcesServer).Recv(0xc00051f9a0, 0xe81e58, 0xc0005823c0, 0xc0000f71e0)
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.9-0.20201210154907-fd9021fe5dad/envoy/service/discovery/v2/ads.pb.go:308 +0x62
google.golang.org/grpc/xds/internal/testutils/fakeserver.(*xdsServer).StreamAggregatedResources.func1(0xe81100, 0xc00051f9a0, 0xc0008b0800, 0xc00075a7b0)
	/fuzz/target/xds/internal/testutils/fakeserver/server.go:163 +0x62
created by google.golang.org/grpc/xds/internal/testutils/fakeserver.(*xdsServer).StreamAggregatedResources
	/fuzz/target/xds/internal/testutils/fakeserver/server.go:161 +0xe9

goroutine 66 [select]:
google.golang.org/grpc/xds/internal/testutils/fakeserver.(*xdsServer).StreamAggregatedResources.func2(0xc0008b0800, 0xc00075a7b0, 0xe81100, 0xc00051f9a0)
	/fuzz/target/xds/internal/testutils/fakeserver/server.go:182 +0x197
created by google.golang.org/grpc/xds/internal/testutils/fakeserver.(*xdsServer).StreamAggregatedResources
	/fuzz/target/xds/internal/testutils/fakeserver/server.go:172 +0x129
```

**Comment by charlesxsh** [comment]
description:
errCh is sent in two places:


```
go func() {
		for {
			req, err := s.Recv()
			if err != nil {
				errCh <- err
				return
			}
			xdsS.reqChan.Send(&Request{req, err})
		}
	}()

```


```
go func() {
	var retErr error
        defer func() {
	        errCh <- retErr
        }()

        select {
					case r := <-xdsS.respChan:
						if r.Err != nil {
							retErr = r.Err
							return
						}
						if err := s.Send(r.Resp.(*discoverypb.DiscoveryResponse)); err != nil {
							retErr = err
							return
						}
					case <-s.Context().Done():
						retErr = s.Context().Err()
						return
					}
```

So if  s.Recv() does not return error or select blocks, errCh will be blocked forever.

**Comment by dfawley** [comment]
If you have ideas to fix this and the related issues, please feel free to propose them here, or send PRs.  If they are simple (do not over-complicate the code; e.g. adding a buffer to a channel), we will accept them.  But otherwise, these are very low priority for us, as they are all test bugs, and they can only occur after there has already been another failure in the test.
