### ISSUE TITLE
http2Server panic in TestServerStreamingConcurrent

### ISSUE THREAD

**Issue by charlesxsh** [grpc/grpc-go#5034]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?

9280052

### What version of Go are you using (`go version`)?
1.16.4

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
During our fuzzer testing, we found that TestServerStreamingConcurrent might encounter an interesting panic because of nil in `func (t *http2Server) deleteStream(s *Stream, eosReceived bool)`.

### What did you expect to see?
No panic

### What did you see instead?

```
=== RUN   TestServerStreamingConcurrent
    end2end_test.go:4211: Running test in tcp-clear-v1-balancer environment...
    end2end_test.go:4211: Running test in tcp-tls-v1-balancer environment...
    end2end_test.go:4211: Running test in tcp-clear environment...
    end2end_test.go:4211: Running test in tcp-tls environment...
    end2end_test.go:4211: Running test in handler-tls environment...
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4234: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    end2end_test.go:4211: Running test in no-balancer environment...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x861d31]

goroutine 910 [running]:
google.golang.org/grpc/internal/transport.(*http2Server).deleteStream(0xc0007a2f00, 0xc000351000, 0xb89c01)
	/fuzz/target/internal/transport/http2_server.go:1727 +0x51
google.golang.org/grpc/internal/transport.(*http2Server).finishStream.func1()
	/fuzz/target/internal/transport/http2_server.go:1763 +0x3b
google.golang.org/grpc/internal/transport.(*loopyWriter).cleanupStreamHandler(0xc000835800, 0xc000831638, 0xc000e12b90, 0x2)
	/fuzz/target/internal/transport/controlbuf.go:859 +0x56
google.golang.org/grpc/internal/transport.(*loopyWriter).headerHandler(0xc000835800, 0xc000e12be0, 0xc000910fd0, 0x1)
	/fuzz/target/internal/transport/controlbuf.go:748 +0x128
google.golang.org/grpc/internal/transport.(*loopyWriter).handle(0xc000835800, 0xa918e0, 0xc000e12be0, 0xc000e12be0, 0x0)
	/fuzz/target/internal/transport/controlbuf.go:916 +0x505
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000835800, 0x0, 0x0)
	/fuzz/target/internal/transport/controlbuf.go:644 +0xe5
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc0007a2f00)
	/fuzz/target/internal/transport/http2_server.go:293 +0xd7
created by google.golang.org/grpc/internal/transport.newHTTP2Server
	/fuzz/target/internal/transport/http2_server.go:290 +0x1130
FAIL	google.golang.org/grpc/test	30.077s
FAIL

```

**Comment by menghanl** [comment]
```
google.golang.org/grpc/internal/transport.(*http2Server).deleteStream(0xc0007a2f00, 0xc000351000, 0xb89c01)
	/fuzz/target/internal/transport/http2_server.go:1727 +0x51
```

Is the line number correct? `http2_server.go` doesn't have line 1727, and it's not clear which line caused the panic.

**Comment by songlh** [comment]
it should happens at `t.activeStreams` [line 1234](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L1234).
