### ISSUE TITLE
Flaky test: ClusterNameInAddressAttributes

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5173]
```
--- FAIL: Test (10.07s)
    --- FAIL: Test/ClusterNameInAddressAttributes (10.05s)
        tlogger.go:116: INFO clusterimpl.go:73 [xds] [xds-cluster-impl-lb 0xc000170900] Created  (t=+130.203µs)
        tlogger.go:116: INFO clusterimpl.go:224 [xds] [xds-cluster-impl-lb 0xc000170900] Received update from resolver, balancer config: {
              "cluster": "test-cluster",
              "edsServiceName": "test-eds-service",
              "childPolicy": [
                {
                  "round_robin": {}
                }
              ]
            }  (t=+274.205µs)
        balancer.go:113: testClientConn: NewSubConn([{1.1.1.1:1  0xc000010380 <nil> 0 <nil>}], {CredsBundle:<nil> HealthCheckEnabled:true}) => sc0
        balancer.go:147: testClientConn: UpdateState({CONNECTING 0xc00003cfa0})
        tlogger.go:116: INFO roundrobin.go:50 [roundrobin] roundrobinPicker: Build called with info: {map[0xc00014f8a0:{{1.1.1.1:1  <nil> <nil> 0 <nil>}}]}  (t=+514.41µs)
        balancer.go:147: testClientConn: UpdateState({READY 0xc00003d090})
        tlogger.go:116: INFO clusterimpl.go:224 [xds] [xds-cluster-impl-lb 0xc000170900] Received update from resolver, balancer config: {
              "cluster": "test-cluster-2",
              "edsServiceName": "test-eds-service",
              "childPolicy": [
                {
                  "round_robin": {}
                }
              ]
            }  (t=+1.198324ms)
        balancer.go:113: testClientConn: NewSubConn([{2.2.2.2  0xc000010440 <nil> 0 <nil>}], {CredsBundle:<nil> HealthCheckEnabled:true}) => sc1
        balancer.go:129: testClientConn: RemoveSubConn(sc0)
        tlogger.go:116: INFO clusterimpl.go:336 [xds] [xds-cluster-impl-lb 0xc000170900] Shutdown  (t=+1.364627ms)
        grpctest.go:39: Leaked goroutine: goroutine 82 [IO wait]:
            internal/poll.runtime_pollWait(0x7fe15f161030, 0x72)
            	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/netpoll.go:234 +0x89
            internal/poll.(*pollDesc).wait(0xc0000ea498, 0xc000254000, 0x0)
            	/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
            internal/poll.(*pollDesc).waitRead(...)
            	/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_poll_runtime.go:89
            internal/poll.(*FD).Read(0xc0000ea480, {0xc000254000, 0x1000, 0x1000})
            	/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_unix.go:167 +0x419
            net.(*netFD).Read(0xc0000ea480, {0xc000254000, 0x1000, 0x1000})
            	/opt/hostedtoolcache/go/1.17.6/x64/src/net/fd_posix.go:56 +0x51
            net.(*conn).Read(0xc00011e018, {0xc000254000, 0x1000, 0x1000})
            	/opt/hostedtoolcache/go/1.17.6/x64/src/net/net.go:183 +0xb1
            net/http.(*persistConn).Read(0xc0002d1320, {0xc000254000, 0x1000, 0x1000})
            	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/transport.go:1926 +0x110
            bufio.(*Reader).fill(0xc0003bc060)
            	/opt/hostedtoolcache/go/1.17.6/x64/src/bufio/bufio.go:101 +0x294
            bufio.(*Reader).Peek(0xc0003bc060, 0x1)
            	/opt/hostedtoolcache/go/1.17.6/x64/src/bufio/bufio.go:139 +0xcc
            net/http.(*persistConn).readLoop(0xc0002d1320)
            	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/transport.go:2087 +0x2db
            created by net/http.(*Transport).dialConn
            	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/transport.go:1747 +0x2ef8
        grpctest.go:39: Leaked goroutine: goroutine 83 [select]:
            net/http.(*persistConn).writeLoop(0xc0002d1320)
            	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/transport.go:2386 +0x1a9
            created by net/http.(*Transport).dialConn
            	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/transport.go:1748 +0x2f8b
        grpctest.go:60: Leak check disabled for future tests
FAIL
FAIL	google.golang.org/grpc/xds/internal/balancer/clusterimpl	10.152s
```

https://github.com/grpc/grpc-go/runs/4973396693?check_suite_focus=true

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/4974585008?check_suite_focus=true

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/4973378414?check_suite_focus=true

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/runs/4984097900?check_suite_focus=true

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/runs/5010151077?check_suite_focus=true

**Comment by dfawley** [comment]
#5171 has the same problem
