### ISSUE TITLE
Goroutine error when running HelloWorld xds example

### ISSUE THREAD

**Issue by palade** [grpc/grpc-go#5188]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
1.44.0

### What version of Go are you using (`go version`)?
1.17

### What operating system (Linux, Windows, …) and version?
Same on both

### What did you do?
If possible, provide a recipe for reproducing the error.

Any hello world xds

### What did you expect to see?

my echo message

### What did you see instead?

```
2022/02/08 09:43:03 INFO: [core] original dial target is: "xds:///localhost:30051"
2022/02/08 09:43:03 INFO: [core] parsed dial target is: {Scheme:xds Authority: Endpoint:localhost:30051 URL:{Scheme:xds Opaque: User: Host: Path:/localhost:30051 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}
2022/02/08 09:43:03 INFO: [core] Channel authority set to "localhost:30051"
2022/02/08 09:43:03 INFO: [xds] [xds-resolver 0xc00035a000] Creating resolver for target: {Scheme:xds Authority: Endpoint:localhost:30051 URL:{Scheme:xds Opaque: User: Host: Path:/localhost:30051 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}
2022/02/08 09:43:03 INFO: [xds] [xds-bootstrap] xds: using bootstrap file with name "C:\\GolandProjects\\xDSworks\\app\\src\\xds_bootstrap.json"
2022/02/08 09:43:03 INFO: [xds] [xds-bootstrap] Bootstrap content: {
  "xds_servers": [
    {
      "server_uri": "xds:///localhost:50051",
      "channel_creds": [
        {
          "type": "insecure"
        }
      ]
    }
  ],
  "node": {
    "id": "b7f9c818-fb46-43ca-8662-d3bdbcf7ec18~10.0.0.1",
    "metadata": {
      "R_GCP_PROJECT_NUMBER": "123456789012"
    },
    "locality": {
      "zone": "us-central1-a"
    }
  }
}
2022/02/08 09:43:03 INFO: [xds] [xds-bootstrap] Bootstrap config for creating xds-client: {
  "XDSServer": {
    "ServerURI": "xds:///localhost:50051",
    "Creds": {},
    "CredsType": "insecure",
    "TransportAPI": 0,
    "NodeProto": {
      "id": "b7f9c818-fb46-43ca-8662-d3bdbcf7ec18~10.0.0.1",
      "metadata": {
        "R_GCP_PROJECT_NUMBER": "123456789012"
      },
      "locality": {
        "zone": "us-central1-a"
      },
      "build_version": "gRPC Go 1.44.1-dev",
      "user_agent_name": "gRPC Go",
      "UserAgentVersionType": {
        "UserAgentVersion": "1.44.1-dev"
      },
      "client_features": [
        "envoy.lb.does_not_support_overprovisioning"
      ]
    }
  },
  "CertProviderConfigs": null,
  "ServerListenerResourceNameTemplate": "",
  "ClientDefaultListenerResourceNameTemplate": "%s",
  "Authorities": null
}
2022/02/08 09:43:03 INFO: [xds] [xds-client 0xc000329840] Created ClientConn to xDS management server: xds:///localhost:50051-insecure-xDSv2
2022/02/08 09:43:03 INFO: [xds] [xds-client 0xc000329840] Created
2022/02/08 09:43:03 INFO: [core] original dial target is: "xds:///localhost:50051"
2022/02/08 09:43:03 INFO: [core] parsed dial target is: {Scheme:xds Authority: Endpoint:localhost:50051 URL:{Scheme:xds Opaque: User: Host: Path:/localhost:50051 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}
2022/02/08 09:43:03 INFO: [core] Channel authority set to "localhost:50051"
2022/02/08 09:43:03 INFO: [xds] [xds-resolver 0xc00035b200] Creating resolver for target: {Scheme:xds Authority: Endpoint:localhost:50051 URL:{Scheme:xds Opaque: User: Host: Path:/localhost:50051 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0x58, 0x28, 0x60)
	C:/Users//sdk/go1.17.3/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000329850)
	C:/Users//sdk/go1.17.3/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	C:/Users//sdk/go1.17.3/src/sync/mutex.go:81
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).findAuthority(0xc000329840, 0xc00048fda8)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/authority.go:45 +0xa8
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).WatchListener(0x6ad507, {0xc0003fbb40, 0xf30720}, 0xc00006fa30)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/watchers.go:31 +0x58
google.golang.org/grpc/xds/internal/resolver.watchService({0x11ba618, 0x19dd8c0}, {0xc0003fbb40, 0xf}, 0xc00006fa20, 0xc000313040)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/resolver/watch_service.go:68 +0x12e
google.golang.org/grpc/xds/internal/resolver.(*xdsResolverBuilder).Build(0xc000006028, {{0xc000314090, 0x3}, {0xc000314096, 0x0}, {0xc000314097, 0xf}, {{0xc000314090, 0x3}, {0x0, ...}, ...}}, ...)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/resolver/xds_resolver.go:138 +0x751
google.golang.org/grpc.newCCResolverWrapper(0xc00072cf00, {0x119b4b0, 0xc000006028})
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/resolver_conn_wrapper.go:72 +0x2de
google.golang.org/grpc.DialContext({0x11aa950, 0xc00009e010}, {0xc000314090, 0x16}, {0xc000490d30, 0x2, 0x90})
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/clientconn.go:295 +0x1389
google.golang.org/grpc.Dial(...)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/clientconn.go:105
google.golang.org/grpc/xds/internal/xdsclient/controller.New(0xc00007c0a0, {0x11b0c38, 0xc0001483f0}, 0xc00006f840, 0xc000038501)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/controller/controller.go:133 +0x3d2
google.golang.org/grpc/xds/internal/xdsclient.glob..func1(0x37e11d600, 0xc000312ee0, 0xc000490e28, 0x25)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/controller.go:37 +0x29
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).newAuthority(0xc000329840, 0xc00007c0a0)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/authority.go:110 +0x26c
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).findAuthority(0xc000329840, 0xc000490fd8)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/authority.go:60 +0x217
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).WatchListener(0x6ad507, {0xc0003fba30, 0xf30720}, 0xc00006f810)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/watchers.go:31 +0x58
google.golang.org/grpc/xds/internal/resolver.watchService({0x11ba618, 0x19dd8c0}, {0xc0003fba30, 0xf}, 0xc00006f800, 0xc000312280)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/resolver/watch_service.go:68 +0x12e
google.golang.org/grpc/xds/internal/resolver.(*xdsResolverBuilder).Build(0xc000006028, {{0x108dcae, 0x3}, {0x108dcb4, 0x0}, {0x108dcb5, 0xf}, {{0x108dcae, 0x3}, {0x0, ...}, ...}}, ...)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/resolver/xds_resolver.go:138 +0x751
google.golang.org/grpc.newCCResolverWrapper(0xc00072c000, {0x119b4b0, 0xc000006028})
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/resolver_conn_wrapper.go:72 +0x2de
google.golang.org/grpc.DialContext({0x11aa950, 0xc00009e010}, {0x108dcae, 0x16}, {0xc000491f20, 0x1, 0x11})
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/clientconn.go:295 +0x1389
google.golang.org/grpc.Dial(...)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/clientconn.go:105
main.main()
	C:/Users//GolandProjects/xDSworks/app/src/grpc_client.go:41 +0x21d

goroutine 35 [select]:
google.golang.org/grpc/xds/internal/xdsclient/pubsub.(*Pubsub).run(0xc0001483f0)
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/pubsub/pubsub.go:171 +0x8c
created by google.golang.org/grpc/xds/internal/xdsclient/pubsub.New
	C:/Users//go/pkg/mod/google.golang.org/grpc@v1.44.0/xds/internal/xdsclient/pubsub/pubsub.go:83 +0x35b
```

**Comment by easwars** [comment]
Looks like the original dial target is: `xds:///localhost:30051`, and the xDS server specified in the bootstrap file is `xds:///localhost:50051`. 

@palade : Was this intentional to use an `xds` scheme for the connection to the xDS server? One cannot use the `xds:///` scheme to connect to the xDS server.

@menghanl : Should we (can we) handle this better instead of deadlocking? While parsing the bootstrap file, can we error out if we find an unsupported scheme (I guess we can support everything other than `xds:///`) to the xDS server?

**Comment by palade** [comment]
@easwars  thank you for your reply. This is a simple hello world setup as I'm learning about how xDS is used. I fixed the errors below but now there is a different issue that I'm experiencing.

> Looks like the original dial target is: xds:///localhost:30051, and the xDS server specified in the bootstrap file is xds:///localhost:50051.

Fixed this in the code as well. 

A question about the expected workflow in the xDS case:
- gRPC client connects to the xDS server which returns some endpoints
- gRPC client uses that endpoint to open another connection to the gRPC server.

> @palade : Was this intentional to use an xds scheme for the connection to the xDS server? One cannot use the xds:/// scheme to connect to the xDS server.

@easwars Thank you for pointing out this. I removed the `xds:///` from the bootstrap file.
