### ISSUE TITLE
xds : Nil pointer dereference error

### ISSUE THREAD

**Issue by srinidhis94** [grpc/grpc-go#5333]
### What version of gRPC are you using?
1.46.0

### What version of Go are you using (`go version`)?
1.18

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Using xds as client side loadbalancer for GCP traffic director service.

`_ "google.golang.org/grpc/xds"`

We're seeing this in production environment and service is clashing.

### What did you expect to see?
client work normal and was not expecting to crash.

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x406331]

goroutine 1899 [running]:
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).newAuthority(0xc000762d40, 0xc0022ae410)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/xdsclient/authority.go:89 +0x93
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).ReportLoad(0xc000762d40, 0xc0022ae410)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/xdsclient/loadreport.go:31 +0x2a
google.golang.org/grpc/xds/internal/balancer/clusterimpl.(*clusterImplBalancer).updateLoadStore(0xc000ac4000, 0xc00219a420)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/clusterimpl/clusterimpl.go:210 +0x2b0
google.golang.org/grpc/xds/internal/balancer/clusterimpl.(*clusterImplBalancer).UpdateClientConnState(0xc000ac4000, {{{0xc001c78c60, 0x2, 0x2}, 0x0, 0xc0022060d8}, {0x1cad880, 0xc00219a420}})
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/clusterimpl/clusterimpl.go:250 +0x2cb
google.golang.org/grpc/internal/balancer/gracefulswitch.(*Balancer).UpdateClientConnState(0x164aea0?, {{{0xc001c78c60, 0x2, 0x2}, 0x0, 0xc0022060d8}, {0x1cad880, 0xc00219a420}})
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/balancer/gracefulswitch/gracefulswitch.go:164 +0x82
google.golang.org/grpc/internal/balancergroup.(*subBalancerWrapper).updateClientConnState(...)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/balancergroup/balancergroup.go:144
google.golang.org/grpc/internal/balancergroup.(*BalancerGroup).UpdateClientConnState(0xc0027a7540?, {0xc0010c64e0?, 0xc12397?}, {{{0xc001c78c60, 0x2, 0x2}, 0x0, 0xc0022060d8}, {0x1cad880, 0xc00219a420}})
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/balancergroup/balancergroup.go:453 +0x1be
google.golang.org/grpc/xds/internal/balancer/priority.(*childBalancer).sendUpdate(0xc002250680)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/priority/balancer_child.go:88 +0xf7
google.golang.org/grpc/xds/internal/balancer/priority.(*priorityBalancer).syncPriority(0xc002250100)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/priority/balancer_priority.go:101 +0x346
google.golang.org/grpc/xds/internal/balancer/priority.(*priorityBalancer).UpdateClientConnState(0xc002250100, {{{0xc001c78630, 0x2, 0x2}, 0x0, 0xc0022060d8}, {0x1cad940, 0xc002589380}})
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/priority/balancer.go:179 +0xa2b
google.golang.org/grpc/xds/internal/balancer/clusterresolver.(*clusterResolverBalancer).updateChildConfig(0xc000686000)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/clusterresolver/clusterresolver.go:224 +0x333
google.golang.org/grpc/xds/internal/balancer/clusterresolver.(*clusterResolverBalancer).handleWatchUpdate(0xc000686000, 0xc002588fc0)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/clusterresolver/clusterresolver.go:198 +0x198
google.golang.org/grpc/xds/internal/balancer/clusterresolver.(*clusterResolverBalancer).run(0xc000686000)
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/clusterresolver/clusterresolver.go:299 +0x2ae
created by google.golang.org/grpc/xds/internal/balancer/clusterresolver.bb.Build
        /workspace/go/pkg/mod/google.golang.org/grpc@v1.46.0/xds/internal/balancer/clusterresolver/clusterresolver.go:89 +0x54a
```

**Comment by easwars** [comment]
@srinidhis94 : Thank you for reporting this issue and apologies for the delay in getting back to you.

Could you please provide us with some more information:
- is this happening all the time or was this a one time occurrence?
- did this happen when the client was starting out? 
  - If not, what was happening in the client around the time this crash happened?
  - would it be possible for you to enable grpc logging on the crashing client and provide us with the logs
- possible minimal setup to reproduce this?

Thank you.
