### ISSUE TITLE
xds: resolver deadlock upon receipt of new style resource name with unknown authority

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5429]
I wrote a test where the management server pushes a `Listener` resource with a `RouteConfigName` which uses the new style resource name and contains an authority which is not present in the bootstrap config of the gRPC application.

<details>
  <summary>Interesting goroutines from the goroutine dump at deadlock</summary>

```
goroutine 434 [semacquire]:
sync.runtime_SemacquireMutex(0x1052389?, 0xf8?, 0x10dc02a?)
        /Users/easwars/homebrew/opt/go/libexec/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00096a7b8)
        /Users/easwars/homebrew/opt/go/libexec/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
        /Users/easwars/homebrew/opt/go/libexec/src/sync/mutex.go:81
google.golang.org/grpc/xds/internal/resolver.(*serviceUpdateWatcher).close(0xc00096a750)
        /Users/easwars/src/grpc-go/xds/internal/resolver/watch_service.go:195 +0x52
google.golang.org/grpc/xds/internal/resolver.(*xdsResolverBuilder).Build.func2()
        /Users/easwars/src/grpc-go/xds/internal/resolver/xds_resolver.go:142 +0x2a
google.golang.org/grpc/xds/internal/resolver.(*xdsResolver).Close(0xc000594cc0)
        /Users/easwars/src/grpc-go/xds/internal/resolver/xds_resolver.go:308 +0x2a
google.golang.org/grpc.(*ccResolverWrapper).close(0xc000594c00)
        /Users/easwars/src/grpc-go/resolver_conn_wrapper.go:89 +0x58
google.golang.org/grpc.(*ClientConn).Close(0xc0007ba000)
        /Users/easwars/src/grpc-go/clientconn.go:1040 +0x15e
runtime.Goexit()
        /Users/easwars/homebrew/opt/go/libexec/src/runtime/panic.go:482 +0x177
testing.(*common).FailNow(0xc000b2e1a0)
        /Users/easwars/homebrew/opt/go/libexec/src/testing/testing.go:864 +0x4c
testing.(*common).Fatalf(0xc000b2e1a0, {0x1d277e1?, 0xc0005947e0?}, {0xc000aa55d8?, 0xc000319670?, 0x1?})
        /Users/easwars/homebrew/opt/go/libexec/src/testing/testing.go:948 +0x65
google.golang.org/grpc/test/xds_test.s.TestFederation_UnknownAuthorityInReceivedResponse({{}}, 0xc000b2e1a0)
        /Users/easwars/src/grpc-go/test/xds/xds_client_federation_test.go:247 +0xc8d
google.golang.org/grpc/internal/grpctest.RunSubTests.func1(0xc000b2e1a0)
        /Users/easwars/src/grpc-go/internal/grpctest/grpctest.go:107 +0xb3
testing.tRunner(0xc000b2e1a0, 0xc0006507e0)
        /Users/easwars/homebrew/opt/go/libexec/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /Users/easwars/homebrew/opt/go/libexec/src/testing/testing.go:1486 +0x35f

goroutine 450 [semacquire]:
sync.runtime_SemacquireMutex(0xa4?, 0x0?, 0x100c7ab?)
        /Users/easwars/homebrew/opt/go/libexec/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00096a7b8)
        /Users/easwars/homebrew/opt/go/libexec/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
        /Users/easwars/homebrew/opt/go/libexec/src/sync/mutex.go:81
google.golang.org/grpc/xds/internal/resolver.(*serviceUpdateWatcher).handleRDSResp(0xc00096a750, {{0x0, 0x0, 0x0}, 0x0, 0x0}, {0x1e5d3e0?, 0xc0003be510})
        /Users/easwars/src/grpc-go/xds/internal/resolver/watch_service.go:177 +0x179
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).WatchRouteConfig(0xc000124940?, {0xc000f6d030?, 0x1e78968?}, 0xc0003be500)
        /Users/easwars/src/grpc-go/xds/internal/xdsclient/watchers.go:52 +0xfc
google.golang.org/grpc/xds/internal/resolver.(*serviceUpdateWatcher).handleLDSResp(0xc00096a750, {{0xc000f6d030, 0x64}, 0x0, 0x0, {0xc000944c90, 0x1, 0x1}, 0x0, 0xc0007509b0}, ...)
        /Users/easwars/src/grpc-go/xds/internal/resolver/watch_service.go:159 +0x58f
google.golang.org/grpc/xds/internal/xdsclient/pubsub.(*Pubsub).callCallback.func1()
        /Users/easwars/src/grpc-go/xds/internal/xdsclient/pubsub/update.go:55 +0xfa
google.golang.org/grpc/xds/internal/xdsclient/pubsub.(*Pubsub).callCallback(0xc000ac6640, 0xc000944cc0)
        /Users/easwars/src/grpc-go/xds/internal/xdsclient/pubsub/update.go:73 +0x2c2
google.golang.org/grpc/xds/internal/xdsclient/pubsub.(*Pubsub).run(0xc000ac6640)
        /Users/easwars/src/grpc-go/xds/internal/xdsclient/pubsub/pubsub.go:183 +0x2c
created by google.golang.org/grpc/xds/internal/xdsclient/pubsub.New
        /Users/easwars/src/grpc-go/xds/internal/xdsclient/pubsub/pubsub.go:89 +0x3f6
```
</details>

**Comment by easwars** [comment]
It looks like goroutine 450 from the above log is blocked on the mutex when handling an RDS response. https://github.com/grpc/grpc-go/blob/c0198a9ce33b0755079e4cdae7f2315af2ebe993/xds/internal/resolver/watch_service.go#L177

While goroutine 434 is blocked on the same mutex when closing the `xds_resolver`. The close is triggered from `ClientConn.Close()` because the test attempts to the close the `ClientConn` after unsuccessfully waiting for an RPC to complete.

The question to be asked here though is why does goroutine 450 not get the lock?

**Comment by easwars** [comment]
I think this is what is happening:

As part of handling the LDS response, the `serviceUpdateWatcher` registers a watch for the RDS resource by calling `WatchRouteConfig` on the `xdsClient`. The mutex is held at this point in time.
https://github.com/grpc/grpc-go/blob/c0198a9ce33b0755079e4cdae7f2315af2ebe993/xds/internal/resolver/watch_service.go#L159

`xdsClient.WatchRouteConfig` attempts to find the configuration for the authority specified in the resource name. Since, the authority is an unknown one, it calls back the provided callback with an error inline.
https://github.com/grpc/grpc-go/blob/c0198a9ce33b0755079e4cdae7f2315af2ebe993/xds/internal/xdsclient/watchers.go#L52

This leads to `handleRDSResponse` being invoked (this is the registered callback). This attempts to grap the lock and hence the deadlock.
https://github.com/grpc/grpc-go/blob/c0198a9ce33b0755079e4cdae7f2315af2ebe993/xds/internal/resolver/watch_service.go#L177

This is also seen in the following stack frames of goroutine 450:
```
google.golang.org/grpc/xds/internal/resolver.(*serviceUpdateWatcher).handleRDSResp(0xc00096a750, {{0x0, 0x0, 0x0}, 0x0, 0x0}, {0x1e5d3e0?, 0xc0003be510})
        /Users/easwars/src/grpc-go/xds/internal/resolver/watch_service.go:177 +0x179
google.golang.org/grpc/xds/internal/xdsclient.(*clientImpl).WatchRouteConfig(0xc000124940?, {0xc000f6d030?, 0x1e78968?}, 0xc0003be500)
        /Users/easwars/src/grpc-go/xds/internal/xdsclient/watchers.go:52 +0xfc
google.golang.org/grpc/xds/internal/resolver.(*serviceUpdateWatcher).handleLDSResp(0xc00096a750, {{0xc000f6d030, 0x64}, 0x0, 0x0, {0xc000944c90, 0x1, 0x1}, 0x0, 0xc0007509b0}, ...)
        /Users/easwars/src/grpc-go/xds/internal/resolver/watch_service.go:159 +0x58f
```
