### ISSUE TITLE
grpc reflection error for import is not defined

### ISSUE THREAD

**Issue by Ja7ad** [grpc/grpc-go#5572]
grpc reflection error for `paginatedList.list.Response` is not defined, but `paginatedList.list.Response` imported from another proto file.

### What version of gRPC are you using?

google.golang.org/grpc v1.48.0

### What version of Go are you using (`go version`)?

1.18.1

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?
I want use server reflection but got error on grpc client (kreya and postman)

### What did you expect to see?

I want access to server rpc path for test service

### What did you see instead?

```
{
  "kreyaVersion": "1.8.0",
  "platform": "Linux x86_64",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
}

Google.Protobuf.Reflection.DescriptorValidationException: application.GetPaginatedApplicationsResponse.response: ".paginatedList.list.Response" is not defined.
   at Google.Protobuf.Reflection.DescriptorPool.LookupSymbol(String name, IDescriptor relativeTo)
   at Google.Protobuf.Reflection.FieldDescriptor.CrossLink()
   at Google.Protobuf.Reflection.MessageDescriptor.CrossLink()
   at Google.Protobuf.Reflection.FileDescriptor.CrossLink()
   at Google.Protobuf.Reflection.FileDescriptor.BuildFromByteStrings(IEnumerable`1 descriptorData, ExtensionRegistry registry)
   at Google.Protobuf.Reflection.FileDescriptor.BuildFromByteStrings(IEnumerable`1 descriptorData)
   at Kreya.Grpc.Core.Importer.ProtoRegistry.Add(Guid sourceId, IEnumerable`1 byteStrings)
   at Kreya.Grpc.Core.Importer.BaseGrpcImporter`1.Import(IImportStream`1 importStream, Boolean allowCache)
   at Kreya.Core.Importer.ImporterService.RunSingleImporter(ImportStream importStream, Boolean allowCache, IReadOnlyDictionary`2 operationsByInvoker)
   at Kreya.Core.Importer.ImporterService.RunImporter(Guid id, Boolean allowCache)
   at SpiderEye.Bridge.ApiMethod.InvokeAsync(Object instance, Object parameter)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.InvokeWithDependencyInjection(IDependencyInjectionApiMethod apiMethod, Object parameters)
   at SpiderEye.Bridge.WebviewBridge.ResolveCall(String id, String parameters)
```

**Comment by easwars** [comment]
The stack trace listed here seems to from a java server. Why is this a Go issue? Could you please provide more information if you think this is still a Go issue.

**Comment by Ja7ad** [comment]
> The stack trace listed here seems to from a java server. Why is this a Go issue? Could you please provide more information if you think this is still a Go issue.

This is stack trace kreya grpc client.

```
Google.Protobuf.Reflection.DescriptorValidationException: application.GetPaginatedApplicationsResponse.response: ".paginatedList.list.Response" is not defined.
```
I import `paginatedList.list.Response` from another proto file, but grpc reflection say is not defined
