### ISSUE TITLE
Flaky test: CustomTagsTracingMetrics

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5595]
```
panic: Log in goroutine after Test/CustomTagsTracingMetrics has completed: Metrics[grpc.io/server/completed_rpcs]

goroutine 6 [running]:
testing.(*common).logDepth(0x40002ea1a0, {0x4000268120, 0x26}, 0x3)
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:887 +0x3d4
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:869
testing.(*common).Logf(0x40002ea1a0, {0x8a0ae7?, 0x40002e16c0?}, {0x4000080d60?, 0xffffffffffffffff?, 0x0?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:920 +0x5c
google.golang.org/grpc/gcp/observability.(*fakeOpenCensusExporter).ExportView(0x40004567b0, 0x40001e2000)
	/home/runner/work/grpc-go/grpc-go/gcp/observability/observability_test.go:369 +0x100
go.opencensus.io/stats/view.(*worker).reportView(0x400016a080, 0x400007a620)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:357 +0x204
go.opencensus.io/stats/view.(*worker).reportUsage(0x400016a080)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:365 +0xac
go.opencensus.io/stats/view.(*worker).start(0x400016a080)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:280 +0xbc
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xa8
FAIL	google.golang.org/grpc/gcp/observability	0.812s
?   	google.golang.org/grpc/gcp/observability/internal/logging	[no test files]
FAIL
```

https://github.com/grpc/grpc-go/runs/7908305648?check_suite_focus=true

**Comment by zasweq** [comment]
This is orthogonal to my test, and happened to occur in the time period that my test. This is due to his fakeOpenCensusExporter being left over from his test globally without cleaning it up. This fakeOpenCensusExporter persists a testing.T from a test that already completed, and future calls into globally persisted exporter try and log on this testing.T from new tests. This will be hopefully be fixed along with the other observability flakes, as they are all the same root cause I believe.

**Comment by dfawley** [comment]
#5423 should cover this.
