### ISSUE TITLE
evictCount  

### ISSUE THREAD

**Issue by ben-swit** [grpc/grpc-go#5610]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?

1.48.0

### What version of Go are you using (`go version`)?
1.18 | 1.17

### What operating system (Linux, Windows, …) and version?
llinux alpine 3.14

### What did you do?
If possible, provide a recipe for reproducing the error.
```
panic: id (33) <= evictCount (34)

goroutine 193 [running]:
golang.org/x/net/http2/hpack.(*headerFieldTable).idToIndex(0xc000a89a80, 0xc0009cf4a0?)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/tables.go:119 +0xce
golang.org/x/net/http2/hpack.(*headerFieldTable).search(0xc000a89a80, {{0xc00097f340, 0xc}, {0xc0016b0540, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/tables.go:106 +0xe5
golang.org/x/net/http2/hpack.(*Encoder).searchTable(0xc000a89a80, {{0xc00097f340, 0xc}, {0xc0016b0540, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/encode.go:97 +0x88
golang.org/x/net/http2/hpack.(*Encoder).WriteField(0xc000a89a80, {{0xc00097f340, 0xc}, {0xc0016b0540, 0x24}, 0x0})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220708220712-1185a9018129/http2/hpack/encode.go:62 +0x14a
google.golang.org/grpc/internal/transport.(*loopyWriter).writeHeader(0xc000a3a3c0, 0x9b, 0x0, {0xc000edcd80?, 0x8, 0xc000f4de68?}, 0x424207?)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:684 +0x32a
google.golang.org/grpc/internal/transport.(*loopyWriter).originateStream(0xc000a3a3c0, 0xc001389040)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:671 +0x185
google.golang.org/grpc/internal/transport.(*loopyWriter).headerHandler(0xc000a3a3c0, 0xc000effa40)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:659 +0x394
google.golang.org/grpc/internal/transport.(*loopyWriter).handle(0xc0003a1770?, {0x1375980?, 0xc000effa40?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:831 +0x3e5
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000a3a3c0)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/controlbuf.go:539 +0x9e
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/http2_client.go:415 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/internal/transport/http2_client.go:413 +0x1eb1
```

**Comment by dfawley** [comment]
Please file a new issue and ensure the template is properly filled out, especially the sections:


### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you expect to see?

### What did you see instead?
