### ISSUE TITLE
panic: grpc: Unexpected error (*errors.errorString) from recvMsg: client disconnected

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#582]
Found in https://circleci.com/gh/cockroachdb/cockroach/13629. Full log https://circle-artifacts.com/gh/cockroachdb/cockroach/13629/artifacts/1/tmp/circle-artifacts.pZZ4UqS/testrace.log (search for `panic: grpc: Unexpected error`).

```
panic: grpc: Unexpected error (*errors.errorString) from recvMsg: client disconnected

goroutine 9233 [running]:
google.golang.org/grpc.(*Server).processUnaryRPC(0xc8205e5e80, 0x7fca8b4b1d58, 0xc8202b1ce0, 0xc8208381c0, 0xc8208e1660, 0x26dd520, 0xc8202acba0, 0x0, 0x0)
    /go/src/google.golang.org/grpc/server.go:465 +0x8cd
google.golang.org/grpc.(*Server).handleStream(0xc8205e5e80, 0x7fca8b4b1d58, 0xc8202b1ce0, 0xc8208381c0, 0xc8202acba0)
    /go/src/google.golang.org/grpc/server.go:654 +0x1419
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc8209662e0, 0xc8205e5e80, 0x7fca8b4b1d58, 0xc8202b1ce0, 0xc8208381c0)
    /go/src/google.golang.org/grpc/server.go:323 +0xae
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /go/src/google.golang.org/grpc/server.go:324 +0xa8
```

**Comment by iamqizhao** [comment]
This uses grpc.Serve or grpc.ServeHTTP?

**Comment by tamird** [comment]
`grpc.(*Server).ServeHTTP`

**Comment by iamqizhao** [comment]
assigned to @bradfitz. I need to be on something else today.

**Comment by hsaliak** [comment]
@tamird sorry for not picking this one up, are you folks still seeing this error from time to time?

**Comment by tamird** [comment]
I don't think we've seen it in some time.
