### ISSUE TITLE
Flaky Test: Test/InvalidFirstResponse

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#5829]
https://github.com/grpc/grpc-go/actions/runs/3587236614/jobs/6037352806

```
    --- FAIL: Test/InvalidFirstResponse (10.04s)
        tlogger.go:116: INFO server.go:113 [xds-e2e] Created new snapshot cache...  (t=+41.801µs)
        tlogger.go:116: INFO server.go:631 [core] [Server #116] Server created  (t=+528.61µs)
        tlogger.go:116: INFO server.go:144 [xds-e2e] Registered Aggregated Discovery Service (ADS)...  (t=+592.011µs)
        tlogger.go:116: INFO server.go:148 [xds-e2e] xDS management server serving at: 127.0.0.1:39653...  (t=+649.412µs)
        transport_ack_nack_test.go:282: Started xDS management server on 127.0.0.1:39653
        tlogger.go:116: INFO server.go:819 [core] [Server #116 ListenSocket #117] ListenSocket created  (t=+818.015µs)
        tlogger.go:116: INFO server.go:198 [xds-e2e] Created new resource snapshot...  (t=+931.417µs)
        tlogger.go:116: INFO server.go:204 [xds-e2e] Updated snapshot cache with resource snapshot...  (t=+977.717µs)
        tlogger.go:116: INFO clientconn.go:105 [core] [Channel #118] Channel created  (t=+1.035618ms)
        tlogger.go:116: INFO clientconn.go:1553 [core] [Channel #118] original dial target is: "127.0.0.1:39653"  (t=+1.074319ms)
        tlogger.go:116: INFO clientconn.go:1558 [core] [Channel #118] dial target "127.0.0.1:39653" parse failed: parse "127.0.0.1:39653": first path segment in URL cannot contain colon  (t=+1.14982ms)
        tlogger.go:116: INFO clientconn.go:1573 [core] [Channel #118] fallback to scheme "passthrough"  (t=+1.187221ms)
        tlogger.go:116: INFO clientconn.go:1581 [core] [Channel #118] parsed dial target is: {Scheme:passthrough Authority: Endpoint:127.0.0.1:39653 URL:{Scheme:passthrough Opaque: User: Host: Path:/127.0.0.1:39653 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+1.254922ms)
        tlogger.go:116: INFO clientconn.go:263 [core] [Channel #118] Channel authority set to "127.0.0.1:39653"  (t=+1.298123ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:175 [core] [Channel #118] Resolver state updated: {
              "Addresses": [
                {
                  "Addr": "127.0.0.1:39653",
                  "ServerName": "",
                  "Attributes": null,
                  "BalancerAttributes": null,
                  "Type": 0,
                  "Metadata": null
                }
              ],
              "ServiceConfig": null,
              "Attributes": null
            } (resolver returned new addresses)  (t=+1.455826ms)
        tlogger.go:116: INFO balancer_conn_wrappers.go:274 [core] [Channel #118] Channel switches to new LB policy "pick_first"  (t=+1.557827ms)
        tlogger.go:116: INFO clientconn.go:725 [core] [Channel #118 SubChannel #119] Subchannel created  (t=+1.645829ms)
        tlogger.go:116: INFO clientconn.go:418 [core] [Channel #118] Channel Connectivity change to CONNECTING  (t=+1.70373ms)
        tlogger.go:116: INFO transport.go:217 Created transport to server "127.0.0.1:39653"  (t=+1.790231ms)
        tlogger.go:116: INFO clientconn.go:1106 [core] [Channel #118 SubChannel #119] Subchannel Connectivity change to CONNECTING  (t=+1.938634ms)
        tlogger.go:116: INFO clientconn.go:1217 [core] [Channel #118 SubChannel #119] Subchannel picks a new address "127.0.0.1:39653" to connect  (t=+2.020435ms)
        tlogger.go:116: INFO clientconn.go:1106 [core] [Channel #118 SubChannel #119] Subchannel Connectivity change to READY  (t=+2.770848ms)
        tlogger.go:116: INFO clientconn.go:418 [core] [Channel #118] Channel Connectivity change to READY  (t=+2.85205ms)
        tlogger.go:116: INFO transport.go:316 ADS stream created  (t=+2.930151ms)
        tlogger.go:116: INFO simple.go:354 [xds-e2e] nodeID "b088c247-49d8-4ecd-b183-76dc5ba693c3" requested type.googleapis.com/envoy.config.listener.v3.Listener[resource name 1] and known map[]. Diff [resource name 1]  (t=+3.728165ms)
        tlogger.go:116: INFO simple.go:421 [xds-e2e] respond type.googleapis.com/envoy.config.listener.v3.Listener[resource name 1] version "" with version "1"  (t=+3.779166ms)
        tlogger.go:116: INFO transport.go:281 ADS response received, type: type.googleapis.com/envoy.config.listener.v3.Listener  (t=+4.138972ms)
        tlogger.go:116: WARNING transport.go:460 Sending NACK for resource type: type.googleapis.com/envoy.config.listener.v3.Listener, version: 1, nonce: 1, reason: unsupported field 'use_original_dst' is present and set to true  (t=+4.952886ms)
        tlogger.go:116: INFO simple.go:354 [xds-e2e] nodeID "b088c247-49d8-4ecd-b183-76dc5ba693c3" requested type.googleapis.com/envoy.config.listener.v3.Listener[resource name 1] and known map[resource name 1:{}]. Diff []  (t=+5.291892ms)
        tlogger.go:116: INFO simple.go:421 [xds-e2e] respond type.googleapis.com/envoy.config.listener.v3.Listener[resource name 1] version "" with version "1"  (t=+5.354793ms)
        tlogger.go:116: INFO transport.go:281 ADS response received, type: type.googleapis.com/envoy.config.listener.v3.Listener  (t=+5.582997ms)
        tlogger.go:116: WARNING transport.go:460 Sending NACK for resource type: type.googleapis.com/envoy.config.listener.v3.Listener, version: 1, nonce: 2, reason: unsupported field 'use_original_dst' is present and set to true  (t=+6.273509ms)
        tlogger.go:116: INFO simple.go:354 [xds-e2e] nodeID "b088c247-49d8-4ecd-b183-76dc5ba693c3" requested type.googleapis.com/envoy.config.listener.v3.Listener[resource name 1] and known map[resource name 1:{}]. Diff []  (t=+6.579314ms)
        tlogger.go:116: INFO simple.go:421 [xds-e2e] respond type.googleapis.com/envoy.config.listener.v3.Listener[resource name 1] version "" with version "1"  (t=+6.632915ms)
        tlogger.go:116: INFO transport.go:281 ADS response received, type: type.googleapis.com/envoy.config.listener.v3.Listener  (t=+6.856319ms)
        tlogger.go:116: WARNING transport.go:460 Sending NACK for resource type: type.googleapis.com/envoy.config.listener.v3.Listener, version: 1, nonce: 3, reason: unsupported field 'use_original_dst' is present and set to true  (t=+7.376928ms)
        tlogger.go:116: WARNING transport.go:433 ADS stream is closed with error: failed to read ADS response: rpc error: code = Canceled desc = context canceled  (t=+7.822136ms)
        tlogger.go:116: INFO clientconn.go:418 [core] [Channel #118] Channel Connectivity change to SHUTDOWN  (t=+7.879837ms)
        tlogger.go:116: INFO clientconn.go:1106 [core] [Channel #118 SubChannel #119] Subchannel Connectivity change to SHUTDOWN  (t=+7.944938ms)
        tlogger.go:116: INFO clientconn.go:1431 [core] [Channel #118 SubChannel #119] Subchannel deleted  (t=+7.989239ms)
        tlogger.go:116: INFO clientconn.go:1061 [core] [Channel #118] Channel deleted  (t=+8.017339ms)
        tlogger.go:116: INFO server.go:770 [core] [Server #116 ListenSocket #117] ListenSocket deleted  (t=+8.115741ms)
        grpctest.go:39: Leaked goroutine: goroutine 602 [semacquire]:
            sync.runtime_Semacquire(0xc000214128?)
            	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/sema.go:62 +0x25
            sync.(*WaitGroup).Wait(0xc000214120)
            	/opt/hostedtoolcache/go/1.19.3/x64/src/sync/waitgroup.go:139 +0xa6
            google.golang.org/grpc.(*Server).serveStreams(0xc000223680, {0x16dfd38?, 0xc000810680})
            	/home/runner/work/grpc-go/grpc-go/server.go:975 +0x285
            google.golang.org/grpc.(*Server).handleRawConn.func1()
            	/home/runner/work/grpc-go/grpc-go/server.go:891 +0x65
            created by google.golang.org/grpc.(*Server).handleRawConn
            	/home/runner/work/grpc-go/grpc-go/server.go:890 +0x24c
        grpctest.go:39: Leaked goroutine: goroutine 691 [chan send]:
            google.golang.org/grpc/xds/internal/xdsclient/transport_test.s.TestInvalidFirstResponse.func1(0x14e1400?, 0xc0004dc400)
            	/home/runner/work/grpc-go/grpc-go/xds/internal/xdsclient/transport/transport_ack_nack_test.go:268 +0x45
            github.com/envoyproxy/go-control-plane/pkg/server/v3.CallbackFuncs.OnStreamRequest(...)
            	/home/runner/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.2-0.20220325020618-49ff273808a1/pkg/server/v3/server.go:119
            github.com/envoyproxy/go-control-plane/pkg/server/sotw/v3.(*server).process(0xc00059a140, {0x7f9398a7dfc0, 0xc00045acd0}, 0xc0000a0f00?, {0x0, 0x0})
            	/home/runner/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.2-0.20220325020618-49ff273808a1/pkg/server/sotw/v3/server.go:181 +0x6a8
            github.com/envoyproxy/go-control-plane/pkg/server/sotw/v3.(*server).StreamHandler(0xc00059a140, {0x7f9398a7dfc0?, 0xc00045acd0}, {0x0, 0x0})
            	/home/runner/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.2-0.20220325020618-49ff273808a1/pkg/server/sotw/v3/server.go:256 +0x174
            github.com/envoyproxy/go-control-plane/pkg/server/v3.(*server).StreamHandler(...)
            	/home/runner/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.2-0.20220325020618-49ff273808a1/pkg/server/v3/server.go:183
            github.com/envoyproxy/go-control-plane/pkg/server/v3.(*server).StreamAggregatedResources(0xc00074a300?, {0x16df5d0?, 0xc00045acd0?})
            	/home/runner/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.2-0.20220325020618-49ff273808a1/pkg/server/v3/server.go:187 +0x83
            github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler({0x150c940?, 0xc00074a300}, {0x16ddcd0?, 0xc00077e000})
            	/home/runner/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.2-0.20220325020618-49ff273808a1/envoy/service/discovery/v3/ads.pb.go:298 +0xc3
            google.golang.org/grpc.(*Server).processStreamingRPC(0xc000223680, {0x16dfd38, 0xc000810680}, 0xc0000f7560, 0xc00074a480, 0x1f26c00, 0x0)
            	/home/runner/work/grpc-go/grpc-go/server.go:1619 +0x1f42
            google.golang.org/grpc.(*Server).handleStream(0xc000223680, {0x16dfd38, 0xc000810680}, 0xc0000f7560, 0x0)
            	/home/runner/work/grpc-go/grpc-go/server.go:1707 +0xfaf
            google.golang.org/grpc.(*Server).serveStreams.func1.2()
            	/home/runner/work/grpc-go/grpc-go/server.go:965 +0xed
            created by google.golang.org/grpc.(*Server).serveStreams.func1
            	/home/runner/work/grpc-go/grpc-go/server.go:963 +0x4de
        grpctest.go:60: Leak check disabled for future tests
FAIL
FAIL	google.golang.org/grpc/xds/internal/xdsclient/transport	13.190s
```

**Comment by easwars** [comment]
Fixed by https://github.com/grpc/grpc-go/pull/5830.
