### ISSUE TITLE
Flaky test: TestRoundRobin_AllServersDown hangs

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5964]
https://github.com/grpc/grpc-go/actions/runs/3991974901/jobs/6847366558

```
panic: test timed out after 7m0s

goroutine 109330 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:2036 +0x88
created by time.goFunc
	/opt/hostedtoolcache/go/1.19.5/x64/src/time/sleep.go:176 +0x38

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0x40008fe680, {0x6ddf9e?, 0x823025866f?}, 0x72e508)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1494 +0x33c
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1846 +0x70
testing.tRunner(0x40008fe680, 0x400025bcb8)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10c
testing.runTests(0x40000c3f40?, {0xc05eb0, 0x1, 0x1}, {0x3400000000000000?, 0x3408d07f2a812b2d?, 0xc1cd40?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1844 +0x3e8
testing.(*M).Run(0x40000c3f40)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1726 +0x500
main.main()
	_testmain.go:47 +0x1e8

goroutine 55658 [chan receive]:
testing.(*T).Run(0x40008fe820, {0x5c5446?, 0xc4d1a8?}, 0x400008ebe0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1494 +0x33c
google.golang.org/grpc/internal/grpctest.RunSubTests(0x1dc436c00481f00?, {0x6dc6a0?, 0xc4d1a8?})
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:101 +0x310
google.golang.org/grpc/test.Test(0x40008fe9c0?)
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:90 +0x2c
testing.tRunner(0x40008fe820, 0x72e508)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x328

goroutine 109311 [IO wait]:
internal/poll.runtime_pollWait(0x55287d1580, 0x72)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x400013ab00?, 0x1?, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x400013ab00)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_unix.go:614 +0x1d8
net.(*netFD).accept(0x400013ab00)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x40002e6168)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0x40002e6168)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock.go:288 +0x2c
google.golang.org/grpc.(*Server).Serve(0x400023c5a0, {0x7f0e38?, 0x40002e6168})
	/home/runner/work/grpc-go/grpc-go/server.go:823 +0x48c
created by google.golang.org/grpc/internal/stubserver.(*StubServer).StartServer
	/home/runner/work/grpc-go/grpc-go/internal/stubserver/stubserver.go:111 +0x414

goroutine 109305 [IO wait]:
internal/poll.runtime_pollWait(0x552863c0f0, 0x72)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x400013a200?, 0x1?, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x400013a200)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_unix.go:614 +0x1d8
net.(*netFD).accept(0x400013a200)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x40002e6018)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0x40002e6018)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock.go:288 +0x2c
google.golang.org/grpc.(*Server).Serve(0x400023c000, {0x7f0e38?, 0x40002e6018})
	/home/runner/work/grpc-go/grpc-go/server.go:823 +0x48c
created by google.golang.org/grpc/internal/stubserver.(*StubServer).StartServer
	/home/runner/work/grpc-go/grpc-go/internal/stubserver/stubserver.go:111 +0x414

goroutine 109329 [IO wait]:
internal/poll.runtime_pollWait(0x55287c1360, 0x72)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x400013ad00?, 0x1?, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x400013ad00)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_unix.go:614 +0x1d8
net.(*netFD).accept(0x400013ad00)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x40002e61b0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0x40002e61b0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock.go:288 +0x2c
google.golang.org/grpc.(*Server).Serve(0x400023c780, {0x7f0e38?, 0x40002e61b0})
	/home/runner/work/grpc-go/grpc-go/server.go:823 +0x48c
created by google.golang.org/grpc/internal/stubserver.(*StubServer).StartServer
	/home/runner/work/grpc-go/grpc-go/internal/stubserver/stubserver.go:111 +0x414

goroutine 109309 [IO wait]:
internal/poll.runtime_pollWait(0x55287d88b0, 0x72)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x400013a980?, 0x1?, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x400013a980)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_unix.go:614 +0x1d8
net.(*netFD).accept(0x400013a980)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x40002e6120)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0x40002e6120)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock.go:288 +0x2c
google.golang.org/grpc.(*Server).Serve(0x400023c3c0, {0x7f0e38?, 0x40002e6120})
	/home/runner/work/grpc-go/grpc-go/server.go:823 +0x48c
created by google.golang.org/grpc/internal/stubserver.(*StubServer).StartServer
	/home/runner/work/grpc-go/grpc-go/internal/stubserver/stubserver.go:111 +0x414

goroutine 109205 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0x4000328080)
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:115 +0x68
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:76 +0x224

goroutine 109307 [IO wait]:
internal/poll.runtime_pollWait(0x552863b970, 0x72)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x400013a780?, 0x1?, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x400013a780)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_unix.go:614 +0x1d8
net.(*netFD).accept(0x400013a780)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x40002e60d8)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0x40002e60d8)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/tcpsock.go:288 +0x2c
google.golang.org/grpc.(*Server).Serve(0x400023c1e0, {0x7f0e38?, 0x40002e60d8})
	/home/runner/work/grpc-go/grpc-go/server.go:823 +0x48c
created by google.golang.org/grpc/internal/stubserver.(*StubServer).StartServer
	/home/runner/work/grpc-go/grpc-go/internal/stubserver/stubserver.go:111 +0x414

goroutine 109317 [select]:
google.golang.org/grpc.(*ClientConn).waitForResolvedAddrs(0x40000be700, {0x7f19a8, 0x4000bee480})
	/home/runner/work/grpc-go/grpc-go/clientconn.go:573 +0xb0
google.golang.org/grpc.newClientStream({0x7f19a8, 0x4000bee480}, 0xc1c120, 0x40000be700, {0x6f6880, 0x23}, {0x0, 0x0, 0x0})
	/home/runner/work/grpc-go/grpc-go/stream.go:[186](https://github.com/grpc/grpc-go/actions/runs/3991974901/jobs/6847366558#step:8:187) +0x108
google.golang.org/grpc.invoke({0x7f19a8?, 0x4000bee480?}, {0x6f6880?, 0x550100c158?}, {0x65cca0, 0x40002083f0}, {0x65cca0, 0x4000208420}, 0x0?, {0x0?, ...})
	/home/runner/work/grpc-go/grpc-go/call.go:66 +0x6c
google.golang.org/grpc.(*ClientConn).Invoke(0x0?, {0x7f19a8?, 0x4000bee480?}, {0x6f6880?, 0x4000063800?}, {0x65cca0?, 0x40002083f0?}, {0x65cca0?, 0x4000208420?}, {0x0?, ...})
	/home/runner/work/grpc-go/grpc-go/call.go:37 +0x1a8
google.golang.org/grpc/test/grpc_testing.(*testServiceClient).EmptyCall(0x40004fe4c0, {0x7f19a8, 0x4000bee480}, 0x17?, {0x0, 0x0, 0x0})
	/home/runner/work/grpc-go/grpc-go/test/grpc_testing/test_grpc.pb.go:74 +0x94
google.golang.org/grpc/test.testRoundRobinBasic({0x7f19a8, 0x4000befb00}, 0x40013e0340, {0x0, 0x0, 0x0?})
	/home/runner/work/grpc-go/grpc-go/test/roundrobin_test.go:88 +0x738
google.golang.org/grpc/test.s.TestRoundRobin_AllServersDown({{}}, 0x40013e0340)
	/home/runner/work/grpc-go/grpc-go/test/roundrobin_test.go:224 +0x74
google.golang.org/grpc/internal/grpctest.RunSubTests.func1(0x40013e0340)
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:109 +0xbc
testing.tRunner(0x40013e0340, 0x400008ebe0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x328
FAIL	google.golang.org/grpc/test	420.239s
```

Not sure if this and https://github.com/grpc/grpc-go/issues/5961 are related, and the root cause is some other test or bug.

**Comment by easwars** [comment]
Another one: https://github.com/grpc/grpc-go/actions/runs/4008739685/jobs/6883275600

```
panic: test timed out after 7m0s

goroutine 110572 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:2036 +0x88
created by time.goFunc
	/opt/hostedtoolcache/go/1.19.5/x64/src/time/sleep.go:176 +0x38

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0x4000282000, {0x6dccfe?, 0x8211115b52?}, 0x72cc18)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1494 +0x33c
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1846 +0x70
testing.tRunner(0x4000282000, 0x400025bcb8)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10c
testing.runTests(0x40000a3f40?, {0xbf5e90, 0x1, 0x1}, {0x5600000000000000?, 0x5611aaf5a5c9973c?, 0xc0cd00?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1844 +0x3e8
testing.(*M).Run(0x40000a3f40)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1726 +0x500
main.main()
	_testmain.go:47 +0x1e8

goroutine 55324 [chan receive]:
testing.(*T).Run(0x40002821a0, {0x5c2654?, 0xc3d160?}, 0x40001f60c0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1494 +0x33c
google.golang.org/grpc/internal/grpctest.RunSubTests(0x2e26d12300000000?, {0x6db420?, 0xc3d160?})
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:101 +0x310
google.golang.org/grpc/test.Test(0x0?)
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:90 +0x2c
testing.tRunner(0x40002821a0, 0x72cc18)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x328

goroutine 110570 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0x4000356180)
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:115 +0x68
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:76 +0x224

goroutine 110569 [select]:
google.golang.org/grpc.(*ClientConn).scWatcher(0x40005c6000)
	/home/runner/work/grpc-go/grpc-go/clientconn.go:547 +0xb4
created by google.golang.org/grpc.DialContext
	/home/runner/work/grpc-go/grpc-go/clientconn.go:278 +0xd80

goroutine 110571 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0x400021e2c0)
	/home/runner/work/grpc-go/grpc-go/clientconn.go:1170 +0x494
google.golang.org/grpc.(*addrConn).connect(0x400021e2c0)
	/home/runner/work/grpc-go/grpc-go/clientconn.go:809 +0x228
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
	/home/runner/work/grpc-go/grpc-go/balancer_conn_wrappers.go:413 +0xf0

goroutine 110568 [sleep]:
time.Sleep(0x5f5e100)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/time.go:[195](https://github.com/grpc/grpc-go/actions/runs/4008739685/jobs/6883275600#step:8:196) +0x120
google.golang.org/grpc/test.testServiceConfigTimeoutTD(0x4000282820, {{0x6ea117, 0x15}, {0x6dca01, 0x3}, {0x0, 0x0}, 0x0, {0x0, 0x0}, ...})
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:5731 +0x588
google.golang.org/grpc/test.s.TestServiceConfigTimeoutTD({{}}, 0x0?)
	/home/runner/work/grpc-go/grpc-go/test/end2end_test.go:5682 +0xa4
google.golang.org/grpc/internal/grpctest.RunSubTests.func1(0x4000282820)
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:109 +0xbc
testing.tRunner(0x4000282820, 0x40001f60c0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x328
FAIL	google.golang.org/grpc/test	420.221s
```

It looks like *some* particular test is taking extraordinary amount of time which is causing the whole test target to timeout. And everytime, the stack trace is different, because a different test is running at the time when the test timeout expires.
