### ISSUE TITLE
Flaky test: Test/WatchResourceTimerCanRestartOnIgnoredADSRecvError

### ISSUE THREAD

**Issue by arvindbr8** [grpc/grpc-go#6070]
Test/WatchResourceTimerCanRestartOnIgnoredADSRecvError failed in this github action [job](https://github.com/grpc/grpc-go/actions/runs/4298404712/jobs/7492472964) with this following error

```
--- FAIL: Test (15.66s)
    --- FAIL: Test/WatchResourceTimerCanRestartOnIgnoredADSRecvError (15.05s)
        tlogger.go:116: INFO server.go:113 [xds-e2e] Created new snapshot cache...  (t=+74.1µs)
        tlogger.go:116: INFO server.go:632 [core] [Server #50] Server created  (t=+794.499µs)
        tlogger.go:116: INFO server.go:139 [xds-e2e] Registered Aggregated Discovery Service (ADS)...  (t=+905.499µs)
        tlogger.go:116: INFO server.go:143 [xds-e2e] xDS management server serving at: 127.0.0.1:33243...  (t=+984.799µs)
        tlogger.go:116: INFO clientconn.go:105 [core] [Channel #51] Channel created  (t=+1.132599ms)
        tlogger.go:116: INFO clientconn.go:1565 [core] [Channel #51] original dial target is: "127.0.0.1:33243"  (t=+1.202299ms)
        tlogger.go:116: INFO clientconn.go:1570 [core] [Channel #51] dial target "127.0.0.1:33243" parse failed: parse "127.0.0.1:33243": first path segment in URL cannot contain colon  (t=+1.294899ms)
        tlogger.go:116: INFO server.go:820 [core] [Server #50 ListenSocket #52] ListenSocket created  (t=+1.492999ms)
        tlogger.go:116: INFO clientconn.go:1585 [core] [Channel #51] fallback to scheme "passthrough"  (t=+1.742099ms)
        tlogger.go:116: INFO clientconn.go:1593 [core] [Channel #51] parsed dial target is: {Scheme:passthrough Authority: URL:{Scheme:passthrough Opaque: User: Host: Path:/127.0.0.1:33243 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+1.870299ms)
        tlogger.go:116: INFO clientconn.go:273 [core] [Channel #51] Channel authority set to "127.0.0.1:33243"  (t=+1.966499ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:175 [core] [Channel #51] Resolver state updated: {
              "Addresses": [
                {
                  "Addr": "127.0.0.1:33243",
                  "ServerName": "",
                  "Attributes": null,
                  "BalancerAttributes": null,
                  "Type": 0,
                  "Metadata": null
                }
              ],
              "ServiceConfig": null,
              "Attributes": null
            } (resolver returned new addresses)  (t=+2.19[219](https://github.com/grpc/grpc-go/actions/runs/4298404712/jobs/7492472964#step:8:220)8ms)
        tlogger.go:116: INFO balancer_conn_wrappers.go:274 [core] [Channel #51] Channel switches to new LB policy "pick_first"  (t=+2.380898ms)
        tlogger.go:116: INFO clientconn.go:735 [core] [Channel #51 SubChannel #53] Subchannel created  (t=+2.513498ms)
        tlogger.go:116: INFO clientconn.go:428 [core] [Channel #51] Channel Connectivity change to CONNECTING  (t=+2.585298ms)
        tlogger.go:116: INFO transport.go:238 Created transport to server "127.0.0.1:33243"  (t=+2.762398ms)
        tlogger.go:116: INFO clientconn.go:1116 [core] [Channel #51 SubChannel #53] Subchannel Connectivity change to CONNECTING  (t=+3.051798ms)
        tlogger.go:116: INFO clientconn.go:1227 [core] [Channel #51 SubChannel #53] Subchannel picks a new address "127.0.0.1:33243" to connect  (t=+3.182798ms)
        tlogger.go:116: INFO clientconn.go:1116 [core] [Channel #51 SubChannel #53] Subchannel Connectivity change to READY  (t=+4.166397ms)
        tlogger.go:116: INFO clientconn.go:428 [core] [Channel #51] Channel Connectivity change to READY  (t=+4.277297ms)
        tlogger.go:116: INFO transport.go:345 ADS stream created  (t=+4.424797ms)
        tlogger.go:116: INFO simple.go:374 [xds-e2e] open watch 1 for type.googleapis.com/envoy.config.listener.v3.Listener[xdsclient-test-lds-resourceA] from nodeID "059d0b97-d540-4a61-b1cf-05714e66fa48", version ""  (t=+5.279997ms)
        tlogger.go:116: INFO server.go:193 [xds-e2e] Created new resource snapshot...  (t=+5.631597ms)
        tlogger.go:116: INFO simple.go:234 [xds-e2e] respond open watch 1 type.googleapis.com/envoy.config.listener.v3.Listener[xdsclient-test-lds-resourceA] with new version "1"  (t=+5.730696ms)
        tlogger.go:116: INFO simple.go:421 [xds-e2e] respond type.googleapis.com/envoy.config.listener.v3.Listener[xdsclient-test-lds-resourceA] version "" with version "1"  (t=+5.807896ms)
        tlogger.go:116: INFO simple.go:354 [xds-e2e] nodeID "059d0b97-d540-4a61-b1cf-05714e66fa48" requested type.googleapis.com/envoy.config.listener.v3.Listener[xdsclient-test-lds-resourceA] and known map[xdsclient-test-lds-resourceA:{}]. Diff []  (t=+7.087496ms)
        tlogger.go:116: INFO simple.go:374 [xds-e2e] open watch 2 for type.googleapis.com/envoy.config.listener.v3.Listener[xdsclient-test-lds-resourceA] from nodeID "059d0b97-d540-4a61-b1cf-05714e66fa48", version "1"  (t=+7.[221](https://github.com/grpc/grpc-go/actions/runs/4298404712/jobs/7492472964#step:8:222)196ms)
        tlogger.go:116: INFO server.go:199 [xds-e2e] Updated snapshot cache with resource snapshot...  (t=+7.528495ms)
        authority_test.go:233: Test timed out before watcher received the update.
        tlogger.go:116: WARNING authority.go:375 Watchers not notified since ADS stream failed after having received at least one response: rpc error: code = Canceled desc = context canceled  (t=+5.005488947s)
        tlogger.go:116: WARNING transport.go:471 ADS stream closed: rpc error: code = Canceled desc = context canceled  (t=+5.005628447s)
        tlogger.go:116: INFO clientconn.go:428 [core] [Channel #51] Channel Connectivity change to SHUTDOWN  (t=+5.005749047s)
        tlogger.go:116: INFO clientconn.go:1116 [core] [Channel #51 SubChannel #53] Subchannel Connectivity change to SHUTDOWN  (t=+5.0059[222](https://github.com/grpc/grpc-go/actions/runs/4298404712/jobs/7492472964#step:8:223)47s)
        tlogger.go:116: INFO clientconn.go:1440 [core] [Channel #51 SubChannel #53] Subchannel deleted  (t=+5.006018546s)
        tlogger.go:116: INFO clientconn.go:1071 [core] [Channel #51] Channel deleted  (t=+5.006087146s)
        grpctest.go:39: Leaked goroutine: goroutine 2884 [IO wait]:
            internal/poll.runtime_pollWait(0x55283dad48, 0x72)
            	/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/netpoll.go:306 +0xa0
            internal/poll.(*pollDesc).wait(0x40000f[228](https://github.com/grpc/grpc-go/actions/runs/4298404712/jobs/7492472964#step:8:229)0?, 0x0?, 0x0)
            	/opt/hostedtoolcache/go/1.20.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0x28
            internal/poll.(*pollDesc).waitRead(...)
            	/opt/hostedtoolcache/go/1.20.1/x64/src/internal/poll/fd_poll_runtime.go:89
            internal/poll.(*FD).Accept(0x40000f2280)
            	/opt/hostedtoolcache/go/1.20.1/x64/src/internal/poll/fd_unix.go:614 +0x[250](https://github.com/grpc/grpc-go/actions/runs/4298404712/jobs/7492472964#step:8:251)
            net.(*netFD).accept(0x40000f2280)
            	/opt/hostedtoolcache/go/1.20.1/x64/src/net/fd_unix.go:172 +0x28
            net.(*TCPListener).accept(0x400000c7f8)
            	/opt/hostedtoolcache/go/1.20.1/x64/src/net/tcpsock_posix.go:148 +0x28
            net.(*TCPListener).Accept(0x400000c7f8)
            	/opt/hostedtoolcache/go/1.20.1/x64/src/net/tcpsock.go:297 +0x2c
            google.golang.org/grpc.(*Server).Serve(0x400017ef00, {0xac4710?, 0x400000c7f8})
            	/home/runner/work/grpc-go/grpc-go/server.go:824 +0x460
            created by google.golang.org/grpc/internal/testutils/xds/e2e.StartManagementServer
            	/home/runner/work/grpc-go/grpc-go/internal/testutils/xds/e2e/server.go:142 +0x5c4
        grpctest.go:60: Leak check disabled for future tests
FAIL
FAIL	google.golang.org/grpc/xds/internal/xdsclient	16.867s
ok  	google.golang.org/grpc/xds/internal/xdsclient/bootstrap	0.444s
ok  	google.golang.org/grpc/xds/internal/xdsclient/e2e_test	30.077s
ok  	google.golang.org/grpc/xds/internal/xdsclient/load	0.172s
ok  	google.golang.org/grpc/xds/internal/xdsclient/transport	3.742s
ok  	google.golang.org/grpc/xds/internal/xdsclient/xdsresource	3.364s
FAIL
```

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4327728155/jobs/7556694360

**Comment by arvindbr8** [comment]
There are two bugs here: 

1. The ctx times out before client receives an update. 
1. Mgmt server is not closed correctly in the event of Fatal error

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4378232100/jobs/7662709868

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4387398883/jobs/7682649491

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4433407281/jobs/7778410284

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4433407281/jobs/7778410433

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4419161188/jobs/7792212400?pr=6077 
![image](https://user-images.githubusercontent.com/16590502/225747093-c65ff86e-1353-4629-ab02-70cde24c9bec.png)

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4442029303/jobs/7797820552?pr=6125

**Comment by zasweq** [comment]
https://github.com/zasweq/grpc-go/actions/runs/4471782467/jobs/7857106140

**Comment by zasweq** [comment]
https://github.com/zasweq/grpc-go/actions/runs/4473251445/jobs/7860414205

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4473574106/jobs/7861110313?pr=6141

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4474684221/jobs/7863554449?pr=6125

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4481379488/jobs/7880362248?pr=6142

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4461092693/jobs/7880756640?pr=6139

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4461092693/jobs/7881025925?pr=6139

**Comment by zasweq** [comment]
https://github.com/zasweq/grpc-go/actions/runs/4485041712/jobs/7886168788

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4505722746/jobs/7931769063 I keep seeing this.

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4547965881/jobs/8018498428?pr=6132

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4547965881/jobs/8018787463?pr=6132

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4567215533/jobs/8061090036?pr=6155

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4567215533/jobs/8061090036?pr=6155

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4569781413/jobs/8066954043?pr=6160

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4596677575/jobs/8118442341?pr=6167

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4570393069/jobs/8067676964?pr=6163

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4663493798/jobs/8270048082?pr=6174

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4672956621/jobs/8275661989?pr=6187

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4683028763/jobs/8297612393?pr=6189

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4703999567/jobs/8343166025?pr=6161

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4704159235/jobs/8343513054?pr=6193

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4703999567/jobs/8343620060?pr=6161
