### ISSUE TITLE
GRPC Stream hangs undefinitly when writing a msg to the stream

### ISSUE THREAD

**Issue by ziggie1984** [grpc/grpc-go#6895]
Currently my program was having a deadlock because of a GRPC-Stream send request not being able to resolve for an hour, casing all other requests pile up and ending in a bad situation.

I was able to get the goroutine dump but I am now a bit stuck how to debug this scenario even further. Any ideas how to trace down the error even more would be highly appreciated. Thank you in advance :)

Currently the GRPC Streamer hang here:

```
goroutine 7699590 [select, 60 minutes]: 1 times: [[7699590]
google.golang.org/grpc/internal/transport.(*writeQuota).get(...)
        google.golang.org/grpc@v1.56.3/internal/transport/flowcontrol.go:59
google.golang.org/grpc/internal/transport.(*http2Server).Write(0xc1fd748340, 0xc1fc9f0120, {0xc030cd9b30, 0x5, 0x5}, {0xc03f29c600, 0x5ab, 0x5ab}, 0x0?)
        google.golang.org/grpc@v1.56.3/internal/transport/http2_server.go:1114 +0x205
google.golang.org/grpc.(*serverStream).SendMsg(0xc001bb05a0, {0x1d68fe0?, 0xc02b880320})
        google.golang.org/grpc@v1.56.3/stream.go:1651 +0x2a8
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).SendMsg(0xc1fc9cded8, {0x1d68fe0?, 0xc02b880320?})
...
```

I would think there must be some kind of timeout when a SendMsg requests takes too long, wondering what's happening here.

**Comment by ginayeh** [comment]
Can you provide details about how to repro the issue?  Are you seeing the deadlock 100% with your implementation?
