### ISSUE TITLE
Flaky Test: ADS_ResourcesAreRequestedAfterStreamRestart

### ISSUE THREAD

**Issue by arjan-bal** [grpc/grpc-go#7714]
Failing run: https://github.com/grpc/grpc-go/actions/runs/11253051356/job/31287508128?pr=7498

This seems to be a newly added test.

## Logs
```
--- FAIL: Test/ADS_ResourcesAreRequestedAfterStreamRestart (20.03s)
        ads_stream_restart_test.go:58: Created new snapshot cache...
        tlogger.go:116: INFO server.go:684 [core] [Server #661]Server created  (t=+746.688µs)
        ads_stream_restart_test.go:58: Registered Aggregated Discovery Service (ADS)...
        ads_stream_restart_test.go:58: xDS management server serving at: 127.0.0.1:44135...
        server.go:[229](https://github.com/grpc/grpc-go/actions/runs/11253051356/job/31287508128?pr=7498#step:8:230): Created new resource snapshot...
        server.go:235: Updated snapshot cache with resource snapshot...
        tlogger.go:116: INFO server.go:880 [core] [Server #661 ListenSocket #662]ListenSocket created  (t=+1.182611ms)
        tlogger.go:116: INFO client_refcounted.go:84 [xds] [xds-client 0x4000633440] Created client with name "Test/ADS_ResourcesAreRequestedAfterStreamRestart" and bootstrap configuration:
             {
              "xds_servers": [
               {
                "server_uri": "passthrough:///127.0.0.1:44135",
                "channel_creds": [
                 {
                  "type": "insecure"
                 }
                ]
               }
              ],
              "certificate_providers": {
               "client-side-certificate-provider-instance": {
                "plugin_name": "file_watcher",
                "config": {
                 "certificate_file": "/tmp/testClientSideXDS2953342875/cert.pem",
                 "private_key_file": "/tmp/testClientSideXDS2953342875/key.pem",
                 "ca_certificate_file": "/tmp/testClientSideXDS2953342875/ca.pem",
                 "refresh_interval": "600s"
                }
               },
               "server-side-certificate-provider-instance": {
                "plugin_name": "file_watcher",
                "config": {
                 "certificate_file": "/tmp/testServerSideXDS1884408869/cert.pem",
                 "private_key_file": "/tmp/testServerSideXDS1884408869/key.pem",
                 "ca_certificate_file": "/tmp/testServerSideXDS1884408869/ca.pem",
                 "refresh_interval": "600s"
                }
               }
              },
              "server_listener_resource_name_template": "grpc/server?xds.resource.listening_address=%s",
              "client_default_listener_resource_name_template": "%s",
              "node": {
               "id": "6c3f7137-b783-44b7-86d1-37f02cbb4c10",
               "locality": {}
              }
             }  (t=+3.4[230](https://github.com/grpc/grpc-go/actions/runs/11253051356/job/31287508128?pr=7498#step:8:231)13ms)
        tlogger.go:116: INFO client_refcounted.go:89 [xds] xDS node ID: 6c3f7137-b783-44b7-86d1-37f02cbb4c10  (t=+3.549832ms)
        tlogger.go:116: INFO clientconn.go:1652 [core] original dial target is: "passthrough:///127.0.0.1:44135"  (t=+3.682723ms)
        tlogger.go:116: INFO clientconn.go:314 [core] [Channel #663]Channel created  (t=+3.796898ms)
        tlogger.go:116: INFO clientconn.go:193 [core] [Channel #663]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"passthrough", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/127.0.0.1:44135", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}}  (t=+3.928[245](https://github.com/grpc/grpc-go/actions/runs/11253051356/job/31287508128?pr=7498#step:8:246)ms)
        tlogger.go:116: INFO clientconn.go:194 [core] [Channel #663]Channel authority set to "127.0.0.1:44135"  (t=+4.007755ms)
        tlogger.go:116: INFO resolver_wrapper.go:200 [core] [Channel #663]Resolver state updated: {
              "Addresses": [
                {
                  "Addr": "127.0.0.1:44135",
                  "ServerName": "",
                  "Attributes": null,
                  "BalancerAttributes": null,
                  "Metadata": null
                }
              ],
              "Endpoints": [
                {
                  "Addresses": [
                    {
                      "Addr": "127.0.0.1:44135",
                      "ServerName": "",
                      "Attributes": null,
                      "BalancerAttributes": null,
                      "Metadata": null
                    }
                  ],
                  "Attributes": null
                }
              ],
              "ServiceConfig": null,
        tlogger.go:116: INFO clientconn.go:1525 [core] [Channel #663 SubChannel #664]Subchannel deleted  (t=+10.011109592s)
        tlogger.go:116: INFO clientconn.go:314 [core] [Channel #663]Channel deleted  (t=+10.011288991s)
        tlogger.go:116: INFO clientimpl.go:101 [xds] [xds-client 0x4000633440] Shutdown  (t=+10.011540876s)
        tlogger.go:116: INFO server.go:816 [core] [Server #661 ListenSocket #662]ListenSocket deleted  (t=+10.011980825s)
        grpctest.go:44: Leaked goroutine: goroutine 4858 [chan send]:
            google.golang.org/grpc/internal/testutils.(*Channel).Send(...)
            	/home/runner/work/grpc-go/grpc-go/internal/testutils/channel.go:37
            google.golang.org/grpc/xds/internal/xdsclient/tests_test.(*listenerWatcher).OnUpdate(0x4000707aa0?, 0x400054e8a0?, 0x4000a04540)
            	/home/runner/work/grpc-go/grpc-go/xds/internal/xdsclient/tests/lds_watchers_test.go:75 +0x9c
            google.golang.org/grpc/xds/internal/xdsclient/xdsresource.(*delegatingListenerWatcher).OnUpdate(0x40008354ac?, {0x1018da8?, 0x40005a4900?}, 0x40006506a0?)
            	/home/runner/work/grpc-go/grpc-go/xds/internal/xdsclient/xdsresource/listener_resource_type.go:170 +0x48
            google.golang.org/grpc/xds/internal/xdsclient.(*authority).updateResourceStateAndScheduleCallbacks.func4({0x40008354a0?, 0x4000650710?})
            	/home/runner/work/grpc-go/grpc-go/xds/internal/xdsclient/authority.go:[262](https://github.com/grpc/grpc-go/actions/runs/11253051356/job/31287508128?pr=7498#step:8:263) +0x34
            google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0x40006404a0, {0x1018ad0, 0x400062abe0})
            	/home/runner/work/grpc-go/grpc-go/internal/grpcsync/callback_serializer.go:94 +0x110
            created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 4855
            	/home/runner/work/grpc-go/grpc-go/internal/grpcsync/callback_serializer.go:52 +0x118
        grpctest.go:71: Goroutine leak check disabled for future tests
```

**Comment by arjan-bal** [comment]
https://github.com/grpc/grpc-go/actions/runs/11260987853/job/31313422526?pr=7498
