### ISSUE TITLE
GracefulStop() is racy, leading to double-closing a channel

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#781]
Observed in CockroachDB.

I had to instrument grpc as follows:
```diff
diff --git a/transport/http2_server.go b/transport/http2_server.go
index 2322c93..1502942 100644
--- a/transport/http2_server.go
+++ b/transport/http2_server.go
@@ -37,11 +37,14 @@ import (
 	"bytes"
 	"errors"
 	"io"
+	"log"
 	"math"
 	"net"
 	"strconv"
 	"sync"
 
+	"github.com/cockroachdb/cockroach/util/caller"
+
 	"golang.org/x/net/context"
 	"golang.org/x/net/http2"
 	"golang.org/x/net/http2/hpack"
@@ -56,6 +59,12 @@ import (
 // the stream's state.
 var ErrIllegalHeaderWrite = errors.New("transport: the stream is done or WriteHeader was already called")
 
+type closer struct {
+	file string
+	line int
+	fun  string
+}
+
 // http2Server implements the ServerTransport interface with HTTP2.
 type http2Server struct {
 	conn        net.Conn
@@ -73,6 +82,8 @@ type http2Server struct {
 	hBuf         *bytes.Buffer  // the buffer for HPACK encoding
 	hEnc         *hpack.Encoder // HPACK encoder
 
+	closers []closer
+
 	// The max number of concurrent streams.
 	maxStreams uint32
 	// controlBuf delivers all the control related tasks (e.g., window
@@ -265,6 +276,7 @@ func (t *http2Server) HandleStreams(handle func(*Stream)) {
 				t.controlBuf.put(&resetStream{se.StreamID, se.Code})
 				continue
 			}
+			grpclog.Printf("transport: http2Server.HandleStreams failed to read frame: %v", err)
 			t.Close()
 			return
 		}
@@ -711,6 +723,15 @@ func (t *http2Server) Close() (err error) {
 		t.mu.Unlock()
 		return errors.New("transport: Close() was already called")
 	}
+	hadCloser := len(t.closers) > 0
+	file, line, fun := caller.Lookup(1)
+	t.closers = append(t.closers, closer{file, line, fun})
+	if hadCloser {
+		log.Printf("MULTIPLE CLOSERS IN STATE %v", t.state)
+		for _, closer := range t.closers {
+			log.Printf("%s:%d (%s)", closer.file, closer.line, closer.fun)
+		}
+	}
 	t.state = closing
 	streams := t.activeStreams
 	t.activeStreams = nil
```

Then running some tests that actually use GracefulStop() I see:
```
I160727 16:11:53.281672 stopper.go:408  quiesceing; tasks left: // <--- this is where GracefulStop() is called.
1      storage/queue.go:427
I160727 16:11:53.281679 http2_server.go:279  transport: http2Server.HandleStreams failed to read frame: EOF
I160727 16:11:53.281754 http2_server.go:730  MULTIPLE CLOSERS IN STATE 3
I160727 16:11:53.281763 http2_server.go:732  http2_server.go:280 ((*http2Server).HandleStreams)
I160727 16:11:53.281768 http2_server.go:732  /Users/tamird/src/go/src/google.golang.org/grpc/server.go:411 ((*Server).serveStreams)
panic: close of closed channel

goroutine 5194 [running]:
panic(0x50265a0, 0xc8200da9c0)
	/Users/tamird/src/go1.6/src/runtime/panic.go:481 +0x3e6
google.golang.org/grpc/transport.(*http2Server).Close(0xc8200f04d0, 0x0, 0x0)
	/Users/tamird/src/go/src/google.golang.org/grpc/transport/http2_server.go:739 +0x61f
google.golang.org/grpc.(*Server).serveStreams(0xc8205899a0, 0x96e1648, 0xc8200f04d0)
	/Users/tamird/src/go/src/google.golang.org/grpc/server.go:411 +0x168
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc8205899a0, 0x96e1548, 0xc820460300, 0x96e15a8, 0xc8200f0420)
	/Users/tamird/src/go/src/google.golang.org/grpc/server.go:396 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc8205899a0, 0x95589d8, 0xc8203ce0b0)
	/Users/tamird/src/go/src/google.golang.org/grpc/server.go:373 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/Users/tamird/src/go/src/google.golang.org/grpc/server.go:345 +0x38c
```

So it seems that:
  1. the client hangs up, causing the EOF and `Close()`ing the stream and `close()`ing its channel
  1. GracefulStop() is called
  1. The run-loop in `(*http2Server).controller()` receives the `goAway` and sets the stream to `draining` again (which is illegal, since it is already closed)
  1. GracefulStop() `Close()`es the stream again, causing a double close on the channel and panicking.

**Comment by iamqizhao** [comment]
Thanks for reporting. Looking ....
