### ISSUE TITLE
transport: build is broken with the SSA backend

### ISSUE THREAD

**Issue by rakyll** [grpc/grpc-go#836]
```
$ go version
go version devel +0958cd6 Mon Aug 15 23:24:31 2016 -0700 darwin/amd64


$ go build google.golang.org/grpc/transport
# google.golang.org/grpc/transport
../../../../google.golang.org/grpc/transport/http_util.go:248: internal compiler error: schedule does not include all values

goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/Users/jbd/go/src/runtime/debug/stack.go:24 +0x79
cmd/compile/internal/gc.Fatalf(0x60abc5, 0x24, 0x0, 0x0, 0x0)
	/Users/jbd/go/src/cmd/compile/internal/gc/subr.go:165 +0x248
cmd/compile/internal/gc.(*ssaExport).Fatalf(0x8e20a8, 0xc400000a98, 0x60abc5, 0x24, 0x0, 0x0, 0x0)
	/Users/jbd/go/src/cmd/compile/internal/gc/ssa.go:4569 +0x74
cmd/compile/internal/ssa.(*Config).Fatalf(0xc421490000, 0xa98, 0x60abc5, 0x24, 0x0, 0x0, 0x0)
	/Users/jbd/go/src/cmd/compile/internal/ssa/config.go:271 +0x6e
cmd/compile/internal/ssa.(*Func).Fatalf(0xc422232a50, 0x60abc5, 0x24, 0x0, 0x0, 0x0)
	/Users/jbd/go/src/cmd/compile/internal/ssa/func.go:397 +0x6b
cmd/compile/internal/ssa.schedule(0xc422232a50)
	/Users/jbd/go/src/cmd/compile/internal/ssa/schedule.go:257 +0x11ef
cmd/compile/internal/ssa.Compile(0xc422232a50)
	/Users/jbd/go/src/cmd/compile/internal/ssa/compile.go:64 +0x323
cmd/compile/internal/gc.buildssa(0xc4209caab0, 0x0)
	/Users/jbd/go/src/cmd/compile/internal/gc/ssa.go:235 +0xc5e
cmd/compile/internal/gc.compile(0xc4209caab0)
	/Users/jbd/go/src/cmd/compile/internal/gc/pgen.go:405 +0x1370
cmd/compile/internal/gc.funccompile(0xc4209caab0)
	/Users/jbd/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x186
cmd/compile/internal/gc.Main()
	/Users/jbd/go/src/cmd/compile/internal/gc/main.go:465 +0x19ab
cmd/compile/internal/amd64.Main()
	/Users/jbd/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa
main.main()
	/Users/jbd/go/src/cmd/compile/main.go:33 +0x2a3
```

**Comment by iamqizhao** [comment]
I have no clue what is going on here according to the error msg. Isn't it a ssa issue/bug instead?

**Comment by rakyll** [comment]
I am not sure what's wrong with the user code either. Filed a bug against the compiler at https://github.com/golang/go/issues/16741.

**Comment by rakyll** [comment]
Not a regression against 1.7. 1.8 devel breaks it, we can close the issue here.
